export type TeslaReportSection = { title: string; thesis: string; bullets: string[] };

export const TESLA_REPORT_SECTIONS: TeslaReportSection[] = [
  { title:"Executive Summary", thesis:"Tesla is simultaneously a scaled electric-vehicle manufacturer, a rapidly growing energy-storage supplier and a high-cost portfolio of physical-AI options. The market price depends far more on the last category than current earnings support.", bullets:["Q2 2026 revenue rose 26% to $28.2B and deliveries reached a record 480,126, yet operating margin fell to 1.4%.","Quarterly capex reached $5.8B and free cash flow was negative $1.1B as AI and factory investment accelerated.","At $354.08, Tesla's market capitalization is about $1.25T, roughly 11.3x Hobite's FY2026 revenue estimate."] },
  { title:"Company History", thesis:"Tesla evolved from a premium electric-vehicle entrant into the highest-scale Western EV producer, then expanded into batteries, charging, energy storage, autonomy and robotics.", bullets:["Model 3 and Model Y created manufacturing scale and funded global factories in the United States, China and Germany.","The energy business moved from a small solar and Powerwall operation toward utility-scale Megapack deployments.","Management now describes Tesla as a physical-AI company, making execution in Robotaxi, Cybercab and Optimus central to valuation."] },
  { title:"Business Model", thesis:"Automotive sales remain the economic base, while energy storage, services, charging and software subscriptions provide diversification with very different margin structures.", bullets:["Vehicle economics depend on volume, price, mix, factory utilization, battery costs, tariffs and incentives.","Regulatory credits carry negligible incremental cost but depend on changing policy and competitor demand.","FSD subscriptions and a potential autonomous fleet offer software-like economics, but commercial scale and liability economics remain unproven."] },
  { title:"Financial Quality", thesis:"Tesla has a net-cash balance sheet and positive annual free cash flow, but current earnings quality is pressured by low automotive margins, volatile credits, tax effects and rapidly rising investment.", bullets:["FY2025 revenue fell 3% to $94.8B and operating margin declined to 4.6%.","FY2025 free cash flow improved to $6.2B, but Tesla expects more than $20B of capex in 2026.","Q2 2026 net income benefited from a California deferred-tax valuation allowance release and mark-to-market gains, while operating income fell 57% year over year."] },
  { title:"Vehicle Economics", thesis:"Record Q2 deliveries show demand can respond to product transitions and pricing, but volume growth alone is not enough if contribution margins remain compressed.", bullets:["Q2 2026 deliveries rose 25% to 480,126 while production reached 451,758.","Total automotive gross margin was 16.9%, down from 17.2% a year earlier despite higher deliveries.","Global vehicle inventory fell to 15 days of supply, improving from 27 days in Q1."] },
  { title:"Energy and Infrastructure", thesis:"Energy storage is Tesla's clearest proven growth adjacency, with strong deployments and historically higher segment margins than the automotive operation.", bullets:["FY2025 energy revenue increased 27% to $12.8B and segment gross margin reached 29.8%.","Q2 2026 storage deployments reached 13.5 GWh, up 41% year over year.","Q2 energy gross margin fell to 20.4%, showing that deployment mix, pricing, tariffs and warranty adjustments can create volatility."] },
  { title:"Autonomy and Physical AI", thesis:"FSD, Robotaxi, Cybercab and Optimus may create exceptional economics, but they should be underwritten as staged options with technical, regulatory and utilization milestones.", bullets:["Active FSD subscriptions reached 1.48M in Q2 2026, up 56% year over year under Tesla's current definition.","Tesla reported Robotaxi launches in three Florida cities in July 2026 and began Cybercab production, but broad commercial economics are not yet established.","The base DCF assumes gradual software and autonomy contribution; only the bull case assumes large-scale physical-AI monetization."] },
  { title:"Balance Sheet and Capital Allocation", thesis:"Tesla's $43.5B of cash and investments provides substantial funding capacity, but the 2026 investment cycle is consuming cash faster than the mature automotive business currently replenishes it.", bullets:["H1 2026 capex was $8.3B versus $3.9B a year earlier, largely for AI and operational infrastructure.","Debt excluding finance leases was about $9.1B at Q2, leaving substantial net cash.","A $2.0B SpaceX equity investment adds related-party and mark-to-market considerations to capital allocation."] },
  { title:"Growth Drivers", thesis:"Near-term growth comes from refreshed vehicles, energy storage and services; long-term upside depends on FSD adoption, autonomous fleet utilization, Cybercab scale and Optimus productivity.", bullets:["Services revenue grew 50% in Q2 as used vehicles, maintenance, collision and paid Supercharging expanded.","Supercharger connectors increased 17% year over year to 82,357.","Sustained value creation requires new businesses to outrun automotive price pressure and the cost of AI infrastructure."] },
  { title:"Competition and Management", thesis:"Tesla retains meaningful brand, manufacturing, charging and data advantages, but competes against increasingly capable Chinese EV makers, global automakers, energy integrators and well-capitalized AI platforms.", bullets:["BYD and other Chinese manufacturers combine rapid product cycles, vertical integration and aggressive pricing.","Waymo and other autonomy developers pursue different technical and operating models with more constrained domains.","Elon Musk is a major strategic asset and a material key-person, governance and capital-allocation risk."] },
  { title:"Risks", thesis:"The central risks are valuation compression, automotive commoditization, autonomy delays or liability, policy changes, execution across simultaneous programs, key-person dependence and geopolitical exposure.", bullets:["Regulatory-credit revenue fell 67% year over year in Q2 after policy restrictions.","More than $20B of planned 2026 capex raises downside if autonomy and robotics milestones slip.","China exposure creates demand, competition, supply-chain, data-governance and geopolitical risks."] },
  { title:"Investment Conclusion", thesis:"Tesla offers unusually large real-option value, but today's price requires outcomes far beyond a healthy vehicle and energy manufacturer. Investors must distinguish evidence of physical-AI economics from product demonstrations and management ambition.", bullets:["The bear case values a slower-growth industrial and energy platform with no major autonomous profit pool.","The base case requires energy, software and autonomy to lift both growth and FCF margins materially through 2035.","The bull case can justify substantial value only if Tesla converts technical leadership into scaled, defensible and highly profitable physical-AI services."] },
];
