import type { ReactNode } from "react";
import { TESLA_ANNUAL_FINANCIALS, TESLA_ANNUAL_FINANCIALS_SOURCE_NOTE } from "./annualFinancials";
import { TESLA_CAPITAL_ECONOMICS, TESLA_CAPITAL_NOTE } from "./capitalEconomics";
import { TESLA_ANNUAL_FILINGS, TESLA_LATEST_ANNUAL_FILING, TESLA_LATEST_QUARTERLY_FILING, TESLA_QUARTERLY_FILINGS } from "./filings";
import { TESLA_DCF_CASES, TESLA_DCF_INPUTS, TESLA_FORECAST_NOTE, TESLA_FORECASTS, TESLA_VALUATION_NOTE } from "./forecastModel";
import { TESLA_2026_CAPEX_OUTLOOK, TESLA_Q2_2026 } from "./latestQuarter";
import { TESLA_LATEST_OPERATING_METRIC, TESLA_OPERATING_METRICS, TESLA_OPERATING_METRICS_NOTE } from "./operatingMetrics";
import { TESLA_PUBLICATION_QA_ITEMS } from "./publicationQa";
import { TESLA_QUARTERLY_FINANCIALS, TESLA_QUARTERLY_FINANCIALS_SOURCE_NOTE } from "./quarterlyFinancials";
import { TESLA_REPORT_SECTIONS } from "./reportContent";
import { TESLA_REPORT_SECTIONS_ZH } from "./reportContentZh";
import { TESLA_CHART_GROUPS, TESLA_SOURCE_SYSTEMS } from "./researchPlan";
import { TESLA_SEGMENT_ECONOMICS, TESLA_SEGMENT_NOTE } from "./segmentEconomics";
import { TESLA_SOURCE_AUDIT_ITEMS, TESLA_SOURCE_AUDIT_NOTE } from "./sourceAudit";
import { TESLA_LATEST_VALUATION, TESLA_VALUATION_HISTORY, TESLA_VALUATION_HISTORY_NOTE } from "./valuationHistory";

type Language = "en" | "zh";

const copy = {
  en: {
    lang: "中文", langHref: "/research/tesla-complete-fundamental-analysis/zh", updated: "Updated September 4, 2026 · TSLA · USD",
    eyebrow: "Complete Fundamental Research Hub", title: "Tesla", subtitle: "Vehicles fund the present. Energy is the proven adjacency. Autonomy and robotics carry most of the valuation debate.",
    nav: [["thesis","Thesis"],["latest","Latest"],["operations","Operations"],["segments","Segments"],["capital","Capital"],["valuation","Valuation"],["forecast","Forecast"],["financials","Financials"],["filings","Filings"],["sources","Sources"]],
    sections: { thesis:["Investment memo","An industrial base carrying physical-AI option value"], latest:["Latest quarter","Growth returned while cash investment accelerated"], operations:["Operating system","Vehicles, FSD, storage and charging"], segments:["Business economics","Automotive scale versus energy margin"], capital:["Capital intensity","A strong balance sheet entering a $20B-plus build cycle"], valuation:["Scenario valuation","What the current price asks investors to believe"], forecast:["Ten-year model","Explicit revenue and free-cash-flow paths"], financials:["SEC financial database","A decade of income statements and cash flow"], filings:["Primary documents","Tesla SEC filing inventory"], sources:["Research controls","Sources, audit trail and publication QA"] },
    metrics: ["Q2 2026 revenue","Q2 deliveries","Cash + investments","Reference price"], reportNote: "Assumptions are Hobite scenarios, not Tesla guidance.", disclaimer: "Research and education only, not personalized investment advice. Prices, guidance and forecasts can become stale.",
  },
  zh: {
    lang: "English", langHref: "/research/tesla-complete-fundamental-analysis", updated: "更新于 2026 年 9 月 4 日 · TSLA · 美元",
    eyebrow: "完整基本面研究中心", title: "特斯拉", subtitle: "汽车业务支撑当下，能源是已验证的增长邻接，而自动驾驶与机器人承载了大部分估值争议。",
    nav: [["thesis","投资逻辑"],["latest","最新季度"],["operations","运营指标"],["segments","分部"],["capital","资本"],["valuation","估值"],["forecast","预测"],["financials","财务"],["filings","文件"],["sources","来源"]],
    sections: { thesis:["投资备忘录","实体工业基础与物理 AI 期权价值"], latest:["最新季度","增长恢复，但现金投入显著加速"], operations:["运营系统","汽车、FSD、储能与充电网络"], segments:["业务经济性","汽车规模与能源利润率的对比"], capital:["资本强度","以强劲资产负债表进入 200 亿美元以上投资周期"], valuation:["情景估值","当前股价要求投资者相信什么"], forecast:["十年模型","明确的收入与自由现金流路径"], financials:["SEC 财务数据库","十年损益表与现金流历史"], filings:["原始文件","特斯拉 SEC 文件清单"], sources:["研究控制","来源、审计轨迹与发布 QA"] },
    metrics: ["FY2026 Q2 收入","Q2 交付量","现金与投资","参考股价"], reportNote: "所有预测均为 Hobite 情景假设，并非特斯拉指引。", disclaimer: "本页仅用于研究与教育，不构成个性化投资建议。市场价格、指引与预测可能迅速过时。",
  },
} as const;

const usd = (value: number | null, digits = 1) => value == null ? "-" : `$${(value / 1_000_000_000).toFixed(digits)}B`;
const pct = (value: number | null, digits = 1) => value == null ? "-" : `${value.toFixed(digits)}%`;
const multiple = (value: number | null, digits = 1) => value == null ? "-" : `${value.toFixed(digits)}x`;
const integer = new Intl.NumberFormat("en-US");
const th = "whitespace-nowrap border-b border-zinc-200 bg-zinc-100 px-3 py-2 text-left text-xs font-semibold text-zinc-600";
const td = "whitespace-nowrap border-b border-zinc-100 px-3 py-2 text-sm text-zinc-700";

function Section({ id, eyebrow, title, note, children }: { id: string; eyebrow: string; title: string; note?: string; children: ReactNode }) {
  return <section id={id} className="border-t border-zinc-200 py-10"><div className="mb-6 max-w-4xl"><p className="text-xs font-semibold uppercase text-red-700">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold text-zinc-950 md:text-3xl">{title}</h2>{note ? <p className="mt-3 text-sm leading-6 text-zinc-600">{note}</p> : null}</div>{children}</section>;
}

function TableFrame({ children }: { children: ReactNode }) { return <div className="overflow-x-auto border border-zinc-200 bg-white">{children}</div>; }

function HeroMetric({ label, value, detail, warm = false }: { label: string; value: string; detail: string; warm?: boolean }) {
  return <div className={`border-l-2 pl-4 ${warm ? "border-amber-400" : "border-red-500"}`}><p className="text-xs font-medium uppercase text-zinc-400">{label}</p><p className="mt-1 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs leading-5 text-zinc-400">{detail}</p></div>;
}

export function TeslaResearchView({ language }: { language: Language }) {
  const t = copy[language];
  const reportSections = language === "zh" ? TESLA_REPORT_SECTIONS_ZH : TESLA_REPORT_SECTIONS;
  const annualMax = Math.max(...TESLA_ANNUAL_FINANCIALS.map((row) => row.revenue ?? 0));
  const dcfCases = Object.values(TESLA_DCF_CASES);
  const latest = TESLA_LATEST_OPERATING_METRIC;
  const labels = language === "zh" ? {
    source: "官方来源", annual: "年度历史", quarterly: "最近季度", history: "历史市场估值", audit: "来源审计", qa: "发布检查",
    period:"期间", revenue:"收入", gross:"毛利润", opIncome:"经营利润", netIncome:"净利润", ocf:"经营现金流", capex:"资本开支", fcf:"自由现金流", margin:"利润率",
    production:"产量", deliveries:"交付量", fsd:"FSD 订阅", inventory:"库存天数", storage:"储能部署", stations:"超充站", connectors:"充电桩",
    automotive:"汽车收入", energy:"能源收入", services:"服务收入", credits:"监管积分", autoMargin:"汽车毛利率", energyMargin:"能源毛利率",
    cash:"现金与投资", debt:"债务", rd:"研发", price:"股价", marketCap:"市值", ev:"企业价值", ps:"市销率", evSales:"EV/收入", pe:"市盈率", yield:"FCF 收益率",
    year:"年份", bear:"悲观", base:"基准", bull:"乐观", reports:"年度报告", quarterlies:"季度报告", filed:"提交日期", reportDate:"报告日期",
  } : {
    source:"Official source", annual:"Annual history", quarterly:"Recent quarters", history:"Historical market valuation", audit:"Source audit", qa:"Publication checks",
    period:"Period", revenue:"Revenue", gross:"Gross profit", opIncome:"Operating income", netIncome:"Net income", ocf:"Operating cash flow", capex:"Capex", fcf:"Free cash flow", margin:"Margin",
    production:"Production", deliveries:"Deliveries", fsd:"FSD subscriptions", inventory:"Inventory days", storage:"Storage GWh", stations:"Supercharger stations", connectors:"Connectors",
    automotive:"Automotive revenue", energy:"Energy revenue", services:"Services revenue", credits:"Regulatory credits", autoMargin:"Auto gross margin", energyMargin:"Energy gross margin",
    cash:"Cash + investments", debt:"Debt", rd:"R&D", price:"Price", marketCap:"Market cap", ev:"Enterprise value", ps:"P/S", evSales:"EV/Sales", pe:"P/E", yield:"FCF yield",
    year:"Year", bear:"Bear", base:"Base", bull:"Bull", reports:"Annual reports", quarterlies:"Quarterly reports", filed:"Filed", reportDate:"Report date",
  };

  return <main className="min-h-screen bg-zinc-50 text-zinc-900">
    <header className="border-b border-zinc-800 bg-zinc-950 text-white">
      <div className="mx-auto max-w-7xl px-5 py-10 md:px-8">
        <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-zinc-400"><a href="/research" className="font-medium text-red-400 hover:text-red-300">Hobite Research</a><div className="flex items-center gap-4"><span>{t.updated}</span><a href={t.langHref} className="border border-zinc-700 px-3 py-1 text-white hover:border-zinc-500">{t.lang}</a></div></div>
        <p className="mt-8 text-xs font-semibold uppercase text-red-400">{t.eyebrow}</p><h1 className="mt-3 max-w-5xl text-4xl font-semibold leading-tight md:text-6xl">{t.title}</h1><p className="mt-4 max-w-4xl text-lg leading-8 text-zinc-300">{t.subtitle}</p>
        <div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4"><HeroMetric label={t.metrics[0]} value={usd(TESLA_Q2_2026.revenue)} detail={`${pct(TESLA_Q2_2026.revenueGrowth,0)} YoY · ${pct(TESLA_Q2_2026.operatingMargin)} op. margin`} /><HeroMetric label={t.metrics[1]} value={integer.format(latest.deliveries)} detail={`${integer.format(latest.production)} produced`} /><HeroMetric label={t.metrics[2]} value={usd(TESLA_Q2_2026.cashAndInvestments)} detail={`${usd(43_524_000_000 - 9_061_000_000)} net cash`} /><HeroMetric label={t.metrics[3]} value={`$${TESLA_DCF_INPUTS.referencePrice.toFixed(2)}`} detail={`${multiple(TESLA_LATEST_VALUATION.priceToSales)} FY2026E P/S`} warm /></div>
      </div>
    </header>
    <nav className="sticky top-0 z-10 overflow-x-auto border-b border-zinc-200 bg-white/95 px-5 backdrop-blur md:px-8"><div className="mx-auto flex max-w-7xl gap-6 py-3 text-xs font-medium text-zinc-600">{t.nav.map(([id,label]) => <a key={id} href={`#${id}`} className="whitespace-nowrap hover:text-red-700">{label}</a>)}</div></nav>
    <div className="mx-auto max-w-7xl px-5 md:px-8">
      <Section id="thesis" eyebrow={t.sections.thesis[0]} title={t.sections.thesis[1]}><div className="grid gap-px border border-zinc-200 bg-zinc-200 md:grid-cols-2">{reportSections.map((section) => <article key={section.title} className="bg-white p-5"><h3 className="text-lg font-semibold text-zinc-950">{section.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-700">{section.thesis}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-zinc-600">{section.bullets.map((bullet) => <li key={bullet} className="border-l border-zinc-300 pl-3">{bullet}</li>)}</ul></article>)}</div></Section>
      <Section id="latest" eyebrow={t.sections.latest[0]} title={t.sections.latest[1]} note={TESLA_Q2_2026.note}><div className="grid gap-px border border-zinc-200 bg-zinc-200 sm:grid-cols-2 lg:grid-cols-4">{[[labels.gross,usd(TESLA_Q2_2026.grossProfit)],[labels.opIncome,usd(TESLA_Q2_2026.operatingIncome)],[labels.netIncome,usd(TESLA_Q2_2026.gaapNetIncome)],[labels.fcf,usd(TESLA_Q2_2026.freeCashFlow)]].map(([label,value]) => <div key={label} className="bg-white p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div><div className="mt-6 border-l-2 border-amber-500 bg-amber-50 p-5"><p className="text-xs font-semibold uppercase text-amber-800">2026 Capex outlook</p><p className="mt-2 text-2xl font-semibold">{language === "zh" ? "超过" : "Above"} {usd(TESLA_2026_CAPEX_OUTLOOK.minimum,0)}</p><p className="mt-2 max-w-4xl text-sm leading-6 text-zinc-700">{TESLA_2026_CAPEX_OUTLOOK.note}</p><a href={TESLA_2026_CAPEX_OUTLOOK.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs underline">{labels.source}</a></div></Section>
      <Section id="operations" eyebrow={t.sections.operations[0]} title={t.sections.operations[1]} note={TESLA_OPERATING_METRICS_NOTE}><TableFrame><table className="w-full min-w-[980px] border-collapse"><thead><tr>{[labels.period,labels.production,labels.deliveries,labels.fsd,labels.inventory,labels.storage,labels.stations,labels.connectors].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{TESLA_OPERATING_METRICS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.sourceUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{integer.format(row.production)}</td><td className={td}>{integer.format(row.deliveries)}</td><td className={td}>{integer.format(row.fsdSubscriptions)}</td><td className={td}>{row.inventoryDays}</td><td className={td}>{row.storageGwh.toFixed(1)}</td><td className={td}>{integer.format(row.superchargerStations)}</td><td className={td}>{integer.format(row.superchargerConnectors)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="segments" eyebrow={t.sections.segments[0]} title={t.sections.segments[1]} note={TESLA_SEGMENT_NOTE}><TableFrame><table className="w-full min-w-[860px] border-collapse"><thead><tr>{[labels.period,labels.automotive,labels.energy,labels.services,labels.credits,labels.autoMargin,labels.energyMargin].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{TESLA_SEGMENT_ECONOMICS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.sourceUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{usd(row.automotiveRevenue)}</td><td className={td}>{usd(row.energyRevenue)}</td><td className={td}>{usd(row.servicesRevenue)}</td><td className={td}>{usd(row.regulatoryCredits)}</td><td className={td}>{pct(row.automotiveGrossMargin)}</td><td className={td}>{pct(row.energyGrossMargin)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="capital" eyebrow={t.sections.capital[0]} title={t.sections.capital[1]} note={TESLA_CAPITAL_NOTE}><TableFrame><table className="w-full min-w-[900px] border-collapse"><thead><tr>{[labels.period,labels.cash,labels.debt,labels.capex,labels.fcf,labels.rd,labels.credits].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{TESLA_CAPITAL_ECONOMICS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.sourceUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{usd(row.cashAndInvestments)}</td><td className={td}>{usd(row.totalDebt)}</td><td className={td}>{usd(row.capitalExpenditures)}</td><td className={td}>{usd(row.freeCashFlow)}</td><td className={td}>{usd(row.researchAndDevelopment)}</td><td className={td}>{usd(row.regulatoryCredits)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="valuation" eyebrow={t.sections.valuation[0]} title={t.sections.valuation[1]} note={TESLA_VALUATION_NOTE}><div className="grid gap-px border border-zinc-200 bg-zinc-200 md:grid-cols-3">{dcfCases.map((item) => <article key={item.label} className="bg-white p-5"><div className="flex items-baseline justify-between gap-3"><h3 className="text-lg font-semibold">{language === "zh" ? ({Bear:labels.bear,Base:labels.base,Bull:labels.bull} as Record<string,string>)[item.label] : item.label}</h3><span className={`text-sm font-semibold ${item.upsideToReferencePrice >= 0 ? "text-emerald-700" : "text-rose-700"}`}>{pct(item.upsideToReferencePrice)}</span></div><p className="mt-5 text-4xl font-semibold">${item.valuePerShare.toFixed(0)}</p><p className="mt-4 text-sm text-zinc-500">{pct(item.discountRate)} discount · {pct(item.terminalGrowth)} terminal growth</p></article>)}</div><p className="mt-3 text-xs text-zinc-500">{t.reportNote} Reference: ${TESLA_DCF_INPUTS.referencePrice.toFixed(2)} on {TESLA_DCF_INPUTS.referencePriceDate}.</p><h3 className="mt-8 text-lg font-semibold">{labels.history}</h3><p className="mt-2 text-sm text-zinc-600">{TESLA_VALUATION_HISTORY_NOTE}</p><TableFrame><table className="mt-4 w-full min-w-[900px] border-collapse"><thead><tr>{[labels.year,labels.price,labels.marketCap,labels.ev,labels.ps,labels.evSales,labels.pe,labels.yield].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{TESLA_VALUATION_HISTORY.map((row) => <tr key={row.fiscalYear}><td className={td}>{row.fiscalYear}</td><td className={td}>{row.adjustedClose == null ? "-" : `$${row.adjustedClose.toFixed(2)}`}</td><td className={td}>{usd(row.marketCapitalization,0)}</td><td className={td}>{usd(row.enterpriseValue,0)}</td><td className={td}>{multiple(row.priceToSales)}</td><td className={td}>{multiple(row.enterpriseValueToSales)}</td><td className={td}>{multiple(row.priceToEarnings)}</td><td className={td}>{pct(row.freeCashFlowYield)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="forecast" eyebrow={t.sections.forecast[0]} title={t.sections.forecast[1]} note={TESLA_FORECAST_NOTE}><TableFrame><table className="w-full min-w-[850px] border-collapse"><thead><tr><th className={th}>{labels.year}</th>{([labels.bear,labels.base,labels.bull]).map((label) => <th key={label} className={th}>{label}: {labels.revenue} / growth / {labels.fcf}</th>)}</tr></thead><tbody>{TESLA_FORECASTS.base.map((baseRow,index) => <tr key={baseRow.year}><td className={`${td} font-medium`}>{baseRow.year}</td>{(["bear","base","bull"] as const).map((scenario) => { const row = TESLA_FORECASTS[scenario][index]!; return <td key={scenario} className={td}>{usd(row.revenue)} <span className="text-zinc-400">/ {pct(row.revenueGrowth)} / {usd(row.freeCashFlow)}</span></td>; })}</tr>)}</tbody></table></TableFrame></Section>
      <Section id="financials" eyebrow={t.sections.financials[0]} title={t.sections.financials[1]} note={TESLA_ANNUAL_FINANCIALS_SOURCE_NOTE}><h3 className="text-lg font-semibold">{labels.revenue}</h3><div className="mt-4 grid gap-2">{TESLA_ANNUAL_FINANCIALS.map((row) => <div key={row.fiscalYear} className="grid grid-cols-[52px_1fr_76px] items-center gap-3 text-xs"><span>FY{row.fiscalYear}</span><div className="h-3 bg-zinc-200"><div className="h-full bg-red-600" style={{width:`${((row.revenue ?? 0)/annualMax)*100}%`}} /></div><span className="text-right">{usd(row.revenue,0)}</span></div>)}</div><h3 className="mt-8 text-lg font-semibold">{labels.annual}</h3><TableFrame><table className="mt-4 w-full min-w-[1120px] border-collapse"><thead><tr>{[labels.year,labels.revenue,labels.gross,labels.opIncome,labels.netIncome,labels.ocf,labels.capex,labels.fcf,labels.cash,labels.debt,"Gross margin","FCF margin"].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{TESLA_ANNUAL_FINANCIALS.map((row) => <tr key={row.fiscalYear}><td className={`${td} font-medium`}><a href={row.filingUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.fiscalYear}</a></td><td className={td}>{usd(row.revenue)}</td><td className={td}>{usd(row.grossProfit)}</td><td className={td}>{usd(row.operatingIncome)}</td><td className={td}>{usd(row.netIncome)}</td><td className={td}>{usd(row.operatingCashFlow)}</td><td className={td}>{usd(row.capitalExpenditures)}</td><td className={td}>{usd(row.freeCashFlow)}</td><td className={td}>{usd((row.cash ?? 0)+(row.shortTermInvestments ?? 0))}</td><td className={td}>{usd(row.totalDebt)}</td><td className={td}>{pct(row.grossMargin)}</td><td className={td}>{pct(row.freeCashFlowMargin)}</td></tr>)}</tbody></table></TableFrame><h3 className="mt-8 text-lg font-semibold">{labels.quarterly}</h3><p className="mt-2 text-sm text-zinc-600">{TESLA_QUARTERLY_FINANCIALS_SOURCE_NOTE}</p><TableFrame><table className="mt-4 w-full min-w-[980px] border-collapse"><thead><tr>{[labels.period,labels.revenue,labels.gross,labels.opIncome,labels.netIncome,labels.ocf,labels.capex,labels.fcf,"Gross margin","FCF margin"].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{TESLA_QUARTERLY_FINANCIALS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.filingUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{usd(row.revenue)}</td><td className={td}>{usd(row.grossProfit)}</td><td className={td}>{usd(row.operatingIncome)}</td><td className={td}>{usd(row.netIncome)}</td><td className={td}>{usd(row.operatingCashFlow)}</td><td className={td}>{usd(row.capitalExpenditures)}</td><td className={td}>{usd(row.freeCashFlow)}</td><td className={td}>{pct(row.grossMargin)}</td><td className={td}>{pct(row.freeCashFlowMargin)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="filings" eyebrow={t.sections.filings[0]} title={t.sections.filings[1]}><div className="grid gap-5 lg:grid-cols-2">{[{title:labels.reports,rows:TESLA_ANNUAL_FILINGS},{title:labels.quarterlies,rows:TESLA_QUARTERLY_FILINGS}].map((group) => <div key={group.title}><h3 className="mb-3 text-lg font-semibold">{group.title}</h3><TableFrame><table className="w-full border-collapse"><thead><tr><th className={th}>Form</th><th className={th}>{labels.reportDate}</th><th className={th}>{labels.filed}</th></tr></thead><tbody>{group.rows.map((filing) => <tr key={filing.accessionNumber}><td className={td}><a href={filing.url} target="_blank" rel="noreferrer" className="font-medium underline decoration-zinc-300">{filing.form}</a></td><td className={td}>{filing.reportDate || "-"}</td><td className={td}>{filing.filingDate}</td></tr>)}</tbody></table></TableFrame></div>)}</div><p className="mt-3 text-xs text-zinc-500">Latest 10-K: {TESLA_LATEST_ANNUAL_FILING.filingDate}. Latest 10-Q: {TESLA_LATEST_QUARTERLY_FILING.filingDate}.</p></Section>
      <Section id="sources" eyebrow={t.sections.sources[0]} title={t.sections.sources[1]} note={TESLA_SOURCE_AUDIT_NOTE}><div className="grid gap-6 lg:grid-cols-2"><div><h3 className="mb-3 text-lg font-semibold">{labels.source}</h3><div className="divide-y divide-zinc-200 border border-zinc-200 bg-white">{TESLA_SOURCE_SYSTEMS.map((source) => <a key={source.name} href={source.url} target="_blank" rel="noreferrer" className="block p-4 hover:bg-zinc-50"><p className="text-sm font-semibold">{source.name}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{source.use}</p></a>)}</div></div><div><h3 className="mb-3 text-lg font-semibold">{labels.audit}</h3><div className="divide-y divide-zinc-200 border border-zinc-200 bg-white">{TESLA_SOURCE_AUDIT_ITEMS.map((item) => <a key={item.area} href={item.sourceUrl} target="_blank" rel="noreferrer" className="block p-4 hover:bg-zinc-50"><div className="flex justify-between gap-4"><p className="text-sm font-semibold">{item.area}</p><span className="text-xs font-medium uppercase text-emerald-700">{item.status}</span></div><p className="mt-1 text-xs leading-5 text-zinc-500">{item.coverage}. {item.note}</p></a>)}</div></div></div><h3 className="mt-8 text-lg font-semibold">{labels.qa}</h3><div className="mt-4 grid gap-px border border-zinc-200 bg-zinc-200 md:grid-cols-2">{TESLA_PUBLICATION_QA_ITEMS.map((item) => <div key={item.check} className="bg-white p-4"><div className="flex justify-between gap-4"><p className="text-sm font-semibold">{item.check}</p><span className={`text-xs font-semibold uppercase ${item.status === "pass" ? "text-emerald-700" : "text-amber-700"}`}>{item.status}</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{item.evidence}</p></div>)}</div><div className="mt-8 border-l-2 border-zinc-900 pl-4 text-xs leading-5 text-zinc-500"><p>{TESLA_CHART_GROUPS.reduce((sum,group) => sum+group.targetCount,0)} analytical views across {TESLA_CHART_GROUPS.length} groups.</p><p className="mt-1">{t.disclaimer}</p></div></Section>
    </div>
  </main>;
}
