export type NvidiaReportSection = { title: string; thesis: string; bullets: string[] };

export const NVIDIA_REPORT_SECTIONS: NvidiaReportSection[] = [
  { title:"Executive Summary", thesis:"NVIDIA is the control plane for accelerated computing, combining processors, systems, networking, software and a developer ecosystem into unusually strong platform economics.", bullets:["Q2 FY2027 revenue doubled to $96.2B and Data Center reached $89.0B.","GAAP gross margin was 75.0% and operating margin was 66.2%.","At $230.36, valuation already capitalizes a long runway of AI infrastructure expansion."] },
  { title:"Company History", thesis:"NVIDIA evolved from PC graphics into a full-stack accelerated-computing company through CUDA, data-center systems and high-speed networking.", bullets:["CUDA converted GPU programmability into a durable developer and software moat.","Mellanox added InfiniBand and Ethernet networking to the compute platform.","Hopper, Blackwell and Vera Rubin moved NVIDIA from chips toward rack-scale AI infrastructure."] },
  { title:"Business Model", thesis:"NVIDIA monetizes architecture leadership through chips, boards, complete systems, networking, software and services, while relying on a global fabless supply chain.", bullets:["Data Center represents more than 90% of current quarterly revenue.","Hyperscalers and AI clouds purchase integrated compute and networking systems.","Edge Computing spans gaming, workstation, automotive and local AI markets."] },
  { title:"Financial Quality", thesis:"Growth, margins and cash generation are exceptional, but equity-security gains and working-capital expansion make GAAP net income less informative than operating profit and cash flow alone.", bullets:["FY2026 revenue grew 65% to $215.9B and operating income reached $130.4B.","Q2 FY2027 operating cash flow was $24.1B despite a $22.3B increase in receivables.","H1 net income included $23.7B of gains from equity securities."] },
  { title:"Platform Economics", thesis:"The moat is system-level: accelerated compute, NVLink, networking, CUDA libraries and deployment tooling raise performance while increasing customer integration costs.", bullets:["Q2 Data Center revenue grew 117% to $89.0B.","Hyperscale revenue was $48.7B; AI Clouds, Industrial & Enterprise was $40.3B.","Blackwell remained the vast majority of revenue while Rubin entered production shipments in Q3 FY2027."] },
  { title:"Supply and Capacity", thesis:"Long-lead procurement secures growth but transfers demand-forecast risk onto NVIDIA as commitments become larger than annual revenue.", bullets:["Supply and capacity commitments rose to $279B from $119B one quarter earlier.","Inventory reached $31.6B, up from $21.4B at FY2026 year-end.","FY2026 included a $4.5B H20 excess-inventory and purchase-obligation charge."] },
  { title:"Balance Sheet and Capital Allocation", thesis:"NVIDIA has substantial liquidity and cash generation, while strategic investments, debt issuance and infrastructure support are making capital allocation more complex.", bullets:["Cash and marketable debt and equity securities totaled $99.4B at Q2.","Debt increased to $33.4B after a $25B senior-note issuance.","NVIDIA repurchased $39.0B of shares in H1 FY2027 and retained $99B of authorization."] },
  { title:"Growth Drivers", thesis:"Demand is expanding from model training into inference, agents, sovereign AI, enterprise workloads, networking and physical AI.", bullets:["Q3 guidance calls for $108B of revenue without China Data Center compute revenue.","Rubin provides the next architecture transition after Blackwell Ultra.","Networking, enterprise adoption and software can broaden revenue beyond hyperscale training clusters."] },
  { title:"Competition", thesis:"NVIDIA competes against custom accelerators, AMD, merchant networking, emerging domestic Chinese platforms and customers seeking lower total cost and supplier leverage.", bullets:["Hyperscalers can shift workloads to internally designed ASICs.","Open software layers may reduce CUDA switching friction over time.","Architecture transitions require simultaneous execution across compute, memory, networking, cooling and systems."] },
  { title:"Management and Governance", thesis:"Founder-led technical strategy has produced extraordinary results, while expanding investments and guarantees require increasingly disciplined disclosure and capital governance.", bullets:["Jensen Huang remains central to product vision and ecosystem relationships.","Strategic stakes may strengthen demand but can blur customer financing and investment returns.","Compensation, succession and related ecosystem commitments deserve continued monitoring."] },
  { title:"Risks", thesis:"The largest risks are an AI capital-spending correction, customer concentration, export controls, supply mismatches, competition, and contingent infrastructure exposure.", bullets:["Two direct customers represented 22% and 14% of FY2026 revenue.","NVIDIA says it is effectively foreclosed from China's data-center compute market under current rules.","Q2 disclosures include $36B of AI-cloud commitments, $20B of third-party leases and material guarantees."] },
  { title:"Valuation", thesis:"A strong business can still be a weak investment if growth duration and terminal margins are overestimated; the current price requires sustained scale and cash conversion.", bullets:["The bear case assumes demand normalizes and FCF margin falls toward 24%.","The base case assumes a long AI build cycle and high-30s mature FCF margins.","The bull case requires NVIDIA to remain the dominant full-stack platform through multiple architecture generations."] },
  { title:"Investment Conclusion", thesis:"NVIDIA has the strongest demonstrated economics in AI infrastructure, but investors are underwriting both technological leadership and the solvency and utilization of an increasingly financed ecosystem.", bullets:["Track Data Center growth and gross margin together, not accelerator demand alone.","Monitor inventory, receivables, supply commitments, cloud agreements and guarantees as a single risk system.","A durable thesis requires Rubin execution and widening enterprise inference demand after hyperscale growth matures."] },
];
