export type Company = {
  ticker: string; name: string; layer: string; layerZh: string;
  price: number; equityValue: number; revenue: number; baseline: string;
  growth: [number, number, number]; margin: [number, number]; da: [number, number]; capex: [number, number];
  tax: number; workingCapital: number; interest: number; preferred: number;
  terminalMultiple: number; durability: number; risk: number;
  thesis: string; thesisZh: string; failure: string; failureZh: string; source: string;
};

// USD billions, except price. Annual run-rate estimates are research inputs, not issuer guidance.
export const COMPANIES: Company[] = [
  { ticker: "MSFT", name: "Microsoft", layer: "Enterprise distribution + cloud", layerZh: "企业分发与云", price: 517.53, equityValue: 3853.01085, revenue: 331.839, baseline: "FY2026 reported / 已披露财年", growth: [.13,.09,.05], margin: [.47,.43], da: [.11,.18], capex: [.35,.24], tax: .18, workingCapital: .03, interest: 1, preferred: 0, terminalMultiple: 24, durability: 9, risk: 3, thesis: "Identity, Office, developer tools and Azure distribute AI inside existing budgets; applications can capture more value than raw tokens.", thesisZh: "身份、Office、开发工具与 Azure 将 AI 引入既有预算；应用可比裸算力获取更多价值。", failure: "Capex remains above 30% of sales; AI seats do not improve renewal, pricing or cloud cash conversion.", failureZh: "资本开支长期超过收入三成，AI 席位未改善续订、定价或云现金转化。", source: "msft" },
  { ticker: "GOOGL", name: "Alphabet", layer: "Consumer distribution + cloud + custom compute", layerZh: "消费分发、云与自研算力", price: 343.50, equityValue: 4201.005, revenue: 480, baseline: "2026 research estimate / 研究估计", growth: [.12,.08,.045], margin: [.34,.32], da: [.065,.15], capex: [.35,.22], tax: .18, workingCapital: .02, interest: 2, preferred: 1.203125, terminalMultiple: 22, durability: 8, risk: 5, thesis: "Search, YouTube and TPUs combine distribution and cost control; Cloud monetization broadens the business.", thesisZh: "搜索、YouTube 与 TPU 结合分发和成本控制，云变现拓宽业务。", failure: "AI interfaces displace profitable search clicks while compute and traffic costs rise; preferred conversions dilute common holders.", failureZh: "AI 界面替代高利润搜索点击，算力和流量成本上升；优先股转换稀释普通股。", source: "goog" },
  { ticker: "AMZN", name: "Amazon", layer: "Cloud + commerce applications", layerZh: "云与商业应用", price: 251.52, equityValue: 2742.32256, revenue: 815, baseline: "2026 research estimate / 研究估计", growth: [.115,.085,.05], margin: [.14,.19], da: [.10,.12], capex: [.25,.16], tax: .21, workingCapital: .01, interest: 3, preferred: 0, terminalMultiple: 23, durability: 8, risk: 4, thesis: "AWS, custom silicon, logistics and advertising provide several monetization paths rather than one model bet.", thesisZh: "AWS、自研芯片、物流与广告提供多条变现路径，不依赖单一模型。", failure: "Compute utilization or cloud pricing disappoints; retail margins cannot offset recurring infrastructure renewal.", failureZh: "算力利用率或云定价不及预期，零售利润不足以弥补基础设施更新。", source: "amzn" },
  { ticker: "META", name: "Meta Platforms", layer: "AI-enhanced advertising", layerZh: "AI 增强广告", price: 728.08, equityValue: 1868.25328, revenue: 245, baseline: "2026 research estimate / 研究估计", growth: [.12,.075,.04], margin: [.35,.40], da: [.09,.19], capex: [.55,.30], tax: .18, workingCapital: .01, interest: 2, preferred: 0, terminalMultiple: 20, durability: 7, risk: 6, thesis: "Better recommendation, conversion and creative tooling can monetize AI without selling a separate subscription.", thesisZh: "推荐、转化与创意工具改善可直接变现，不必另售 AI 订阅。", failure: "Infrastructure and experimental projects permanently outrun incremental advertising cash profit; regulation weakens targeting.", failureZh: "基础设施与实验项目支出长期超过新增广告现金利润，监管削弱定向能力。", source: "meta" },
  { ticker: "NVDA", name: "NVIDIA", layer: "Accelerated compute + software stack", layerZh: "加速计算与软件栈", price: 233.95, equityValue: 5681.47575, revenue: 390, baseline: "FY2027 research estimate / 研究估计", growth: [.18,.10,.045], margin: [.66,.44], da: [.012,.018], capex: [.022,.025], tax: .17, workingCapital: .13, interest: 1, preferred: 0, terminalMultiple: 22, durability: 8, risk: 7, thesis: "Integrated networking, libraries and system-level performance defend economics beyond individual chip specifications.", thesisZh: "网络、软件库与系统性能的整合使竞争力不止于单颗芯片。", failure: "Customer ASICs, export limits or a spending pause compress margins faster than unit demand expands.", failureZh: "客户自研芯片、出口限制或投资暂停，使利润率下降快于需求增长。", source: "nvda" },
  { ticker: "AVGO", name: "Broadcom", layer: "Custom accelerators + connectivity", layerZh: "定制加速器与连接", price: 355.14, equityValue: 1695.30691, revenue: 105, baseline: "FY2026 research estimate / 研究估计", growth: [.22,.115,.05], margin: [.54,.43], da: [.05,.035], capex: [.018,.02], tax: .19, workingCapital: .08, interest: 3, preferred: 0, terminalMultiple: 21, durability: 7, risk: 7, thesis: "Custom compute and high-speed connectivity can benefit as hyperscalers optimize mature workloads; software supports cash generation.", thesisZh: "云厂商优化成熟负载有利于定制计算和高速连接，软件支撑现金生成。", failure: "A few design wins dominate revenue; customers internalize IP or concentration creates pricing pressure.", failureZh: "少数设计订单主导收入，客户内化知识产权或集中度压低价格。", source: "avgo" },
  { ticker: "TSM", name: "TSMC", layer: "Leading-edge foundry + packaging", layerZh: "先进代工与封装", price: 472.78, equityValue: 25.932 / 5 * 472.78, revenue: 165, baseline: "2026 USD research estimate / 美元研究估计", growth: [.17,.10,.05], margin: [.59,.45], da: [.17,.17], capex: [.30,.27], tax: .18, workingCapital: .06, interest: 1, preferred: 0, terminalMultiple: 20, durability: 9, risk: 9, thesis: "Manufactures for competing chip architectures; process, yield and packaging are difficult to replicate together.", thesisZh: "为竞争芯片架构共同制造，制程、良率与封装难以一并复制。", failure: "Taiwan disruption, export controls, overseas fab dilution or customer bargaining power impair common-equity cash flows.", failureZh: "台湾地区中断、出口管制、海外工厂稀释利润或客户议价损害普通股现金流。", source: "tsm" },
  { ticker: "ASML", name: "ASML", layer: "Lithography equipment + service", layerZh: "光刻设备与服务", price: 1867.31, equityValue: 734.6403138, revenue: 44 * 1.17, baseline: "EUR44B guide midpoint x assumed FX / 指引中值与假设汇率", growth: [.13,.09,.045], margin: [.36,.35], da: [.025,.03], capex: [.05,.045], tax: .18, workingCapital: .10, interest: .2, preferred: 0, terminalMultiple: 25, durability: 10, risk: 6, thesis: "EUV lithography and installed-base service underpin a durable bottleneck that is less tied to the winning AI chip designer.", thesisZh: "EUV 与装机服务形成持久瓶颈，较少依赖某家 AI 芯片设计商获胜。", failure: "High-NA adoption slips, customer capex pauses or export restrictions narrow the accessible market; a premium entry price magnifies losses.", failureZh: "High-NA 推广延迟、客户投资暂停或出口限制缩小市场；高买入价放大损失。", source: "asml" },
  { ticker: "ANET", name: "Arista Networks", layer: "Ethernet networking + operating software", layerZh: "以太网与网络软件", price: 207.35, equityValue: 264.5786, revenue: 12.5, baseline: "2026 research estimate / 研究估计", growth: [.18,.10,.05], margin: [.45,.37], da: [.012,.015], capex: [.025,.025], tax: .20, workingCapital: .12, interest: 0, preferred: 0, terminalMultiple: 23, durability: 7, risk: 6, thesis: "AI clusters need reliable high-bandwidth fabrics; software operations and integration support premium networking economics.", thesisZh: "AI 集群需要可靠高带宽网络，软件运维与整合支撑网络设备溢价。", failure: "Hyperscaler concentration, bundled alternatives or optical redesigns compress the economics; valuation leaves little room for delays.", failureZh: "云客户集中、捆绑方案或光网络重构压缩经济性；估值缺乏容错空间。", source: "anet" },
  { ticker: "ETN", name: "Eaton", layer: "Electrical equipment + power management", layerZh: "电气设备与电力管理", price: 436.11, equityValue: 169.864845, revenue: 33, baseline: "2026 research estimate / 研究估计", growth: [.10,.07,.04], margin: [.20,.22], da: [.035,.035], capex: [.045,.04], tax: .20, workingCapital: .12, interest: .8, preferred: 0, terminalMultiple: 22, durability: 8, risk: 5, thesis: "Switchgear, protection and power management benefit from electrification beyond AI, with long qualification and replacement cycles.", thesisZh: "开关设备、保护与电力管理受益于更广泛电气化，认证和替换周期较长。", failure: "Backlogs normalize, acquisitions disappoint or a separation changes earnings; stock returns may lag strong equipment demand.", failureZh: "积压订单回归常态、并购失利或分拆改变盈利；强需求不一定带来强股价回报。", source: "etn" },
];

export const MARKET_DATE = "2026-10-02";
export const RESEARCH_DATE = "2026-10-04";
