import type { SourceId } from "./sources";

export type Chapter = { id: string; title: string; titleZh: string; paragraphs: string[]; paragraphsZh: string[]; sources: SourceId[] };
export const REPORT: Chapter[] = [
  { id: "conclusion", title: "1. Investment conclusion: own the scarce complement, not just the popular technology", titleZh: "1. 投资结论：拥有稀缺互补品，而不只是热门技术", sources: ["iea26", "stanford"], paragraphs: [
    "The AI product chain is a connected economic system: electricity and manufacturing enable computing; computing enables models; models enable workflow tools; distribution turns those tools into customer outcomes. Its investment opportunity is not one homogeneous market. Profit can migrate between layers even while aggregate use increases. The central question is which business keeps a meaningful share of customer value after paying for computing, talent, reinvestment and competition.",
    "Our strongest ten-year business-economics thesis is the combination of qualified electrical equipment, advanced manufacturing bottlenecks and software-rich compute systems. They sell scarce complements during a physical expansion whose construction cannot happen at software speed. Our strongest twenty-year thesis is distribution-owned workflow automation: businesses already inside customer identity, data, transactions and decision processes can turn improving models into recurring cash flow. These are business-quality conclusions, not assertions that every associated stock is inexpensive.",
    "For a public shareholder, entry valuation can overturn the industry ranking. A highly profitable lithography supplier bought at an extreme cash-flow multiple can deliver a lower return than a less celebrated platform bought cheaply. The ten-stock ranking below therefore uses modeled cash returns at the dated market snapshot, normalized reinvestment and a downside case. It is an investable research shortlist, not a guarantee, an exhaustive global optimization or a recommendation to buy all ten immediately.",
    "No credible analysis can identify the single highest-return investment over twenty years with certainty. We distinguish corporate return on invested capital, customer payback and stock return. Our forecasts are conditional illustrations designed to expose what must happen for an investment to work. If the price required for a 12% model return is below the market price, that is a valuation warning, not an instruction to raise the terminal multiple until the stock looks attractive.",
  ], paragraphsZh: [
    "AI 产品链是一个相连的经济系统：电力与制造支撑算力，算力支撑模型，模型支撑工作流工具，分发再将工具转化为客户成果。它不是单一、同质化的市场。即使用量增长，利润仍可能在各层之间转移。关键在于支付算力、人才、再投资与竞争成本后，谁还能保留客户价值。",
    "未来十年，我们对企业经济性最看好的是经过认证的电气设备、先进制造瓶颈，以及具备软件优势的计算系统。这些业务在物理建设过程中出售稀缺互补品，建设速度无法像软件一样加快。未来二十年，更看好掌握分发的工作流自动化：已经嵌入客户身份、数据、交易与决策流程的公司，更可能将不断改善的模型转化为持续现金流。这是业务质量判断，不代表相关股票都便宜。",
    "对股票投资者而言，买入估值可能推翻行业排序。高现金流倍数下买入优秀光刻企业，回报可能低于低价买入普通平台。因此，下面的十股排序基于注明日期的市场价格、正常化再投资与悲观情景。它是可研究的候选名单，不是保证、全球最优解，也不意味着现在应同时买入十家公司。",
    "没有可信分析能确定二十年后回报最高的单一投资。本文区分企业投入资本回报、客户投资回收期和股东收益。预测是有条件的示例，用于揭示投资成立所需的条件。如果满足模型 12% 回报所需的价格低于市价，应视为估值警示，而不是不断提高终值倍数来迎合价格。",
  ] },
  { id: "chain", title: "2. Follow the money through the complete product chain", titleZh: "2. 沿完整产品链追踪现金", sources: ["iea26", "tsm", "avgo", "asml"], paragraphs: [
    "The upstream chain starts with power generation, transmission, substations, transformers, switchgear, backup generation, cooling, water and permitted land. Semiconductor inputs add electronic design software, intellectual property, lithography, deposition, etching, metrology, wafers, chemicals, advanced packaging and test. A finished AI system combines accelerators, CPUs, high-bandwidth memory, ordinary DRAM, storage, optical interconnects, switches and management software. Every important bottleneck is a possible profit pool, but none has an unlimited market.",
    "Above hardware sit cloud infrastructure and orchestration, foundation-model training, inference serving, evaluation, security, observability, data governance and enterprise integration. Applications include coding, search, advertising, customer support, document processing, design, healthcare administration and industrial optimization. Physical AI extends the chain into sensors, actuators, robots, autonomous systems and maintenance. Finance and insurance sit across all layers: they fund construction, cover liabilities and absorb utilization or technology risk.",
    "Do not add revenues across these layers and call the result an AI total addressable market. A cloud operator's purchase becomes a chip designer's revenue, part of which becomes a foundry's revenue, part of which funds equipment purchases. The same end-customer dollar appears repeatedly. Conversely, substantial AI value may appear as an existing advertiser's improved conversion rather than a separately disclosed AI revenue line. Our sector comparison consequently uses economics and operating measures, not a fabricated summed market size.",
    "A useful investment map classifies the constraint, buyer, payment mechanism, replacement cycle and substitute at each layer. An accelerator is not interchangeable with an installed switchboard: its technological life is shorter and its value is more sensitive to software performance. A workflow product is not interchangeable with a model API: it may own the customer relationship, consented data and regulatory accountability. Those differences explain why one growth rate or one valuation multiple cannot describe the entire chain.",
  ], paragraphsZh: [
    "上游从发电、输电、变电站、变压器、开关设备、备用电源、冷却、水和获批土地开始。半导体链还包括 EDA、知识产权、光刻、沉积、刻蚀、量测、晶圆、化学品、先进封装和测试。完整 AI 系统结合加速器、CPU、高带宽存储、普通 DRAM、存储设备、光互连、交换机和管理软件。瓶颈可能形成利润池，但市场并非无限。",
    "硬件之上是云与编排、基础模型训练、推理服务、评估、安全、可观测性、数据治理和企业整合。应用包括编程、搜索、广告、客服、文档处理、设计、医疗行政和工业优化。物理 AI 则延伸至传感器、执行器、机器人、自主系统和维护。融资与保险贯穿各层，承担建设、责任、利用率和技术风险。",
    "不能将这些层的收入相加并称为 AI 总市场。云厂商的采购是芯片公司的收入，部分又成为代工收入，再转成设备订单。同一终端客户的一美元会被重复计算。反过来，AI 价值可能表现为广告转化改善，而非独立披露的 AI 收入。因此本文比较经济性和运营指标，不编造相加后的市场规模。",
    "有效的投资地图需要逐层列出限制因素、买方、支付机制、更新周期和替代方案。加速器与已安装的配电设备不同，技术寿命更短，对软件性能更敏感。工作流产品与模型 API 也不同，前者可能拥有客户关系、授权数据和监管责任。这些差异意味着不能用同一个增速或估值倍数描述全链。",
  ] },
  { id: "evidence", title: "3. The evidence supports adoption, not automatic profitability", titleZh: "3. 证据支持采用增长，不支持利润必然增长", sources: ["stanford", "nber", "metr", "robots"], paragraphs: [
    "Stanford's 2026 AI Index reports organizational adoption of 88% and emphasizes a jagged capability frontier. Adoption answers whether people use a tool; it does not answer how often they pay, whether it replaces another expense or whether the provider earns an economic profit. Strong benchmark performance is an input to a business case, not a substitute for measuring actual task reliability, completion time and required supervision.",
    "The customer-support field research summarized by NBER found meaningful average productivity improvements, especially for less experienced workers. METR's early-2025 experiment found experienced open-source developers took 19% longer with AI tools. Its February 2026 update explained why changing tools and participant selection complicated follow-up estimates. These are different tasks and populations; neither proves that AI is universally productive or universally unproductive. We use the contrast to require task-specific measurement instead of extrapolating one headline to the economy.",
    "A deployment should be judged on completed, accepted work. Start with a controlled baseline, record human review and error remediation, and include integration, training, security and model costs. A twenty-percent improvement in drafting speed can coexist with no saving if approval takes longer or demand is fixed. An apparent productivity gain can also become higher output rather than lower payroll. For investors, what matters is the portion of this value a supplier can charge for without destroying the customer's incentive to use it.",
    "IFR's September 2026 release places the operating industrial robot stock at roughly five million units in 2025. That demonstrates a substantial existing automation base, not proof that general-purpose humanoid robots already have attractive economics. Physical deployments need durable uptime, safe interaction, spare parts and acceptable liability. We treat general robotics and AI-driven drug discovery as valuable twenty-year options, but do not insert speculative breakthrough revenue into the base valuation of an unrelated listed company.",
  ], paragraphsZh: [
    "斯坦福 2026 AI Index 报告称组织采用率达到 88%，并强调能力边界并不均衡。采用率说明有人使用，不说明付费频率、是否替代原有支出或供应商是否赚取经济利润。优秀基准表现只是商业论证的输入，不能代替真实任务可靠性、完成时间和监督成本。",
    "NBER 总结的客服研究发现平均生产率明显改善，经验较少的员工受益更大。METR 的早期 2025 实验则发现，经验丰富的开源开发者使用 AI 后耗时增加 19%；2026 年 2 月更新解释了工具变化和参与者选择如何影响后续估计。任务和人群不同，两者都不能证明 AI 普遍有效或无效。本文因此要求逐任务衡量，而非将单个标题外推至整个经济。",
    "部署应以被接受的完成工作衡量。先设对照基线，记录人工审查和错误修复，并计入整合、培训、安全和模型成本。草稿速度快两成，不等于实际节省，审批可能更慢或需求固定。生产率改善也可能成为产出增加，而非薪资下降。投资者关注的是供应商在不破坏客户使用激励的情况下，能够收取多少价值。",
    "IFR 2026 年 9 月公告指出，2025 年工业机器人在用存量约五百万台。这说明传统自动化基础较大，不意味着通用人形机器人已经经济可行。实体部署需要稳定运行、安全互动、备件与可接受责任。本文将通用机器人和 AI 药物发现视为二十年的可选机会，但不将猜测的突破收入填入无关上市公司的基准估值。",
  ] },
  { id: "energy", title: "4. Power, grid and cooling: the scarce connection matters more than electricity volume", titleZh: "4. 电力、电网与冷却：接入稀缺性比总电量更重要", sources: ["iea26", "iea25", "lbl", "etn", "vrt"], paragraphs: [
    "The IEA's April 2026 central outlook moves global data-centre electricity consumption from 485 TWh in 2025 to around 950 TWh in 2030, roughly 3% of global consumption at that date. It is a forecast and includes non-AI data centres. The implication is substantial local construction pressure, not unlimited demand for every energy stock. Transmission access, reliability, permitting and time-to-power can be more valuable than undifferentiated generation capacity.",
    "Electrical equipment and thermal management are attractive complements because they solve a real constraint and can serve markets beyond AI. Qualification, maintenance networks and installed equipment create switching friction. Nevertheless, rising order books can invite capacity additions, customer double ordering and eventual margin normalization. Compare backlog conversion, cancellation terms, cash advances, factory utilization and warranty claims rather than treating every reservation as guaranteed revenue.",
    "Generation investments need contract-by-contract underwriting. A long-term power purchase agreement is valuable only if the price, escalator, collateral, delivery obligations and customer credit compensate for capital and fuel risk. Merchant power prices may rise during shortages and fall after new capacity arrives. Nuclear projects add licensing, construction duration and cost-overrun risk. Gas facilities add fuel and emissions exposure. Storage improves dispatch flexibility but is not itself a source of net energy.",
    "Cooling demand should be measured by delivered heat-removal capacity, service revenue and customer architecture, not simply rack count. Higher density may favor liquid systems, but equipment standards and design choices can change. Eaton and Vertiv represent different exposures: diversified power management versus more concentrated data-centre infrastructure. We prefer qualified, cash-generative suppliers as business models, while acknowledging that a high stock valuation can already discount years of successful expansion.",
  ], paragraphsZh: [
    "IEA 2026 年 4 月基准展望将全球数据中心用电从 2025 年 485 TWh 预测到 2030 年约 950 TWh，届时约占全球电量 3%。这是一项预测，且包含非 AI 数据中心。含义是局部建设压力较大，而不是所有能源股都有无限需求。输电接入、可靠性、许可和通电时间，可能比普通发电容量更有价值。",
    "电气与热管理设备解决真实限制，也能服务 AI 之外的市场，因此具备吸引力。认证、维修网络和已安装设备形成转换摩擦。但订单增长也可能引发扩产、重复下单和利润率正常化。应比较积压订单转化、取消条款、预付款、工厂利用率和保修成本，不能将所有预订视为确定收入。",
    "发电投资需要逐份合同分析。长期购电协议只有在价格、递增条款、抵押、交付责任和客户信用足以补偿资本及燃料风险时才有价值。现货电价可能在短缺时上涨，新增产能后下跌。核电有许可、建设周期和超支风险；燃气有燃料及排放风险；储能提高调度灵活性，但不是净能源来源。",
    "冷却需求应以交付的散热能力、服务收入和客户架构衡量，而不只看机柜数量。高密度可能利好液冷，但标准和设计会变化。Eaton 偏多元电力管理，Vertiv 更集中于数据中心基础设施。本文偏好认证充分、现金生成良好的业务，同时承认高股价可能已经反映多年成功扩张。",
  ] },
  { id: "silicon", title: "5. Chips, memory, foundry, packaging and equipment: separate bottlenecks from cycles", titleZh: "5. 芯片、存储、代工、封装与设备：区分瓶颈和周期", sources: ["nvda", "avgo", "tsm", "asml", "mu"], paragraphs: [
    "Accelerator economics depend on system-level usefulness: how much accepted output a cluster produces per dollar and per watt. Software compatibility, developer familiarity, networking, utilization and support can sustain an advantage beyond raw arithmetic throughput. NVIDIA therefore has an integrated-system thesis rather than merely a GPU-volume thesis. But large customers have a strong incentive to optimize their own workloads, making custom accelerators and inference specialization a real competitive constraint.",
    "Broadcom's opportunity is to participate in that optimization through custom silicon and connectivity. The attractive model is capital-light design combined with scarce expertise; the risk is concentration in a few customers and design programs. Foundry economics are different. TSMC must continually invest in process transitions, yield learning and packaging. It can serve multiple competing designers, yet it bears significant physical capital requirements, geographic concentration and the lower initial productivity of new fabs.",
    "ASML's lithography position is a hard-to-replicate manufacturing complement. Installed-base service can soften, but not eliminate, equipment cycles. A dominant position does not mean customers can indefinitely accelerate investment or accept any price. Analyze customer concentration, shipment acceptance, service attachment and process adoption rather than projecting an order spike forever. A normalized margin and explicit maintenance investment are essential even for a near-monopoly.",
    "Memory is a particularly important warning against extrapolation. Micron's September 30 release reports FY2026 revenue of $133.188B and a very strong earnings and cash-flow year, much newer than its available companyfacts quarter. Those reported results should be recognized, not silently replaced with older data. They also should not become a permanent twenty-year margin assumption. HBM qualification can improve differentiation while ordinary memory still responds to bit supply, inventory and capacity additions. We leave MU outside this ten-stock long-duration model because a reliable cycle-specific cash model deserves separate treatment, not because memory is unimportant.",
  ], paragraphsZh: [
    "加速器的经济性取决于系统效用，即每美元、每瓦能产生多少合格产出。软件兼容、开发者习惯、网络、利用率和支持服务可以形成超越算术吞吐的优势。因此英伟达的投资逻辑是整合系统，而不只是 GPU 数量。但大客户有动力优化自有负载，定制加速器和专用推理构成真实竞争约束。",
    "博通通过定制芯片和连接参与这种优化。资本较轻的设计与稀缺专业知识具有吸引力，风险则在于少数客户和设计项目。代工不同：台积电需持续投入制程、良率和封装，能服务多种竞争架构，但承担实物资本、地域集中和新工厂初期效率不足。",
    "ASML 的光刻地位难以复制。装机服务可缓冲、但无法消除设备周期。优势地位不代表客户能无限加速投资或接受任意价格。应分析客户集中度、验收、服务附着和工艺采用，而不是永久外推订单高峰。即使近乎垄断，也必须使用正常化利润率和明确维护投资。",
    "存储尤其提醒我们不能外推高峰。美光 9 月 30 日公告披露 2026 财年收入 1,331.88 亿美元，盈利与现金流强劲，时间比 companyfacts 可用季度更新。应承认最新披露，而非悄悄用旧数据替代；同时不能将高峰利润率设为二十年常态。HBM 认证加强差异化，但普通存储仍受比特供给、库存和扩产影响。MU 未进入本次十股长期模型，是因为需要独立跨周期现金流分析，不是因为存储不重要。",
  ] },
  { id: "network", title: "6. Networking, optics and storage: optimize useful throughput", titleZh: "6. 网络、光互连与存储：优化有效吞吐", sources: ["anet", "nvda", "avgo"], paragraphs: [
    "A cluster with powerful accelerators but a congested network wastes expensive capacity. Networking can therefore participate in AI growth without owning the winning foundation model. The relevant measures are job completion time, fabric reliability, congestion control, bandwidth per accelerator and total cost of ownership. Nominal port speed is not sufficient if optics, cabling, software or failure recovery become the limiting factor.",
    "Arista's software-rich Ethernet proposition benefits when customers value a manageable open fabric across different compute architectures. It is not immune to alternatives: integrated accelerator platforms, customer-designed switching, changes in optical interconnect and aggressive bundling can alter its share of system spending. A large AI fabric order also does not automatically imply high recurring revenue; investors should track service attachment and the proportion of growth supplied by a few hyperscalers.",
    "Optics and storage contain both differentiated intellectual property and commoditized manufacturing. Count qualification cycles, yield, component redundancy, inventory commitments and customer bargaining power. Faster traffic can increase bandwidth demand while integration moves value into fewer packages. For storage, retrieval and memory efficiency can reduce cost per task even as total data expands. Growth in bits or ports is not identical to growth in gross profit.",
    "Our base thesis favors integrated operations software and qualified components over unqualified capacity announcements. We nevertheless give Arista a material valuation and concentration penalty in the score. Its strong current operating margin is evidence of a good business; it is not evidence that paying any multiple will produce a good twenty-year stock return.",
  ], paragraphsZh: [
    "强加速器配上拥堵网络，会浪费昂贵产能。因此网络可以受益于 AI，而不必押注某个基础模型。应看任务完成时间、网络可靠性、拥塞控制、每加速器带宽和总拥有成本。如果光模块、线缆、软件或恢复机制成为限制，标称端口速度并不足够。",
    "当客户重视跨计算架构、可管理的开放网络时，Arista 的软件化以太网具有优势。但整合加速器平台、自研交换、光互连变化和激进捆绑仍会改变其价值份额。大型 AI 网络订单不自动意味着高经常收入，应关注服务附着和少数云客户贡献的增长比例。",
    "光学和存储同时包含差异化知识产权和商品化制造。应研究认证周期、良率、冗余、库存承诺与客户议价。流量加快可能增加带宽需求，也可能让价值集中到更少封装。检索和存储效率可降低单任务成本，即使数据总量上涨。比特或端口增长不等于毛利润增长。",
    "基准逻辑偏向运营软件整合和经过认证的零部件，而非未经验证的扩产公告。评分仍对 Arista 的估值与集中度给予明显扣分。当前高营业利润率证明业务质量，不证明任意买入倍数都有良好二十年股东回报。",
  ] },
  { id: "cloud", title: "7. Cloud and foundation models: capital intensity is the central underwriting issue", titleZh: "7. 云与基础模型：资本强度是核心承保问题", sources: ["msft", "goog", "amzn", "meta"], paragraphs: [
    "Cloud platforms connect infrastructure spending with paying users, enterprise budgets and software deployment. Their advantage is distribution, integration, identity, data management and the ability to optimize several workloads. Their risk is that compute becomes a fiercely competitive commodity while the balance sheet absorbs buildings, chips and contractual commitments. Revenue growth must be tested against cash return on the capital installed to produce it.",
    "Microsoft's FY2026 cash flow illustrates the tension: $182.935B of operating cash flow and $115.948B of cash PP&E investment, before adjusting for compensation and financing obligations. Alphabet's first-half 2026 CFO of $84.859B was close to its $80.598B PP&E expenditure. Meta's 2026 capex guidance of $130-145B includes lease principal. These are different fiscal periods and definitions; they should not be added into an apparently precise comparable total without reconciliation.",
    "Foundation-model revenue can grow quickly while research and inference costs also rise. Competition from open models, falling prices, distillation and customer-owned infrastructure can transfer value from the model producer to the application or end customer. Proprietary models may retain an advantage in difficult tasks, evaluation, safety and enterprise support, but that advantage needs repeated investment. We do not assume that the frontier model layer will automatically have the highest sustainable margin.",
    "The model's cloud capex declines as a share of revenue only gradually and still exceeds depreciation at maturity. That is a consequential assumption, not a discovered fact. If expanding usage continually requires equally intensive chip replacement, free-cash-flow recovery will be weaker than our base case. Useful leading indicators are net incremental cloud revenue per dollar of cumulative capex, availability versus paid utilization, backlog conversion and depreciation growth relative to revenue.",
  ], paragraphsZh: [
    "云平台把基础设施投入连接到付费用户、企业预算和软件部署。优势在于分发、整合、身份、数据管理，以及多负载优化。风险是算力变成竞争激烈的商品，而资产负债表承担建筑、芯片与合同承诺。收入增长必须与为此安装资本的现金回报相比较。",
    "微软 2026 财年经营现金流 1,829.35 亿美元，现金固定资产投入 1,159.48 亿美元，尚未调整薪酬和融资义务。Alphabet 2026 上半年 CFO 为 848.59 亿美元，接近 805.98 亿美元固定资产支出。Meta 全年资本支出指引 1,300 至 1,450 亿美元包含融资租赁本金。这些期间和定义不同，不能直接相加为看似精确的可比总量。",
    "基础模型收入可能快速增加，研究与推理成本也可能同步上涨。开放模型、价格下降、蒸馏和客户自有设施，会将价值从模型商转移给应用或终端客户。私有模型可能在复杂任务、评估、安全和企业支持保有优势，但必须持续投入。本文不假设前沿模型层必然拥有最高可持续利润率。",
    "模型只逐步降低云资本开支占比，成熟阶段仍高于折旧。这是重要假设，不是已知事实。如果用量增长始终要求同样高强度芯片更新，现金流修复将弱于基准。领先指标包括每累计资本投入对应的新增云收入、可用容量与付费利用率、订单兑现，以及折旧相对收入的增长。",
  ] },
  { id: "applications", title: "8. Workflow software, data, security and advertising: the twenty-year compounding candidate", titleZh: "8. 工作流、数据、安全与广告：二十年复利候选", sources: ["msft", "goog", "meta", "stanford"], paragraphs: [
    "Applications can capture the value between cheap intelligence and an expensive business problem. A model may be replaceable while a product embedded in permissions, audit trails, customer history and business processes is harder to remove. This is the most attractive long-duration opportunity in our framework, provided the vendor genuinely improves an outcome and does not simply repackage a model behind an interface.",
    "There are two competing revenue effects. AI can improve a product enough to support higher pricing and broader adoption; it can also automate tasks previously sold as individual software seats. A seat-priced vendor may lose revenue as customers need fewer workers, even while customers become more productive. Outcome pricing, transaction pricing and consumption pricing may defend revenue, but they require accurate measurement and can shift delivery risk onto the vendor.",
    "Data and security matter because enterprise automation must respect access controls, trace decisions and prevent unauthorized actions. Retrieval quality, data freshness, evaluation coverage and incident response can be more commercially important than adding another model option. But 'proprietary data' is not inherently a moat: a company must have lawful usage rights, differentiated information and a workflow in which that information changes decisions. Compliance expense belongs in the margin forecast, not just the risk section.",
    "Advertising offers a different route: Meta and Alphabet can monetize better ranking and conversion inside an existing marketplace without convincing every user to buy an AI subscription. The investment test is incremental advertiser value after extra compute, content integrity and privacy expense. Longer-term success requires maintaining distribution and trust. We favor measurable business outcomes over generic claims about agents replacing entire professions.",
  ], paragraphsZh: [
    "应用可以获取廉价智能与昂贵商业问题之间的价值。模型可替换，但嵌入权限、审计、客户历史和业务流程的产品更难移除。这是本文最有吸引力的长期方向，前提是供应商真正改善结果，而非给模型套一个界面。",
    "收入有两种相反效应：AI 改善产品可支持提价和更广采用，也可能自动化原来按席位销售的任务。即使客户效率改善，员工减少仍可能降低席位收入。结果、交易或用量计价可保护收入，但要求准确衡量，也可能将交付风险转给供应商。",
    "企业自动化必须遵守访问控制、追踪决策并防止未经授权行动，所以数据和安全重要。检索质量、更新程度、评估覆盖和事件响应，可能比多接一个模型更具商业价值。但私有数据不天然构成护城河，必须具备合法权限、差异化信息和能改变决策的场景。合规成本应进入利润率，而不只出现在风险章节。",
    "广告提供另一条路径：Meta 和 Alphabet 可以在既有市场中，通过更好排序与转化变现，不必让每个用户购买 AI 订阅。投资检验是新增广告价值减去算力、内容治理和隐私成本。长期仍需维持分发与信任。本文偏好可衡量成果，而非代理将替代整个职业的泛化叙述。",
  ] },
  { id: "physical", title: "9. Physical AI, healthcare and scientific discovery: valuable optionality, slower cash conversion", titleZh: "9. 物理 AI、医疗与科学发现：有价值但兑现较慢的选择权", sources: ["robots", "stanford"], paragraphs: [
    "Robotics can address labor scarcity, dangerous work and repetitive physical tasks. The relevant market is not a count of all human labor hours multiplied by a robot wage. Tasks differ in physical variability, required dexterity, failure consequences and integration cost. An automated warehouse station with a defined environment can have a far clearer payback than a general robot expected to work safely anywhere.",
    "Underwrite an installation using accepted units per hour, uptime, interventions, maintenance, energy, insurance, installation and replacement. A demonstration of a successful task is not evidence of fleet reliability. Customer financing, lease guarantees and service obligations can make a hardware company look recurring while leaving it exposed to asset residual values. Public-company exposure may be diluted by legacy businesses or priced as if broad adoption were already certain.",
    "Healthcare administration, imaging support and scientific tools may reach cash-generative workflows sooner than fully autonomous diagnosis or de novo drug discovery. Drug economics still depend on experimental validation, clinical trials, manufacturing and reimbursement. An AI discovery platform can improve search efficiency without removing biological failure risk. Forecast probability-adjusted milestone receipts separately from hypothetical blockbuster sales.",
    "Over twenty years these fields could create exceptionally large winners. They also present wide outcome dispersion and often require expertise beyond a general public-equity model. We keep them in the industry map and monitoring plan rather than choosing a speculative stock solely to make the ranking appear comprehensive. A large addressable problem is not the same as an investable company with a defensible share of future profits.",
  ], paragraphsZh: [
    "机器人可应对劳动力不足、危险工作与重复劳动，但市场不能用全部人类工时乘以机器人时薪来估计。任务的环境变化、灵巧性、失败后果和整合成本不同。环境明确的仓库工位，其回收期可能远清晰于需要在任意场景安全工作的通用机器人。",
    "部署要分析每小时合格产出、运行率、人工介入、维修、能源、保险、安装和替换。演示成功不等于规模化可靠性。客户融资、租赁保证和服务义务，可能让硬件看起来收入经常化，却留下残值风险。上市公司相关敞口也可能被旧业务稀释，或已按普及确定发生定价。",
    "医疗行政、影像辅助和科学工具，可能比全自主诊断或全新药物发现更早进入现金流工作流。药物仍需实验、临床、制造与支付验证。AI 改善搜索效率，不消除生物学失败。概率调整的里程碑收入应与假想重磅药品销售分开预测。",
    "二十年内这些领域可能产生巨大赢家，但结果分布很宽，需要专门知识。本文将其纳入行业地图和监测计划，不为了名单完整而选择投机股票。问题规模巨大，不等于某个可投资企业能稳固获取未来利润。",
  ] },
  { id: "roi", title: "10. Where the highest ROI is most plausible", titleZh: "10. 哪些领域更可能取得高回报", sources: ["iea26", "etn", "asml", "msft"], paragraphs: [
    "For incremental corporate capital, asset-light workflow ownership and differentiated design software can be more attractive than owning fleets of rapidly depreciating compute. Their marginal delivery cost can fall as models improve, while existing customer relationships reduce acquisition costs. However, research spending and stock compensation are real capital costs, and competition can pass efficiency gains to the customer. High accounting ROIC may also reflect expensed investment rather than a truly small economic capital base.",
    "For the next ten years, qualified power equipment and thermal systems have a comparatively visible physical demand driver; foundry, packaging, lithography and integrated compute have powerful bottleneck positions but higher cycle or concentration risk. We regard raw GPU rental, generic model reselling and undifferentiated hosting as less attractive unless secured by strong utilization, financing and customer contracts. The best private-project ROI could still occur in a niche unavailable through a listed stock.",
    "For the next twenty years, we prefer customer-owned workflows, identity, transactions and trusted data to a static bet on today's model leaderboard. This does not require the same model vendor to win forever. The owner's product can swap models and benefit from falling unit costs. The opposing risk is that an incumbent's old pricing or distribution becomes obsolete. Long duration should never mean ignoring technological substitution.",
    "The sector table below contains our qualitative research assessments, not measured sector-wide return forecasts. It purposely avoids invented precise ROIC ranges. Our numerical stock returns instead come from explicit company-level assumptions and dated equity values. This separation matters: a sector with the highest business return can still have the lowest shareholder return if the price already assumes perfection.",
  ], paragraphsZh: [
    "从企业新增投入资本看，轻资产工作流和差异化设计软件，可能比拥有快速折旧的算力更有吸引力。模型改善可降低边际交付成本，既有客户关系可减少获客费用。但研发和股权薪酬是真实成本，竞争也可能把效率收益转给客户。高账面 ROIC 还可能反映投资费用化，而非经济资本很小。",
    "未来十年，认证电气与热管理设备的物理需求较清晰；代工、封装、光刻和整合计算拥有强瓶颈，但周期或集中风险更高。裸 GPU 租赁、普通模型转售和同质托管较弱，除非有高利用率、合理融资和优质合同。最高私人项目回报也可能出现在无法通过上市股票参与的细分领域。",
    "未来二十年，偏好掌握客户工作流、身份、交易和可信数据，而非静态押注今天的模型榜单。这不要求同一模型供应商永远获胜，产品可替换模型并受益于单位成本下降。反面风险是旧定价或分发被淘汰。长期持有不应意味着忽视技术替代。",
    "下面行业表是定性研究判断，不是实际测量的全行业回报预测，也不编造精确 ROIC 区间。股票数值回报由公司假设与注明日期的市值计算。区分很重要：企业回报最高的行业，如果价格已反映完美结果，股东回报仍可能最低。",
  ] },
  { id: "unit", title: "11. A 100 MW AI data-centre example: renewal, not electricity, can dominate cost", titleZh: "11. 100 MW 数据中心示例：更新成本可能超过电费", sources: ["iea26"], paragraphs: [
    "Our project example is deliberately an analyst illustration, not a quoted market price or a forecast of any company's facility. It assumes 100 MW of IT load, PUE 1.2, $5B of installed capital, $3.5B of compute replaced every four years and $1.5B of facility capital replaced over twenty years. Power is conservatively charged at full-load consumption for the whole year at $70/MWh, regardless of billable utilization. Other annual operating cost is $200M.",
    "With these assumptions electricity costs about $73.6M a year, while steady-state replacement costs $950M a year. At a hypothetical $25,000 of annual revenue per billed kW and 65% billed utilization, revenue is $1.625B. Pre-tax owner cash is approximately $401M after operating expense and replacement; after a simplified 20% tax on that economic cash amount it is about $321M, or 6.4% of initial capital. This is a steady-state cash yield, not a full construction-period IRR or accounting net profit.",
    "To obtain a twelve-percent after-tax cash yield under the same simplified assumptions, billable utilization must be around 79%. At 50% utilization the economics deteriorate sharply. Faster chip replacement, lower rental prices or a higher construction bill weaken results; slower renewal or better software efficiency improve them. We exclude land residual value, debt, ramp-up, price decay and customer defaults, which are all necessary in a real project valuation.",
    "The point is not that all data centres have these economics. It is that the dominant cost can be compute renewal rather than power. A provider reporting strong revenue but spending equally fast to maintain competitive capacity may not generate attractive owner returns. Compare customer willingness to pay per accepted task, not only megawatts or installed accelerators. Power scarcity creates an opportunity for suppliers without proving the renter of expensive compute earns a high return.",
  ], paragraphsZh: [
    "项目示例是分析师假设，不是市场报价或某家公司设施预测。假设 IT 负载 100 MW、PUE 1.2、初始投入 50 亿美元；35 亿美元算力每四年更新，15 亿美元设施按二十年更新。电价 70 美元/MWh，并保守按全年满负载计电费，不随付费利用率下降；其他年运营成本 2 亿美元。",
    "据此年电费约 7,360 万美元，稳定更新成本 9.5 亿美元。假设每付费 kW 年收入 25,000 美元、付费利用率 65%，年收入为 16.25 亿美元。扣运营和更新后的税前股东现金约 4.01 亿美元，再简化按经济现金计 20% 税后约 3.21 亿美元，相当于初始资本的 6.4%。这是稳定现金收益率，不是完整建设期 IRR 或会计净利润。",
    "同样简化假设下，要达到税后 12% 现金收益率，付费利用率约需 79%。50% 时经济性显著恶化。更快芯片更新、更低租价或更高建设费会降低回报；慢更新和软件效率改善则相反。示例不含土地残值、债务、爬坡、价格衰减或客户违约，真实估值必须补充。",
    "重点不是所有数据中心都如此，而是算力更新可能比电费更重要。供应商收入强劲，却需要同速投入维持竞争力，未必创造高股东回报。应比较客户对合格任务的付费意愿，而不只看 MW 或加速器数量。电力短缺能利好供应商，但不证明昂贵算力的租赁运营方回报很高。",
  ] },
  { id: "method", title: "12. Forecast construction, return definitions and limitations", titleZh: "12. 预测构造、回报定义与局限", sources: ["sec", "ads", "goog"], paragraphs: [
    "The comparison model begins with a disclosed annual revenue or explicitly labeled annual research estimate; it does not annualize one exceptional quarter and call it audited history. Years 1-5, 6-10 and 11-20 have separate growth assumptions. Operating margin, depreciation and capital intensity interpolate to a normalized year-ten level and then remain at that level. Forecast years are relative model years because issuers have different fiscal calendars, not precise calendar-year guidance.",
    "Owner cash equals operating income less modeled net interest and tax, plus depreciation, less capital expenditure, incremental working capital and a preferred-holder reserve. Operating margin already includes recurring stock compensation; the model does not add that compensation back. It values common-equity distribution capacity, not enterprise FCFF. Therefore it does not add a net-cash bridge or subtract debt a second time. Existing non-operating investment holdings and acquisitions are excluded, which can materially understate some companies' equity value.",
    "Positive owner cash is assumed distributed annually. A deficit is assumed funded at 8% and deducted, with accumulated financing cost, from maturity proceeds; external funding availability is assumed rather than guaranteed. Terminal value is next year's positive owner cash multiplied by an explicit exit multiple. The bear case cuts growth, margin and terminal franchise retention while raising capex. It is an adverse scenario, not a calibrated probability. It does not capture outright insolvency or a geopolitical shutdown; those can produce much larger losses.",
    "The displayed IRR is a hypothetical distribution-capacity return, not a forecast of actual dividends or share prices. Fixed quote-equivalent shares avoid counting buybacks twice, but omit future issuance and dilution changes. Alphabet's annual $1.203B preferred reserve approximates the current coupon; it is retained throughout the model as a conservative simplification, not a correct conversion schedule. TSM uses five common shares per ADS; ASML uses a fixed 1.17 USD/EUR modeling assumption. Currency changes, preferred conversion, lease renewal and repurchases require issuer-specific work before investing.",
    "A 12% hurdle price discounts the same cash stream at twelve percent; it is not a sell-side target. The ranking score equals 100 times the average of the base ten- and twenty-year IRRs, plus 20 times the bear ten-year IRR, plus 1.5 times subjective durability (0-10), less subjective risk (0-10). There are no estimated probabilities or promises in this formula. The score is designed to be inspectable, not to make a subjective shortlist look statistically objective.",
  ], paragraphsZh: [
    "比较模型从已披露年度收入或明确标注的年度研究估计开始，不把特殊季度简单年化并称为审计历史。第 1 至 5、6 至 10、11 至 20 年分别设增速，利润率、折旧和资本强度插值到第十年正常化水平，之后保持。年份是相对模型年，因为各公司财年不同，并非精确日历年度指引。",
    "股东现金等于营业利润减模型利息和税，加折旧，再减资本支出、新增营运资本和优先股准备。营业利润率已含持续股权薪酬，不再加回。模型估计普通股分配能力，不是企业 FCFF，因此不另加净现金或重复扣债务。未计非经营投资持仓和未来收购，可能明显低估部分公司的权益价值。",
    "正现金假设逐年分配；负现金假设以 8% 融资，累计成本从期末所得扣除，融资可得性是假设而非保证。终值是下一年正现金乘退出倍数。悲观情景降低增长、利润率和终值保留比例，增加资本开支；它是压力情景，不是校准概率，不能覆盖破产或地缘停产，此类损失可能更大。",
    "IRR 是假想分配能力回报，不是实际股息或股价预测。固定报价等效股数避免回购重复计数，但忽略未来发行与稀释变化。Alphabet 每年 12.03 亿美元优先股准备近似当前票息，长期保留属于保守简化，不是真实转换时间表。TSM 每 ADS 对应五股，ASML 假设 1 欧元等于 1.17 美元。投资前仍需专门处理汇率、转换、租赁更新和回购。",
    "12% 门槛价格用相同现金流按 12% 折现，不是券商目标价。评分等于基准十年和二十年 IRR 均值乘 100，加悲观十年 IRR 乘 20，加主观持久性（0 至 10）乘 1.5，再减主观风险（0 至 10）。公式无概率估计或收益承诺，目的在于可检查，而非把主观名单包装为统计客观。",
  ] },
  { id: "ranking", title: "13. Interpret the ten-stock ranking as a watchlist, not a portfolio", titleZh: "13. 十股排序是观察名单，不是投资组合", sources: ["msft", "nvda", "tsmshares", "asml"], paragraphs: [
    "The candidate set intentionally covers distribution, cloud, advertising, integrated compute, custom silicon, foundry, lithography, networking and electrical equipment. It is limited to ten large, liquid listed companies where we can articulate a long-duration economic case. The financial appendix additionally covers Vertiv, Micron, AMD, Constellation and Vistra. Those five are not numerically ranked here; excluding them is a scope choice, not a claim that their returns must be inferior.",
    "Rankings are generated from the model, not manually arranged to follow a popular AI narrative. Each row shows the dated price, base ten-year and twenty-year returns, bear ten-year return and the price consistent with the stated hurdle. A high score can still have an unattractive absolute base return. A lower-ranked stock can become attractive after a price decline or after evidence improves. The dashboard lets readers change a candidate's entry price without pretending the publication-date ranking has changed.",
    "These businesses are economically correlated. A hyperscaler pause can reduce accelerator, networking, foundry, equipment and electrical orders together. Owning one stock from each layer is not automatically diversification. Customer budgets, Taiwan production, interest rates and capital-market sentiment are shared factors. A real portfolio also needs position limits, liquidity planning and exposure to assets outside the AI thesis; this article does not prescribe allocations.",
    "A falsifiable thesis is more useful than a precise-looking distant target. We provide a failure condition for each candidate: sustained capex intensity, weakened software economics, lost custom design wins, customer concentration, manufacturing disruption or backlog normalization. Revisit the ranking when those variables change, rather than defending it because a company remains important to AI. Great technology and disappointing shareholder returns can coexist.",
  ], paragraphsZh: [
    "候选覆盖分发、云、广告、整合计算、定制芯片、代工、光刻、网络和电气设备，限定十家规模较大、流动性较好且可描述长期经济逻辑的上市公司。财务附录另含 Vertiv、美光、AMD、Constellation 和 Vistra，但不对这五家数值排序。排除是范围选择，不代表收益必然较差。",
    "排序由模型生成，不手工迎合流行叙事。每行给出日期价格、基准十年及二十年回报、悲观十年回报和门槛价格。评分高也可能绝对回报不理想；评分低的股票在下跌或证据改善后可能有吸引力。仪表板允许改变单家公司买入价格，不假装已改变出版日固定排序。",
    "这些公司高度相关。云厂商暂停投入可同时降低加速器、网络、代工、设备和电气订单。每层买一家不等于分散，客户预算、台湾制造、利率和资本市场情绪是共同因素。真实组合还需仓位限制、流动性规划和 AI 之外资产；本文不规定配置比例。",
    "可证伪逻辑比看似精确的遥远目标价更有用。每家公司列出失败条件：资本强度持续偏高、软件经济性下降、定制订单丢失、客户集中、制造中断或积压正常化。变量变化时重做排序，而非因为公司仍重要就维护原判断。伟大技术与失望股东收益可以并存。",
  ] },
  { id: "risks", title: "14. What could invalidate the entire thesis", titleZh: "14. 什么可能推翻全局逻辑", sources: ["iea26", "goog", "meta", "metr"], paragraphs: [
    "The first risk is economic demand: users may like AI but resist prices sufficient to cover infrastructure and model renewal. The second is efficiency: cheaper inference can expand usage, yet the demand response may be insufficient to preserve supplier revenue. The third is capital overbuild: project announcements, customer reservations and financed purchases can create the appearance of stronger independent demand than actually exists. The fourth is substitution: value can move from frontier models to open models, from GPUs to specialized chips, or from legacy seats to automated outcomes.",
    "The fifth risk is financing. Leases, preferred shares, customer prepayments and special-purpose structures can move liabilities away from a simple cash-capex headline without eliminating them. Strategic investors that are also major customers can support a supplier while complicating the interpretation of its revenue quality. Demand funded by a partner's financing deserves a different confidence level from an unrelated customer's recurring cash payment. Track commitments, collateral and credit exposure, not just recognized revenue.",
    "The sixth risk is geography and policy: advanced-node production and essential inputs are concentrated; export permissions, tariffs, cyber incidents and military conflict can interrupt supply. The seventh is social permission: power prices, water, land use, privacy and copyright can slow deployments or increase cost. The eighth is valuation duration: a large part of a twenty-year estimate may be terminal value. Small changes in sustained margin or the exit multiple can outweigh several good near-term quarters.",
    "Our downside case is not a worst case. A stock can lose most of its value, and a compounder can cease to be a compounder. The right response is not to label every uncertain variable bullish; it is to price uncertainty, demand a margin of safety and monitor evidence. Longer time horizons increase both the potential for reinvestment and the chance that the competitive landscape changes fundamentally.",
  ], paragraphsZh: [
    "第一是经济需求：用户喜欢 AI，却不愿支付足以覆盖设施与模型更新的价格。第二是效率：推理降价扩大使用，但需求弹性可能不足以维持供应商收入。第三是过度建设：项目公告、容量预订和融资采购，会制造独立需求更强的假象。第四是替代：价值可能从前沿转向开放模型、GPU 转专用芯片、旧席位转自动化成果。",
    "第五是融资：租赁、优先股、预付款和特殊结构，可让义务不出现在简单现金资本开支标题中，但并未消失。既是战略投资者又是大客户的合作方，可能支持供应商，也使收入质量更难解释。伙伴融资支持的需求，应与独立客户持续现金付款区别对待。需要跟踪承诺、抵押和信用，而非只看确认收入。",
    "第六是地域与政策：先进制程和关键投入集中，出口、关税、网络事件和冲突可中断供给。第七是社会许可：电价、水、土地、隐私和版权可拖慢部署或增加成本。第八是估值久期：二十年估值可能大量依赖终值，小幅利润率或退出倍数变化可超过几个优秀季度。",
    "悲观情景不是最坏情况，股票可能损失大部分价值，复利企业也可能不再复利。应对方式不是将所有不确定变量设为乐观，而是为风险定价、要求安全边际并监测证据。长期既增加再投资潜力，也增加竞争格局根本变化的机会。",
  ] },
  { id: "monitor", title: "15. A decision process for the next decade", titleZh: "15. 未来十年的决策流程", sources: ["sec", "iea26"], paragraphs: [
    "Review the chain quarterly, but separate operating evidence from the share price. For platforms, track revenue quality, net retention, paid usage, accepted task outcomes and cash after infrastructure renewal. For chips, track end-customer concentration, inventory, purchase commitments, software adoption and returns on development spending. For foundries and equipment, track utilization, yield, geographic mix, capex per incremental revenue and customer acceptance. For power suppliers, track firm orders, cancellations, capacity additions and warranty costs.",
    "Refresh the market snapshot before using the valuation outputs. Reconcile fiscal calendars, stock splits, ordinary shares and ADS ratios, currencies, cash versus lease capex and GAAP versus adjusted profit. Remove paper investment gains from operating profitability. Retain the original filing date and source, and mark management guidance and analyst estimates differently from historical facts. A convenient data feed is a starting point for validation, not an authority that makes unit errors disappear.",
    "Use a thesis checklist with measurable invalidation triggers. Examples include several quarters of cash conversion deterioration despite revenue growth, utilization below break-even, backlog cancellations above new bookings, or persistent maintenance capex exceeding the model. A trigger should lead to investigation and a revised valuation, not an automatic trade based on one quarter. Timing effects, working capital, acquisitions and accounting changes can explain a temporary mismatch.",
    "The practical conclusion is selective ownership rather than indiscriminate exposure. Search for businesses that solve scarce problems, retain pricing power, reinvest at sensible returns and distribute economic cash after compensation and renewal. Then insist on an entry price that can withstand weaker growth and a less generous exit valuation. That discipline is more likely to survive twenty years of technological change than a portfolio built around today's most impressive demonstration.",
  ], paragraphsZh: [
    "按季度复核全链，同时区分运营证据与股价。平台看收入质量、净留存、付费用量、合格任务与设施更新后现金；芯片看终端集中、库存、采购承诺、软件采用和研发回报；代工设备看利用率、良率、地域、每新增收入资本投入和验收；电力供应商看确定订单、取消、扩产及保修。",
    "使用估值前更新市场快照，协调财年、拆股、普通股与 ADS、币种、现金与租赁资本开支、GAAP 与调整利润，剔除经营盈利中的账面投资收益。保留申报日期和来源，并区分管理层指引、分析师估计与历史事实。数据接口是核验起点，不是消除单位错误的权威。",
    "建立可量化失效清单，例如收入增长但现金转化连续恶化、利用率低于盈亏线、取消订单超过新增，或维护资本投入持续超过模型。触发应引导调查和重新估值，而非因一个季度自动交易。时间差、营运资本、并购和会计变动可能解释临时偏差。",
    "实际结论是选择性持有，而非无差别暴露。寻找解决稀缺问题、保有定价权、合理再投资，并在薪酬与更新之后产生经济现金的企业，再要求买价能承受更弱增长和更低退出估值。相比围绕今日最佳演示构建组合，这种纪律更可能跨越二十年技术变化。",
  ] },
];

export const SECTORS = [
  ["Workflow, identity, data and security", "工作流、身份、数据与安全", "High if outcome ownership survives", "若掌握成果则高", "Highest long-duration preference", "长期优先", "Net retention; accepted tasks; economic FCF; pricing per outcome", "净留存、合格任务、经济现金流、成果价格"],
  ["Qualified power and cooling equipment", "认证电气与冷却设备", "Strong buildout visibility", "建设需求较清晰", "Durable, but normalize backlog", "持续，但须正常化订单", "Firm backlog; cancellations; margin; service attachment", "确定订单、取消、利润率、服务附着"],
  ["Integrated accelerators and custom design", "整合加速器与定制设计", "High, concentrated and cyclical", "高但集中且周期化", "Architecture substitution risk", "架构替代风险", "Useful throughput/$; share; customer concentration; gross profit", "有效吞吐/美元、份额、客户集中、毛利润"],
  ["Foundry, packaging and lithography", "代工、封装与光刻", "Scarce capability, capital-heavy", "能力稀缺，资本重", "Strong moats; geographic exposure", "壁垒强，地域风险", "Yield; utilization; capex/sales; service; ROIC", "良率、利用率、资本强度、服务、ROIC"],
  ["Networking, optics and memory", "网络、光互连与存储", "Selective; avoid commodity extrapolation", "精选，勿外推商品高峰", "Software and qualification matter", "软件与认证重要", "Job completion; inventory; bit supply; qualification; cash conversion", "任务时间、库存、比特供给、认证、现金转化"],
  ["Cloud and model platforms", "云与模型平台", "Distribution helps; renewal risk", "分发有利，更新有风险", "Attractive only with capital discipline", "取决于资本纪律", "Paid utilization; capex cohorts; depreciation; customer ROI", "付费利用率、资本批次、折旧、客户回报"],
  ["Merchant generation and compute rental", "现货发电与算力租赁", "Contract-specific, not blanket high ROI", "取决合同，不宜泛称高回报", "Commodity and residual-value risk", "商品与残值风险", "Contract price; credit; utilization; replacement; fuel exposure", "合同价、信用、利用率、更新、燃料"],
  ["Physical AI and scientific discovery", "物理 AI 与科学发现", "Selective commercial deployments", "精选商业部署", "Large option value, wide dispersion", "选择权大，分化大", "Uptime; interventions; payback; trials; milestone cash", "运行率、介入、回收期、临床、里程碑现金"],
];
