import { LLY_SOURCES as s } from "./operatingMetrics";
export const LLY_REPORT = [
  {
    titleEn: "1. Executive summary",
    titleZh: "1. 执行摘要",
    en: "Lilly is a pharmaceutical research and manufacturing platform whose recent growth is dominated by tirzepatide. The investment question is not simply whether obesity treatment demand is large. It is whether net pricing, access, supply execution and successful franchise renewal can turn that demand into durable cash returns at the market valuation. Our analysis separates reported earnings, issuer adjustments and independent cash-flow assumptions. Strong gross margins are not equivalent to distributable cash when capacity, acquired research and acquisitions consume capital. The base scenario already assumes expansion; it is not a conservative liquidation estimate. No scenario probabilities or personalized investment recommendation are assigned.",
    zh: "礼来是制药研发与制造平台，近期增长主要由替尔泊肽驱动。投资问题不只是肥胖治疗需求是否庞大，而是净价、准入、供应执行及产品更新能否把需求转化为足以支撑市场估值的持久现金回报。本文区分报告利润、公司调整及独立现金流假设。当产能、购入研发和收购消耗资本时，高毛利并不等于可分配现金。基准情景已包含扩张，不是保守清算价值。情景不赋予概率，不构成个性化建议。",
    source: s.earnings,
  },
  {
    titleEn: "2. History and comparability",
    titleZh: "2. 历史与可比性",
    en: "Founded in Indianapolis in 1876, Lilly has survived by renewing products rather than protecting an unchanged portfolio indefinitely. That is the useful interpretation of its long history. The historical financial database begins in 2011, not at incorporation or IPO. Later acquisitions and the separation of Elanco complicate comparisons of revenue, net income and cash generation. The database uses the latest available comparable SEC flow facts and original balance contexts, so it is explicitly ex-post. Changes in R&D taxonomy and missing early fields are marked rather than filled with invented precision. Long-run trend lines must be read with these boundaries in mind.",
    zh: "礼来于 1876 年创立于印第安纳波利斯，其长期生存依靠产品更新，而不是永久保护不变的组合。本文历史数据库从 2011 年开始，不从创立或上市开始。后续收购及 Elanco 分离使收入、净利润与现金创造的比较复杂化。数据库采用最新可比 SEC 流量及原始余额，因此明确属于事后历史。研发分类变化与早期缺失字段标注而不虚构精度。长期趋势线必须结合这些边界解读。",
    source: s.annual,
  },
  {
    titleEn: "3. Business model and defensibility",
    titleZh: "3. 商业模式与壁垒",
    en: "The platform converts discovery, clinical development, regulatory work, manufacturing and commercial access into medicine sales and collaboration income. Each stage can destroy value as well as create it. Scientific differentiation is only one layer of defensibility: reliable production, physician experience, distribution and payer coverage can matter just as much economically. Our inference is that scaled execution makes the franchise harder to replicate, but not immune to competition or price concessions. Lilly reports one operating segment; therapeutic categories and product revenue should not be presented as separately disclosed profit pools. We do not invent a product-level cost or lifetime patient value.",
    zh: "平台将发现、临床开发、监管、制造及商业准入转化为药品销售与合作收入，每个阶段都可能创造或损失价值。科学差异化只是壁垒的一层；可靠生产、医生经验、分销及支付方覆盖在经济上同样重要。我们的判断是规模执行提高复制难度，却不能免疫竞争或价格让步。礼来仅报告一个经营分部，治疗领域与产品收入不能当作独立披露的利润池。本文不虚构单品成本或患者终身价值。",
    source: s.quarter,
  },
  {
    titleEn: "4. Financial quality and operating leverage",
    titleZh: "4. 财务质量与经营杠杆",
    en: "Revenue growth has lifted the earnings base, but the source and persistence of each improvement matter. Derived operating profit excludes the Other-net line, preventing investment income or financing effects from masquerading as operating performance. Reported R&D, acquired IPR&D and special charges remain in the historical GAAP bridge. In forecasts we use a different, explicitly normalized perimeter and then charge cash for external pipeline renewal. Examine gross margin, internal R&D intensity, capex and cash conversion together. A single quarter can contain favorable rebates, milestones, mix and timing effects that should not automatically become recurring margin assumptions.",
    zh: "收入增长抬升盈利基础，但改善的来源及持久性更重要。推导营业利润排除 Other-net，避免投资或融资收益伪装成经营业绩。历史 GAAP 桥保留报告研发、购入 IPR&D 及特殊费用。预测采用明确不同的规范化范围，再扣外部管线更新现金。应共同检查毛利、内部研发强度、资本开支及现金转化。单季的有利返利、里程碑、结构及时间影响不能自动变成经常性利润率假设。",
    source: s.quarter,
  },
  {
    titleEn: "5. Product concentration and demand quality",
    titleZh: "5. 产品集中度与需求质量",
    en: "Mounjaro and Zepbound serve different markets but share tirzepatide exposure. Their combined share of sales is a more useful concentration measure than the number of brand names. Volume growth can accompany falling realized prices; reimbursement expansion may increase access while reducing revenue per unit. Collaboration milestones and changes in estimates for prior shipments can also support a quarter without indicating equal growth in recurring prescription economics. Follow the product/geography tables and disclosed volume-price bridge rather than extrapolating list prices or social-media demand. Selected product rows are not a complete company revenue reconciliation; therapeutic totals provide that check, subject to rounding.",
    zh: "Mounjaro 与 Zepbound 服务不同市场，但共享替尔泊肽风险。合计收入占比比品牌数量更能体现集中度。销量增长可伴随实现价格下降；医保扩展可能提高准入却降低单位收入。合作里程碑与历史发货估计调整也能支撑单季，而不意味着处方经济同等增长。应追踪产品地域表及披露的量价桥，不外推标价或社交媒体需求。精选产品表不是全公司勾稽；治疗领域总数提供该检查，允许舍入。",
    source: s.earnings,
  },
  {
    titleEn: "6. Research and manufacturing economics",
    titleZh: "6. 研发与制造经济",
    en: "Internal research is an ongoing operating cost of keeping the platform competitive. Acquired research is economically another form of renewal even when its accounting location differs. Adding back an IPR&D charge to operating cash and stopping there can overstate owner cash when the acquisition payment appears in investing activities. We display both measures and deduct a recurring pipeline cash reserve in normalized forecasts. Manufacturing also requires more than buildings: qualification, work-in-process, supply reliability and utilization determine returns. Positive terminal net capex and continuing research replacement are necessary conditions for a credible perpetuity, not optional penalties added to an otherwise capital-free model.",
    zh: "内部研发是保持平台竞争力的持续经营成本；购入研发在经济上也是更新，即使会计分类不同。当购入现金列在投资活动时，只将 IPR&D 费用在经营现金中加回可能高估股东现金。本文同时展示两种口径，并在规范化预测中扣持续管线预留。制造不止是建筑：认证、在产品、供应可靠性及利用率决定回报。终值正净资本支出与研发更新是可信永续价值的必要条件，而非对无资本模型额外加罚。",
    source: s.quarter,
  },
  {
    titleEn: "7. Balance sheet and capital allocation",
    titleZh: "7. 资产负债与资本配置",
    en: "A fast-growing earnings stream does not eliminate financing constraints. Manufacturing investment, pipeline purchases, full business acquisitions, dividends and buybacks all compete for cash. Rebate liabilities are operating obligations, not free permanent funding to capitalize without analysis. Our DCF adds dated cash and deducts financial debt, retains rent in margins and excludes noncurrent strategic investments from surplus cash. It does not deduct operating liabilities again after modeling working capital. The latest available balance sheet is not an October cash statement. Share buybacks are not an extra cash-flow addback or a guaranteed future reduction in the valuation denominator.",
    zh: "快速增长的利润不会消除融资约束。制造投入、管线购买、完整企业收购、股息及回购共同争夺现金。返利负债是经营义务，不是可无条件资本化的永久免费资金。DCF 加入有日期的现金并扣金融债务，租金保留利润率中，长期战略投资不当作剩余现金。建模营运资本后不重复扣经营负债。最新余额并不是十月现金表。回购不是现金流额外加回，也不是估值分母必然减少。",
    source: s.quarter,
  },
  {
    titleEn: "8. Growth drivers and pipeline discipline",
    titleZh: "8. 增长驱动与管线纪律",
    en: "Growth can come from broader access, international penetration, supply expansion, new indications and replacement products. These channels have different margins and evidence requirements. Foundayo is already reflected in the latest disclosed product table; retatrutide remains investigational in the September issuer update. We do not translate a clinical headline into a guaranteed launch date, market share or safety conclusion. Successful trials can still require regulatory, manufacturing and commercial execution. The aggregate forecast expresses possible platform outcomes rather than a molecule-by-molecule risk-adjusted present value. A dedicated patent and launch model would be a meaningful extension, not evidence that the current terminal value is certain.",
    zh: "增长可来自扩大准入、国际渗透、供应扩展、新适应证及替换产品；这些渠道的利润率和证据要求不同。Foundayo 已进入最新披露产品表；九月公司更新中 retatrutide 仍处研究阶段。本文不把临床标题转为必然上市日期、份额或安全结论。成功试验后仍需监管、制造及商业执行。汇总预测表达平台可能结果，而非逐分子风险调整现值。完整专利上市模型是有价值的扩展，不意味着当前终值确定。",
    source: s.september,
  },
  {
    titleEn: "9. Competition and market structure",
    titleZh: "9. 竞争与市场结构",
    en: "Novo Nordisk remains a direct cardiometabolic competitor, with oral and injectable offerings discussed in its own 2026 disclosures. Compare primary-source evidence rather than making cross-trial efficacy rankings from unrelated endpoints or populations. Other research platforms, payer bargaining and new modalities can also limit pricing power. In our analytical framework, the scarce economic resource is durable access at an acceptable net price, not simply manufacturing the largest number of doses. Oral products may broaden the market while changing mix and cannibalizing existing sales. Competition can lower returns even while the total treatment market continues expanding.",
    zh: "诺和诺德仍是直接心血管代谢竞争者，其 2026 披露讨论口服及注射产品。应比较一手资料，不用不同终点或人群的试验做简单疗效排名。其他研发平台、支付方议价与新技术也可能限制定价权。本文分析中稀缺资源是可接受净价下的持久准入，而非单纯生产最多剂量。口服药可能扩大市场，同时改变结构并替代现有销售。即使治疗市场扩大，竞争仍可压低回报。",
    source: s.peer,
  },
  {
    titleEn: "10. Management and execution",
    titleZh: "10. 管理层与执行",
    en: "Evaluate management through observable decisions: staged manufacturing investment, cash discipline in external research, transparent accounting adjustments and progress against disclosed operating evidence. David Ricks and Lucas Montarce sign the latest filing's control evaluation; that is a dated disclosure, not a qualitative guarantee about future execution. A stronger pipeline can justify investment, but the price paid and the eventual cash return remain separate questions. Our framework favors tracking acquisition-inclusive cash demands and leverage alongside launch narratives. Do not infer a successful capital-allocation record merely from a rising share price or normalize every unfavorable cost away.",
    zh: "应通过可观察决策评价管理层：分阶段制造投入、外部研发现金纪律、透明会计调整及披露经营目标进度。David Ricks 与 Lucas Montarce 签署最新申报控制评价；这是有日期的披露，不是未来执行的保证。更强管线可以支持投资，但购买价格与最终现金回报是不同问题。本文主张在上市叙事旁跟踪包含收购的现金需求及杠杆，不因股价上涨就认定资本配置成功，也不将所有不利成本规范化剔除。",
    source: s.quarter,
  },
  {
    titleEn: "11. Principal risks and monitoring",
    titleZh: "11. 主要风险与监测",
    en: "The risks are correlated: a concentrated franchise can face clinical or quality issues just when new factories, acquired programs and reimbursement commitments require cash. Lower net prices, rebate reversals, coverage restrictions, patent challenges and launch delays can reduce both growth and margins. Monitor inventory versus sales, receivables and rebates, cash after investing-classified research, net debt and recurring research intensity. A high valuation magnifies the effect of disappointing duration rather than only the next quarter's earnings. Our bear scenario includes revenue contraction and margin erosion; working-capital releases in contraction are a modeling convention and may not be fully realizable.",
    zh: "风险具有相关性：集中产品群可能在新工厂、购入项目及医保承诺需要现金时遭遇临床或质量问题。净价下降、返利反转、覆盖限制、专利挑战及上市延迟可同时削弱增长和利润率。应监测库存相对销售、应收与返利、扣投资分类研发后的现金、净债务及持续研发强度。高估值放大的是增长期限不及预期，而不只是下一季利润。悲观情景含收入收缩和利润下降；收缩时营运资本释放仅为约定，未必完全实现。",
    source: s.annual,
  },
  {
    titleEn: "12. Valuation framework",
    titleZh: "12. 估值框架",
    en: "The model values ten explicit years plus an assumed remaining-year cash stub and terminal platform cash. Normalized operating margins retain internal R&D, SBC and rent, exclude acquired IPR&D and special charges, and are independent assumptions rather than issuer performance-margin guidance. We subtract a full cash pipeline reserve without a tax benefit, capex and incremental working capital. Terminal cash includes both continuing pipeline spending and net production reinvestment. WACC, terminal growth, renewal cost and dilution sensitivities expose the dependence on duration. No scenario outcome is a target guaranteed to occur; compare the market price with the embedded operating requirements, not just a headline valuation spread.",
    zh: "模型估值十个明确年度、假设的剩余年度现金及平台终值。规范化营业利润率保留内部研发、股权激励及租金，剔除购入 IPR&D 和特殊费用；它是独立假设，不是公司业绩利润率指引。扣除无税惠的全额管线现金预留、资本开支及增量营运资本。终值含持续管线及净生产再投资。WACC、永续增长、更新成本和稀释敏感性展示对期限的依赖。情景不是必然实现目标；应比较股价所要求的经营条件，而非仅看估值差。",
    source: s.earnings,
  },
  {
    titleEn: "13. Investment conclusion",
    titleZh: "13. 投资结论",
    en: "Lilly's research engine and expanding production offer meaningful commercial opportunity, but opportunity and an attractive purchase price are not interchangeable. The strongest thesis requires durable net revenue growth, manufacturing returns and repeated portfolio renewal while preserving funding flexibility. The most important counterargument is that concentration, reinvestment and access costs may absorb more of the growth than adjusted earnings suggest. Use the report as a research framework with explicit missing data and dated balances. Recheck new filings, net-price evidence, pipeline status and the market quote before making decisions. This is general financial research, not individualized investment advice or a recommendation to use any medicine.",
    zh: "礼来的研发引擎与扩张生产带来重要商业机会，但机会不等于有吸引力的购买价格。最强论点要求持久净收入增长、制造回报及反复组合更新，同时保留融资弹性。最重要反论点是集中度、再投资及准入成本可能消耗比调整利润暗示更多的增长。本文是有缺失数据、有日期余额的研究框架。决策前应重查新申报、净价证据、管线状态及报价。这是一般财务研究，不是个性化投资建议，也不是使用任何药物的建议。",
    source: s.results,
  },
];
