import { AMD_SOURCES as s } from "./operatingMetrics";
export const AMD_REPORT = [
  {
    titleEn: "1. Executive summary",
    titleZh: "1. 执行摘要",
    en: "AMD combines a growing server CPU franchise, an expanding accelerator platform and cyclical client, gaming and embedded businesses. The independent investment question is whether durable cash profits can justify the current price after the costs of software, capacity, customer incentives and dilution. Product announcements establish opportunity, not realized shareholder returns. Our framework separates reported GAAP performance, issuer adjustments and analyst scenarios. The ten-year base case assumes substantial expansion already; it should not be described as a low-expectations valuation. We use no assigned scenario probabilities and make no personalized recommendation.",
    zh: "AMD 结合持续成长的服务器 CPU、扩张中的加速器平台，以及具有周期性的客户端、游戏和嵌入式业务。独立投资问题是：在软件、产能、客户激励和稀释成本之后，持久现金利润能否支持当前股价。产品公告意味着机会，而非已实现的股东回报。本文区分 GAAP 业绩、公司调整口径与分析师情景。十年基准情景已假设显著扩张，不能称为低预期估值。情景不赋予概率，也不构成个性化建议。",
    source: s.earnings,
  },
  {
    titleEn: "2. History and changing perimeter",
    titleZh: "2. 历史与业务边界",
    en: "Read the history as several different economic businesses, not a single steady-growth curve. The turnaround in x86 products, the Xilinx acquisition and the later ZT Systems transaction changed product breadth, assets and accounting. Older weak years are useful evidence of operating leverage and funding risk. The historical tables preserve fiscal periods and source provenance. Acquisition-related goodwill and amortization make post-2022 book returns difficult to compare directly with the earlier company, while the ZT manufacturing divestiture creates a continuing-versus-discontinued cash-flow distinction.",
    zh: "历史应理解为多个不同经济结构，而不是一条稳定增长曲线。x86 产品转型、Xilinx 收购和后续 ZT Systems 交易改变了产品范围、资产和会计。早期弱年份是经营杠杆和融资风险的证据。历史表保留财年和来源。收购商誉与摊销使 2022 年后的账面回报难以直接和早期相比，ZT 制造业务出售还带来持续经营与终止经营现金流的区别。",
    source: s.annual,
  },
  {
    titleEn: "3. Business model and defensibility",
    titleZh: "3. 商业模式与竞争壁垒",
    en: "The fabless model places scarce engineering talent, architecture and customer qualification ahead of owned fabrication capacity. CPU competitiveness can create a repeat platform position; accelerators also need software compatibility, distributed-system reliability and customer integration. Our analytical view is that these complements decide how much of headline chip demand becomes recurring revenue. A performance advantage is not permanent, and customers can source alternatives or design their own silicon. Supplier bargaining power and advanced packaging availability remain constraints even when demand is strong.",
    zh: "无晶圆厂模式的核心是稀缺工程人才、架构和客户认证，而不是自有制造产能。CPU 竞争力可能形成重复平台位置，加速器还需要软件兼容、分布式可靠性和客户集成。我们的分析认为，这些配套能力决定芯片需求有多少转化为经常性收入。性能优势并非永久，客户可采购替代产品或设计自有芯片。即使需求强，供应商议价权和先进封装仍构成约束。",
    source: s.annual,
  },
  {
    titleEn: "4. Financial quality",
    titleZh: "4. 财务质量",
    en: "Start with GAAP operating income rather than extrapolating adjusted EPS. Acquisition amortization is noncash but arose from a real capital-allocation decision; SBC is an economic cost that does not disappear because settlement uses shares. Investment gains and discrete tax benefits can make net income outpace operating progress. Cash conversion also depends on receivable collection, inventory and supplier-payment timing. Historical CFO-minus-capex is an observation, not enterprise FCFF: it can include SBC addbacks and discontinued activity. The forecast retains SBC expense and models working-capital investment explicitly.",
    zh: "先看 GAAP 营业利润，不直接外推调整后 EPS。收购摊销虽非现金，却来自真实资本配置；股权激励不会因以股票结算就失去经济成本。投资收益和一次性税项可能使净利润领先于经营进展。现金转化也取决于应收、库存和供应商付款时间。历史经营现金流减资本支出是观察值，并非企业 FCFF，可能包含股权激励加回及终止经营。预测保留股权激励费用并单列营运资本投入。",
    source: s.quarter,
  },
  {
    titleEn: "5. Operating metrics and segment boundaries",
    titleZh: "5. 经营指标与分部边界",
    en: "Data Center is the key growth exposure, but it bundles EPYC, Instinct and other products. We do not infer standalone accelerator margin or GPU revenue from the aggregate. Client and Gaming contains two businesses with different refresh cycles; Embedded adds longer qualification cycles and inventory digestion. Segment profit is not consolidated EBIT because All Other contains real costs. Track the segment-to-GAAP bridge alongside revenue mix. Comparisons use the current disclosed perimeter; older segment classifications cannot be spliced into a homogeneous time series without restatement.",
    zh: "数据中心是主要增长敞口，但包含 EPYC、Instinct 等产品，不能从总数推断独立加速器利润率或 GPU 收入。客户端与游戏包含更新周期不同的业务，嵌入式则有较长认证和库存消化周期。分部利润不等于合并营业利润，因为其他类别有真实成本。应把分部至 GAAP 的勾稽和收入结构一起跟踪。比较采用当前披露边界，未重述的旧分类不能拼成同质序列。",
    source: s.earnings,
  },
  {
    titleEn: "6. Company-specific economics",
    titleZh: "6. 公司特有经济性",
    en: "A fabless producer still funds capacity indirectly through inventory, prepayments and purchase commitments. Our test of economic quality is the cash earned after these commitments and the engineering needed to support each product generation, not capex intensity alone. Customer warrants align demand and equity incentives but transfer part of future value to buyers. Announced gigawatts are not equivalent to revenue backlog, immediate share issuance or guaranteed payment. Future warrant measurement and commercial concessions are additional uncertainties that a simple dilution table cannot fully capture.",
    zh: "无晶圆厂企业仍通过库存、预付款和采购承诺间接资助产能。经济质量应以承担这些义务及支持每代产品所需工程投入之后的现金衡量，而不只看资本支出率。客户权证把需求与股权激励联系起来，但也把部分未来价值转给买方。公告中的吉瓦不等于收入订单储备、立即增发或保证付款。未来权证计量和商业让利，是单纯稀释表无法完整反映的额外不确定性。",
    source: s.openai,
  },
  {
    titleEn: "7. Balance sheet and capital allocation",
    titleZh: "7. 资产负债与资本配置",
    en: "Cash and current investments exceed reported financial debt at the latest balance date, but that liquidity must support a much larger operating footprint. The model excludes long-term strategic holdings and reserves the full conditional subsequent investment commitment without assuming investment returns. Procurement and operating leases are reflected through costs and reinvestment rather than mechanically subtracted again as financial debt. This is a simplifying analyst convention: lease ramp costs, guarantees and prepayment timing deserve separate stress tests. Goodwill is not spendable liquidity, and repurchases should be evaluated against issuance and customer incentives.",
    zh: "最新余额日的现金和短期投资高于金融债务，但这些流动性需要支持更大的经营规模。模型不计长期战略持仓，并全额预留后续附条件投资承诺，不假设投资回报。采购和经营租赁通过成本与再投资体现，不机械地再次当成金融债务扣除。这是简化分析约定：租赁扩张成本、担保及预付时间仍需单独压力检验。商誉不是可支配现金，回购应结合发行和客户激励评价。",
    source: s.quarter,
  },
  {
    titleEn: "8. Growth drivers and evidence gates",
    titleZh: "8. 增长驱动与验证关口",
    en: "The scenario opportunity comes from server-platform penetration, accelerator deployments, richer system content and software adoption. Converting opportunity into value requires qualification, delivery, collection and repeat orders. We would strengthen the thesis when growth produces better GAAP margins and cash conversion without disproportionate prepayments or concessions. We would weaken it if shipment growth requires rising capital support while adjusted earnings remain detached from owner economics. Guidance is a near-term issuer expectation, not evidence that the entire ten-year market opportunity has been secured.",
    zh: "情景机会来自服务器平台渗透、加速器部署、更丰富的系统价值量和软件采用。机会转化为价值需要认证、交付、收款和复购。若增长带来更好的 GAAP 利润率与现金转化，而不伴随过度预付或让利，论点会增强；若出货增长需要持续增加资金支持，调整后利润又偏离股东经济性，则论点减弱。指引是近期公司预期，并不证明十年市场机会全部锁定。",
    source: s.earnings,
  },
  {
    titleEn: "9. Competition",
    titleZh: "9. 竞争",
    en: "The relevant competitors vary by workload. NVIDIA competes through its accelerator platform and software ecosystem; Intel and Arm-based alternatives challenge server and client CPUs; internally designed hyperscaler silicon can constrain merchant pricing. Our inference is that customers seeking a second source can create an opening without guaranteeing equal profitability. Benchmark leadership must translate into deployment cost, reliability and engineering productivity. Embedded products face a different competitive and qualification environment, which prevents a single AI valuation multiple from describing the entire company.",
    zh: "竞争者随工作负载而异。NVIDIA 依靠加速器平台和软件生态竞争；Intel 与 Arm 方案挑战服务器和客户端 CPU；云商自研芯片可能限制商用定价。我们的推断是，客户寻找第二供应源可带来入口，却不保证相同盈利。跑分优势必须转化为部署成本、可靠性和工程生产率。嵌入式产品有不同竞争与认证环境，不能用一个 AI 估值倍数描述整家公司。",
    source: s.annual,
  },
  {
    titleEn: "10. Management and execution",
    titleZh: "10. 管理与执行",
    en: "Assess management through delivery against product roadmaps, integration outcomes and the cash returns of strategic commitments. A coherent platform strategy is valuable, but its quality is proven by production acceptance and cash realization rather than announcement cadence. The independent governance question is whether incentives reward sustainable per-share returns after SBC, acquisitions and customer warrants. We use operational and capital-allocation evidence, not a management score or assumed personality premium. Execution failures can affect several generations because software and qualification cycles are cumulative.",
    zh: "应从产品路线交付、整合结果和战略承诺的现金回报评价管理层。连贯的平台战略有价值，但其质量需由生产采用和现金实现证明，而非公告频率。独立治理问题是：激励是否在股权激励、收购及客户权证之后，仍奖励可持续每股回报。我们采用经营和资本配置信息，不给管理层打分或假设个人溢价。软件与认证具有累积性，执行失败可能影响数代产品。",
    source: s.annual,
  },
  {
    titleEn: "11. Risks and monitoring",
    titleZh: "11. 风险与监测",
    en: "The downside is broader than a temporary CPU cycle. Accelerator adoption can lag, rivals can lower system costs, export controls can restrict sales and supplier concentration can interrupt delivery. Inventory, prepayments, leases and guarantees create funding exposure before customer cash arrives. Warrants may dilute holders precisely when the business becomes most successful, while accounting charges can reduce recognized revenue. Monitor cash conversion, commitment utilization, GAAP profitability and effective share count together. A deterministic model cannot price every disruption; do not mistake a sensitivity grid for a complete risk distribution.",
    zh: "下行风险不只是一轮 CPU 周期。加速器采用可能落后，竞争者可能降低系统成本，出口管制可能限制销售，供应商集中可能中断交付。库存、预付、租赁和担保使资金敞口先于客户现金出现。权证可能在业务最成功时稀释持有人，会计费用还可能减少确认收入。应同时监测现金转化、承诺利用率、GAAP 盈利与有效股数。确定性模型无法给所有冲击定价，敏感性表不是完整风险分布。",
    source: s.quarter,
  },
  {
    titleEn: "12. Valuation framework",
    titleZh: "12. 估值框架",
    en: "The ten-year FCFF model begins in FY2027 with a separate remaining-FY2026 cash stub. The FY2026 revenue baseline is an analyst assumption, not a full-year actual or company guidance. GAAP EBIT retains SBC and assumed operating rent; finite acquired-amortization addbacks run off before terminal value. Terminal cash retains positive net capex and working-capital investment. Bear/base/bull assumptions differ in growth, margins, discount rates and incremental customer shares. Read WACC, terminal-margin and warrant sensitivity together; compare market expectations with the modeled business scale rather than selecting the most attractive price target.",
    zh: "十年 FCFF 模型从 2027 财年开始，另列 2026 剩余期间现金假设。2026 收入基数是分析师假设，并非全年实际或公司指引。GAAP 营业利润保留股权激励和假设租金，收购摊销加回在永续前逐渐归零。永续现金保留正的净资本支出与营运资本投入。悲观、基准和乐观情景在增长、利润率、折现及客户增发股数上不同。应同时阅读折现、永续利润率和权证敏感性，以模型业务规模对照市场预期，而非挑选最吸引人的目标价。",
    source: s.quarter,
  },
  {
    titleEn: "13. Investment conclusion",
    titleZh: "13. 投资结论",
    en: "AMD offers credible participation in several computing markets, but a strong product opportunity and an attractive entry price are different judgments. Our conditional conclusion is to require evidence of repeat customer demand, cash realization and improving per-share economics after all incentives. The base scenario already requires a much larger business and sustained margin expansion. A valuation premium must be supported by that execution, not simply by association with AI. Revisit the source data, commitments, warrant status and model after each filing. This research is general information, not a promise of returns or a recommendation tailored to any investor.",
    zh: "AMD 提供对多个计算市场的真实参与，但产品机会强与买入价有吸引力是两个判断。我们的有条件结论是：需要看到客户复购、现金实现及全部激励之后的每股经济性改善。基准情景已要求业务大幅扩大并持续提高利润率。估值溢价必须由执行支持，而非仅与 AI 关联。每次申报后都应重新核验数据、承诺、权证状态和模型。本文是一般信息，不承诺回报，也不针对任何投资者给出推荐。",
    source: s.annual,
  },
];
