import { AMD_SOURCES as s } from "./operatingMetrics";
export const AMD_AUDIT = [
  {
    area: "Annual / 年度",
    coverage: "FY2011-FY2025",
    status: "complete",
    source: s.annual,
    en: "15 filed annual GAAP rows; no FY2026 full-year actual. FY2025 amendment corrects MD&A, not financial statements.",
    zh: "15 个已申报年度 GAAP 期间，没有 2026 全年实际。2025 修订更正管理讨论而非财务报表。",
  },
  {
    area: "Quarterly / 季度",
    coverage: "FY2011 Q1-FY2026 Q2",
    status: "complete",
    source: s.quarter,
    en: "62 fiscal quarters; cash YTD differences and Q4 annual differences carry provenance. Q4 EPS/shares are N/A. FY2013 Q1 submission report-date typo corrected to revenue filing context.",
    zh: "62 个财季，累计现金流差额和全年差额保留出处。第四季 EPS 和股数保持 N/A。2013 第一季申报报告日误差按收入上下文更正。",
  },
  {
    area: "Balance/debt / 余额与债务",
    coverage: "Original filed context / 原申报",
    status: "partial",
    source: s.quarter,
    en: "Some older debt/D&A fields are missing. Derived liabilities disclosed. Historical EV deducts cash only, not current investments or contingent obligations; not the full current DCF bridge.",
    zh: "部分旧债务与折旧字段缺失。推算负债明确披露。历史企业价值仅扣现金，不扣短期投资或附条件义务，与当前 DCF 桥不同。",
  },
  {
    area: "Operating / 经营",
    coverage: "Q2 2026, Q1 2026, Q2 2025",
    status: "complete",
    source: s.earnings,
    en: "Current three-segment perimeter, client/gaming detail, adjusted EBIT reconciliation and Q3 non-GAAP guidance. No standalone GPU revenue or margin inferred.",
    zh: "当前三分部、客户端和游戏明细、调整后营业利润桥及第三季非 GAAP 指引。不推算独立 GPU 收入或利润。",
  },
  {
    area: "Customer incentives / 客户激励",
    coverage: "Quarter-end warrant status / 季末权证状态",
    status: "partial",
    source: s.quarter,
    en: "Up to 320M conditional shares, none vested at June 27. Later vesting, exact current dilution and future warrant charges require updates; model share stresses are assumptions.",
    zh: "最多 3.2 亿附条件股，6 月 27 日无归属。后续归属、精确当前稀释和未来权证费用需更新，股数压力为模型假设。",
  },
  {
    area: "Forecast / 预测",
    coverage: "FY2027-FY2036 plus FY2026 stub",
    status: "partial",
    source: s.quarter,
    en: "Analyst assumptions, not issuer guidance. Finite acquired-amortization runoff, positive terminal reinvestment, $5B conservative investment reserve. New leases/guarantees and concession costs are not modeled contract-by-contract.",
    zh: "分析师假设而非公司指引。收购摊销有限期归零，永续保留再投资，一次预留 50 亿美元投资承诺。新增租赁、担保和让利未逐合同建模。",
  },
  {
    area: "Filings / 申报",
    coverage: "Electronic SEC inventory / SEC 电子清单",
    status: "complete",
    source: "https://data.sec.gov/submissions/CIK0000002488.json",
    en: "Includes 10-K/Q, 8-K, S-1 and amendments where electronically available; not a complete pre-electronic company archive.",
    zh: "涵盖可得电子 10-K/Q、8-K、S-1 与修订，不是完整电子化前档案。",
  },
];
