import { TSM_SOURCES as sources } from "./operatingMetrics";
export const TSM_REPORT = [
  {
    id: "thesis",
    enTitle: "Investment thesis",
    zhTitle: "投资论点",
    source: sources.annual,
    en: "TSMC sells manufacturing capability rather than a single chip franchise. Its neutrality lets competing chip designers and system companies share a common production platform. The investment case combines advanced-process execution, customer qualification, design enablement and packaging. These capabilities support switching costs, but they do not make demand, pricing or returns on new fabs inevitable.",
    zh: "台积电出售的是制造能力，而不是单一芯片产品。中立代工模式让相互竞争的芯片设计商与系统公司使用共同的生产平台。投资逻辑由先进制程执行、客户认证、设计生态与封装能力共同构成。这些能力形成转换成本，但并不保证需求、定价或新工厂资本回报。",
  },
  {
    id: "business",
    enTitle: "Business model and moat",
    zhTitle: "商业模式与护城河",
    source: sources.annual,
    en: "A successful tape-out binds design tools, intellectual property, process rules, yield learning and delivery reliability. Moving an advanced chip to another foundry requires engineering effort and qualification, not just a lower wafer quote. TSMC reports one operating segment, so platform and node mix are operating disclosures, not separately audited profit segments. A segment-margin sum-of-the-parts model would create precision the filings do not provide.",
    zh: "一次成功流片依赖设计工具、知识产权、工艺规则、良率学习与可靠交付。将先进芯片转移到另一家代工厂，需要重新投入工程与认证工作，而非仅获得更低晶圆报价。台积电披露单一经营分部，因此平台及节点组合属于经营指标，并非分别审计的利润分部；按平台利润率进行分部加总估值会制造财报不存在的精度。",
  },
  {
    id: "latest",
    enTitle: "Latest results and earnings quality",
    zhTitle: "最新业绩与盈利质量",
    source: sources.release,
    en: "Q2 2026 TIFRS revenue was NTD 1,270.381B and parent net income NTD 706.562B. Operating income, at NTD 766.603B, is the cleaner starting point for a manufacturing forecast: non-operating gains and interest do not earn the same recurring multiple. Q3 guidance is forward-looking and must not be presented as an already reported quarter. Monthly revenue updates improve visibility into sales, not tax, margins or cash generation.",
    zh: "2026 年第二季度 TIFRS 收入为 12,703.81 亿新台币，归母净利润为 7,065.62 亿新台币。7,666.03 亿新台币营业利润更适合作为制造业务预测起点：营业外收益与利息收入不应获得相同的持续经营倍数。第三季度指引属于前瞻信息，不能当作已披露季度业绩。月度收入提高收入可见度，却不能证明税率、利润率或现金创造能力。",
  },
  {
    id: "history",
    enTitle: "Historical financial evidence",
    zhTitle: "历史财务证据",
    source: sources.facts,
    en: "The annual database spans 2015–2025, the verified IFRS company-facts window plus the latest original filing instance. It includes the 2023 revenue contraction as well as the subsequent expansion. Gross margin, operating margin and cash conversion should be read over a full cycle. ROE here uses year-end parent equity, not management’s annualized average-equity definition; the difference is intentional and labeled. Earlier years are not silently padded with incompatible accounting.",
    zh: "年度数据库覆盖 2015—2025 年，采用已核验的 IFRS 公司事实窗口，并补入最新原始申报实例。它同时保留 2023 年收入收缩与之后的扩张。毛利率、营业利润率及现金转化应跨完整周期观察。此处 ROE 使用年末归母权益，不是管理层年化平均权益口径，差异已明确标注。更早年份不会以不兼容会计数据填充。",
  },
  {
    id: "nodes",
    enTitle: "Technology and platform mix",
    zhTitle: "制程及平台组合",
    source: sources.presentation,
    en: "Q2 leading-edge wafer revenue comprises 2 nm, 3 nm, 5 nm and 7 nm. HPC leads consolidated platform sales, but includes non-AI computing. The two mixes cannot be added because their denominators overlap and differ. Higher-end mix can lift revenue without proportional wafer growth; revenue per 12-inch-equivalent wafer is consequently an illustrative productivity proxy, not an observable contractual selling price.",
    zh: "第二季度先进晶圆收入涵盖 2、3、5、7 纳米。高性能计算在合并平台收入中占主导，但也包含非 AI 计算。两种占比的分母不同且相互交叉，不能加总。高端组合可使收入增长快于晶圆出货，因此每片十二英寸等效晶圆收入只是生产率代理，并非可观察的合同销售价格。",
  },
  {
    id: "packaging",
    enTitle: "Advanced packaging and capacity",
    zhTitle: "先进封装与产能",
    source: sources.annual,
    en: "Advanced packaging expands the value delivered after wafer fabrication and can constrain AI system shipments. The economic question is whether additional packaging and process capacity earns attractive returns after equipment, labor and utilization costs. This report does not invent standalone CoWoS revenue, yield or profit. Node migration and new-fab ramps can absorb depreciation before mature utilization is reached; watch delivery execution and cash rather than capacity announcements alone.",
    zh: "先进封装扩大晶圆制造后的价值交付，也可能限制 AI 系统出货。关键经济问题是：新增封装与制程产能在承担设备、人力及利用率成本后，能否获得有吸引力的回报。本报告不编造 CoWoS 独立收入、良率或利润。节点迁移及新厂爬坡可能在达到成熟利用率前消耗折旧，应关注交付执行与现金，而不只看产能公告。",
  },
  {
    id: "cash",
    enTitle: "Capital intensity and cash conversion",
    zhTitle: "资本密集度与现金转化",
    source: sources.fullInterim,
    en: "Cash PP&E purchases are substantial, but cash capex is not the same as new asset additions. Equipment payables, subsidies, tax timing and customer deposits can shift the timing of cash consumption. Reported FCF here is operating cash flow minus gross cash PP&E only; it is not enterprise FCFF and excludes neither lease principal nor every intangible purchase. The forecast uses a separate operating-profit bridge and retains reinvestment into the terminal period.",
    zh: "现金购建固定资产规模很大，但现金资本支出不等于新增资产。设备应付款、补贴、缴税时点与客户预付款可改变现金消耗时间。此处报告 FCF 仅为经营现金流减现金固定资产购建，并未进一步扣除租赁本金或全部无形资产购买，因此不是企业自由现金流 FCFF。预测另用营业利润现金桥，并在永续期继续保留再投资。",
  },
  {
    id: "allocation",
    enTitle: "Balance sheet and capital allocation",
    zhTitle: "资产负债表与资本配置",
    source: sources.fullInterim,
    en: "A large cash balance is valuable because semiconductor investment cannot always be stopped quickly. The DCF adds June cash and deducts current debt, bonds, bank loans and minority equity once. Current marketable instruments are disclosed but excluded from base equity value to avoid assuming the entire balance is freely realizable cash. Dividends distribute equity value rather than create operating value; foreign withholding and depositary fees affect ADS investors’ realized proceeds.",
    zh: "较大的现金余额有价值，因为半导体投资并不总能迅速停止。DCF 仅一次加入六月现金，并扣除流动债务、债券、银行贷款及少数股东权益。流动有价证券列示但不计入基准权益价值，避免假设全部可自由变现为现金。股息分配权益价值，而不创造经营价值；境外预提税与存托费用影响 ADS 投资者实际所得。",
  },
  {
    id: "competition",
    enTitle: "Competition and customer bargaining",
    zhTitle: "竞争及客户议价",
    source: sources.annual,
    en: "Leading-edge competition is determined by qualified performance, yield, ecosystem and schedule, not node names alone. A small group of large customers can negotiate intensely even when switching is difficult. FY2025 top-ten concentration was 78%, with the largest two at 19% and 17%; the filing does not name them. System companies designing custom silicon may expand foundry demand while increasing dependence on a handful of capital budgets.",
    zh: "先进制程竞争由经过认证的性能、良率、生态与进度决定，而非仅看节点名称。即使转换困难，少数大客户仍可进行强有力议价。2025 年前十大客户收入占比为 78%，前两大分别为 19% 和 17%；申报文件并未具名。系统公司自研芯片可能扩大代工需求，也可能使业务更加依赖少数客户的资本预算。",
  },
  {
    id: "risk",
    enTitle: "Geography, FX and discontinuity risk",
    zhTitle: "地域、汇率与非连续风险",
    source: sources.annual,
    en: "Taiwan production concentration introduces risks that a smooth ten-year DCF cannot faithfully price. Disruption can affect production, logistics and the ability to monetize otherwise valuable equipment. Overseas fabs diversify geography gradually but introduce ramp costs and local operating requirements. A stronger TWD (fewer NTD per USD) mechanically raises translated ADS value at fixed TWD equity; actual currency effects on revenues, costs and hedges are more complex. Do not treat a higher discount rate as complete geopolitical insurance.",
    zh: "台湾产能集中带来平滑十年 DCF 难以准确计价的风险。生产中断可能影响制造、物流及设备资产变现。海外工厂逐步分散地域风险，也增加爬坡成本与当地运营要求。在新台币权益价值固定时，换算汇率分母下降才会机械性提高美元 ADS 价值；实际收入、成本及套期保值汇率效应更复杂。提高折现率不等于完整的地缘风险保险。",
  },
  {
    id: "valuation",
    enTitle: "Forecast and valuation discipline",
    zhTitle: "预测与估值纪律",
    source: sources.presentation,
    en: "Bear, base and bull paths start with explicit 2026 TWD sales and fade growth and margins over ten years. Capital intensity remains high rather than disappearing after AI demand matures. The base translation rate is 32 TWD/USD, an assumption anchored to guidance, not current spot. Terminal growth must remain below the discount rate. Compare terminal-value dependence, FX sensitivity and the market-price date before drawing a conclusion; a precise output is not a precise estimate.",
    zh: "悲观、基准、乐观情景从明确的 2026 年新台币收入出发，十年内逐渐收敛增长率及利润率。资本密集度持续存在，不会因 AI 需求成熟而消失。基准换算率为 32 新台币兑 1 美元，是参考指引的假设，而非实时汇率。永续增长率必须低于折现率。结论前应比较终值依赖、汇率敏感性及市价日期；输出数字精确不代表估计精确。",
  },
  {
    id: "monitor",
    enTitle: "Catalysts and thesis falsification",
    zhTitle: "催化剂与论点证伪",
    source: sources.quarterly,
    en: "Potential catalysts are successful node ramps, stronger customer demand, improving packaging throughput and sustained cash conversion. Falsification signals are weaker customer investment, rising inventory without matching shipments, persistently lower margins, investment outrunning operating cash, and delays in new capacity qualification. Treat monthly sales as an early signal, then verify margin and cash in the next earnings release. The watchlist favors measurable evidence over an unconditional AI-growth narrative.",
    zh: "潜在催化剂包括节点成功爬坡、客户需求增强、封装吞吐提升与持续现金转化。证伪信号包括客户投资走弱、库存增长但出货未同步、利润率持续下降、投资长期超出经营现金流，以及新产能认证延迟。月度收入仅作早期信号，随后应在财报中验证利润率与现金。本观察框架以可衡量证据为重，而非无条件的 AI 增长叙事。",
  },
  {
    id: "conclusion",
    enTitle: "Conclusion and research limitations",
    zhTitle: "结论与研究边界",
    source: sources.annual,
    en: "TSMC offers exposure to manufacturing leadership across competing chip ecosystems. The central judgment is whether durable demand and mix gains justify recurring fab investment and the price paid for the ADS. Business quality alone does not establish an attractive entry valuation. The report is independent research, not individualized investment advice or a guarantee. Annual IFRS and local TIFRS quarterly earnings are intentionally separate; uncovered historical quarters, spot FX and unverified capacity economics remain limitations rather than synthetic data.",
    zh: "台积电提供跨多个竞争芯片生态的制造领先地位敞口。核心判断是：持续需求与组合改善能否覆盖反复发生的晶圆厂投资，并支持 ADS 买入价格。业务质量本身不能证明入场估值有吸引力。本报告属于独立研究，不是个性化投资建议或保证。年度 IFRS 与本地 TIFRS 季度利润刻意分开；未覆盖历史季度、实时汇率及未核验产能经济性是研究边界，而非需要合成填补的数据。",
  },
];
