export type BroadcomReportSection = { title: string; thesis: string; bullets: string[] };

export const BROADCOM_REPORT_SECTIONS: BroadcomReportSection[] = [
  { title: "Executive Summary", thesis: "Broadcom has become a concentrated AI infrastructure and mission-critical software compounder, but the September 2026 valuation already discounts extraordinary growth and execution.", bullets: ["Q3 FY2026 revenue rose 86% to $29.6B while AI semiconductor revenue rose 221% to $16.7B.", "Q4 guidance implies roughly $105.9B of FY2026 revenue, nearly two-thirds above FY2025.", "At $357.16, the market values Broadcom near $1.74T and about 16.8x estimated FY2026 enterprise value to sales."] },
  { title: "Company History", thesis: "Broadcom is the product of Avago's semiconductor consolidation strategy and a deliberate expansion into infrastructure software.", bullets: ["The modern portfolio combines Bell Labs, HP, Broadcom Corporation, CA, Symantec enterprise security and VMware lineages.", "The $69B VMware transaction closed in November 2023 and materially changed revenue mix, debt and intangible assets.", "Hock Tan's operating model emphasizes category leadership, focused R&D and strict portfolio management."] },
  { title: "Business Model", thesis: "Semiconductor solutions generate design-win economics in custom accelerators, networking, connectivity, broadband, wireless and storage, while software supplies recurring private-cloud, mainframe and security revenue.", bullets: ["AI revenue is a subset of semiconductor solutions and includes custom XPUs and Ethernet networking.", "Infrastructure software benefits from switching costs and mission-critical workloads but carries VMware integration and customer-transition risk.", "A small number of hyperscale and distribution customers account for a meaningful share of revenue."] },
  { title: "Financial Quality", thesis: "Broadcom combines exceptional FCF conversion with acquisition-accounting noise, large intangible amortization and rising stock compensation.", bullets: ["FY2025 revenue was $63.9B and reported FCF was $26.9B in the company release.", "FY2025 stock compensation reached $7.6B with $23.8B of unrecognized compensation cost.", "GAAP margins should be read beside non-GAAP operating income, dilution and cash taxes rather than in isolation."] },
  { title: "AI Economics", thesis: "Broadcom's AI opportunity is built on custom accelerator programs and the Ethernet fabric around increasingly large clusters.", bullets: ["AI semiconductor revenue grew from $3.8B in FY2023 to $12.2B in FY2024 and approximately $19.9B in FY2025.", "Q3 FY2026 AI revenue reached $16.7B, equal to about 80% of semiconductor segment revenue.", "The principal underwriting risk is that a few hyperscale programs create both exceptional growth and exceptional concentration."] },
  { title: "VMware and Software", thesis: "VMware gives Broadcom a high-margin recurring software base, but value creation depends on durable renewal economics rather than only price and cost restructuring.", bullets: ["Infrastructure software revenue reached $27.0B in FY2025, up 26% after the first full VMware year.", "Q3 FY2026 software revenue grew 29% to $8.8B.", "Private-cloud positioning can benefit from enterprise AI, while product changes may invite customer migration and regulatory scrutiny."] },
  { title: "Balance Sheet and Capital Allocation", thesis: "Rapid cash generation is reducing VMware acquisition leverage while supporting a growing dividend and opportunistic repurchases.", bullets: ["Net debt fell from about $58.2B at FY2024 to $35.4B by Q3 FY2026.", "Broadcom paid $9.3B of dividends and repurchased $8.45B of shares in the first three quarters of FY2026.", "Large equity awards mean gross repurchases and net per-share dilution must be evaluated together."] },
  { title: "Growth Drivers", thesis: "The central growth vectors are custom AI accelerators, Ethernet switching and connectivity, and VMware Cloud Foundation adoption.", bullets: ["Q4 FY2026 guidance calls for $34.8B of revenue and $21.7B of AI semiconductor revenue.", "Additional hyperscale design wins could extend growth, but product ramps are lumpy and customer controlled.", "Software growth can add resilience as AI semiconductor comparisons become harder."] },
  { title: "Competition", thesis: "Broadcom competes at different layers against merchant silicon, internally designed hyperscaler chips, alternative custom-silicon partners and enterprise software platforms.", bullets: ["Nvidia dominates accelerated computing systems while Broadcom targets custom silicon and open Ethernet connectivity.", "Marvell and other ASIC partners compete for hyperscale custom programs.", "VMware competes with public cloud, Nutanix, Red Hat and open-source virtualization ecosystems."] },
  { title: "Management", thesis: "Management has a strong integration and capital-allocation record, but the model is unusually dependent on a small senior leadership team.", bullets: ["Hock Tan remains central to customer selection, acquisitions and operating discipline.", "CFO succession and the scale of the combined company raise execution complexity.", "Investors should monitor organic R&D productivity as well as acquisition returns."] },
  { title: "Risks", thesis: "The largest risks are AI customer concentration, program timing, valuation compression, supply-chain dependence, VMware churn, debt and dilution.", bullets: ["A delay or loss at one large AI customer can move consolidated growth sharply.", "Foundry, packaging and networking supply constraints can limit shipments or pressure margins.", "The current multiple leaves less room for ordinary semiconductor cyclicality or weaker terminal economics."] },
  { title: "Investment Conclusion", thesis: "Broadcom is one of the strongest cash-generative AI infrastructure franchises, but the investment case now requires sustained hypergrowth rather than merely solid execution.", bullets: ["The bull case needs multiple custom-XPU ramps, durable Ethernet leadership and successful VMware monetization.", "The base case supports strong business compounding but offers limited valuation error tolerance.", "The bear case shows how quickly fair value falls if AI growth normalizes before the revenue base and FCF catch up."] },
];
