export type BroadcomSourceAuditStatus = "complete" | "partial" | "needs-review";
export type BroadcomSourceAuditItem = { area: string; coverage: string; primarySource: string; sourceUrl: string; status: BroadcomSourceAuditStatus; note: string };

export const BROADCOM_SOURCE_AUDIT_NOTE = "SEC filings are authoritative for GAAP history. Broadcom releases supply the September 2 Q3 update, guidance, AI revenue and non-GAAP metrics. Yahoo Finance is used only for market-price context.";
export const BROADCOM_SOURCE_AUDIT_ITEMS: BroadcomSourceAuditItem[] = [
  { area: "Filing inventory", coverage: "Registration filings, FY2018-FY2025 10-K and recent 10-Q", primarySource: "SEC submissions API", sourceUrl: "https://data.sec.gov/submissions/CIK0001730168.json", status: "complete", note: "Generated from the current Broadcom Inc. CIK." },
  { area: "Annual financials", coverage: "FY2016-FY2025", primarySource: "SEC company facts and predecessor 10-K", sourceUrl: "https://data.sec.gov/api/xbrl/companyfacts/CIK0001730168.json", status: "complete", note: "FY2016-FY2017 use audited predecessor-CIK comparative statements." },
  { area: "Quarterly financials", coverage: "FY2024 Q1-FY2026 Q2 SEC; FY2026 Q3 release", primarySource: "SEC 10-Q and Broadcom release", sourceUrl: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial", status: "complete", note: "Q3 is kept as an official release bridge until the 10-Q is filed." },
  { area: "Segment and AI metrics", coverage: "FY2023-FY2025 and FY2026 Q1-Q3", primarySource: "Broadcom filings and releases", sourceUrl: "https://investors.broadcom.com/financial-information/quarterly-results", status: "complete", note: "FY2025 AI revenue is summed from quarterly disclosures and labeled approximate." },
  { area: "Capital economics", coverage: "FY2023-FY2026 Q3 YTD", primarySource: "Broadcom filings and Q3 release", sourceUrl: "https://www.sec.gov/Archives/edgar/data/1730168/000173016825000121/avgo-20251102.htm", status: "complete", note: "Tracks cash, debt, SBC, dividends, repurchases and acquisition intangibles." },
  { area: "Forecast and DCF", coverage: "FY2026-FY2035", primarySource: "Hobite model anchored to Q3 results and Q4 guidance", sourceUrl: "https://investors.broadcom.com/news-releases/news-release-details/broadcom-inc-announces-third-quarter-fiscal-year-2026-financial", status: "complete", note: "Forward rows after company Q4 guidance are Hobite assumptions." },
  { area: "Historical valuation", coverage: "FY2020-FY2026", primarySource: "Yahoo Finance and SEC filings", sourceUrl: "https://query1.finance.yahoo.com/v8/finance/chart/AVGO", status: "complete", note: "Prices and shares are normalized for the July 2024 ten-for-one split." },
];
