import { VST_SOURCES as sources } from "./operatingMetrics";
export type MemoSection = { en:string; zh:string; thesis:string; thesisZh:string; bullets:string[]; bulletsZh:string[]; source:string; };
export const VST_REPORT: MemoSection[] = [
  {
    en:"Executive Summary", zh:"投资摘要",
    thesis:"Vistra is an integrated merchant-power and retail platform, not a regulated utility or a pure AI infrastructure stock. The attractive asset is an existing fleet with scarce interconnection, dispatchable capacity and nuclear operating licenses. The difficult investment question is how much of higher power-market cash generation remains after growth projects, preferred distributions and financing obligations.",
    thesisZh:"Vistra 是一体化市场化发电与零售电力平台，不是受监管公用事业，也不是纯 AI 基础设施公司。现有机组的并网资格、可调度容量和核电运行许可具备稀缺性。投资关键在于：电力市场改善带来的现金，在增长项目、优先股分配和融资义务之后，还剩多少能归普通股股东。",
    bullets:["Q2 adjusted EBITDA improved while GAAP revenue declined: hedge marks and realized economics tell different stories.","The reference quote is the October 2, 2026 close, not a live price. Require a margin of safety against common-equity cash value, not an AI headline premium."],
    bulletsZh:["Q2 调整后 EBITDA 上升，但 GAAP 收入下降；套期保值估值与已实现经营收益应分开分析。","参考价格为 2026 年 10 月 2 日收盘价，并非实时行情。应以普通股现金价值衡量安全边际，而非追逐 AI 概念溢价。"],source:sources.q2,
  },
  {
    en:"Company History",zh:"公司历史",
    thesis:"The current reporting entity emerged from the restructuring of Energy Future Holdings. Dynegy broadened the generation footprint in 2018; Energy Harbor added nuclear assets in 2024; Lotus added a gas portfolio in 2025. These transactions materially change comparability. A larger revenue base is not proof of organic growth, and a purchase-price-accounting gain is not a repeatable operating return.",
    thesisZh:"当前报告主体源自 Energy Future Holdings 重组。2018 年 Dynegy 扩展发电版图，2024 年 Energy Harbor 增加核电资产，2025 年 Lotus 增加燃气机组。这些交易使历史数据可比性发生重大变化；收入规模扩大并不等同于有机增长，收购会计收益也不是可重复经营回报。",
    bullets:["The database keeps the 2017 filing but flags incomplete flow facts; predecessor results are not spliced into successor history.","Compare cash conversion and returns on invested capital through acquisitions, rather than extrapolating a simple revenue CAGR."],
    bulletsZh:["数据库保留 2017 年文件，但标注流量数据缺失，不把重组前后主体强行拼接。","应跨收购周期比较现金转化与投入资本回报，而不是机械外推收入复合增速。"],source:sources.annual,
  },
  {
    en:"Business Model",zh:"业务模式",
    thesis:"Generation sells energy and capacity; retail buys and packages electricity for end users. Integration creates a partial natural hedge between generation output and customer load, while commercial operations manage residual exposure. This is a portfolio advantage, not immunity from commodity risk: weather can simultaneously change demand, plant availability, fuel costs and collateral needs.",
    thesisZh:"发电业务出售电量与容量，零售业务采购并向终端用户提供电力套餐。一体化在发电与客户负荷之间形成部分自然对冲，商业运营团队管理剩余风险。这是组合优势，并非免疫商品风险：天气会同时改变需求、机组可用率、燃料成本及保证金需求。",
    bullets:["Retail earnings should be assessed through churn, bad debt and procurement discipline; generation through dispatch, heat rates and outage performance.","PJM capacity revenue and ERCOT energy scarcity have different market mechanics. Do not treat all regional EBITDA as interchangeable."],
    bulletsZh:["零售业务关注流失率、坏账与采购纪律；发电业务关注调度、热耗率和停机表现。","PJM 容量收入与 ERCOT 电能稀缺定价的机制不同，区域 EBITDA 不能一概而论。"],source:sources.filing,
  },
  {
    en:"Financial Quality",zh:"财务质量",
    thesis:"Unrealized derivative marks can move consolidated revenue and net income before the physical power is delivered. Q2 2026 reported net income includes a $472M unrealized loss on hedges settling in future years. Conversely, adjusted EBITDA removes some items that still matter to owners over a full cycle. Both measures need to be tied to realized cash rather than used selectively.",
    thesisZh:"未实现衍生品估值会在电力实际交付前影响合并收入与净利润。Q2 2026 净利润包含未来年度结算套保产生的 $472M 未实现损失。另一方面，调整后 EBITDA 剔除的一些项目，在完整周期内仍是股东的真实成本。两类指标都必须与实际现金核对，而不能选择性使用。",
    bullets:["H1 2026 OCF of $2.222B less $1.572B capex equals $650M; adjusted FCF before growth is a different measure.","Reported company net income and income available to common stock differ because preferred dividends are senior to common owners."],
    bulletsZh:["H1 2026 OCF $2.222B 减资本支出 $1.572B 等于 $650M；增长前调整后 FCF 是另一个指标。","公司净利润与普通股可得利润不同，因为优先股股息优先于普通股。"],source:sources.filing,
  },
  {
    en:"Operating Metrics and Hedging",zh:"运营指标与套保",
    thesis:"As of August 3, expected generation was approximately 100% hedged for 2026, 94% for 2027 and 72% for 2028. This protects near-term visibility but delays participation in higher spot or forward prices. A long-term investor must underwrite hedge roll-off and replacement prices, not multiply a newly observed electricity price by the whole fleet.",
    thesisZh:"截至 8 月 3 日，预计发电量的套保覆盖率约为：2026 年 100%、2027 年 94%、2028 年 72%。这提升近期可见性，也延缓更高市场电价的传导。长期分析应关注套保到期及重订价格，不能直接把新市场电价乘以整个机组容量。",
    bullets:["Availability during extreme heat matters more than nameplate capacity alone; management reported at least 97% commercial availability during recent heat periods, not an annual fleet utilization rate.","Collateral calls can consume liquidity even when a hedge is economically sensible. Cash on hand is not the same as total revolving-credit availability."],
    bulletsZh:["极端高温时的可用率比铭牌容量更重要；管理层披露近期高温期间商业可用率至少 97%，并非全年利用率。","即使套保在经济上合理，追加保证金仍可能消耗流动性。账面现金不等于循环授信可用额度。"],source:sources.q2,
  },
  {
    en:"Generation and Retail Economics",zh:"发电与零售经济",
    thesis:"Retail produced $1.622B of 2025 segment adjusted EBITDA, providing a different earnings stream from the generation regions. East was the largest generation contributor at $2.282B. The quarterly comparison shows substantial East and Texas improvement, but a single spring or summer quarter cannot establish a permanent margin because outages, load and hedged settlements are seasonal.",
    thesisZh:"2025 年零售分部调整后 EBITDA 为 $1.622B，提供与发电区域不同的收益来源。East 是最大的发电贡献区域，为 $2.282B。季度比较显示 East 和 Texas 改善显著，但单个春夏季度无法证明永久利润率，因为停机、负荷和套保结算具有季节性。",
    bullets:["Segment EBITDA excludes Asset Closure in the ongoing total; rounded segment totals can differ slightly.","Maintenance, nuclear fuel and long-term service payments are recurring economic needs. Growth investment should not be ignored just because management reports cash before it."],
    bulletsZh:["持续经营合计不包括 Asset Closure；分部四舍五入可能导致轻微差异。","维护、核燃料和长期服务付款属于持续经济需求；增长支出不能因公司披露增长前现金流就被忽略。"],source:sources.annual,
  },
  {
    en:"Balance Sheet and Capital Allocation",zh:"资产负债表与资本配置",
    thesis:"June 30 cash was $435M against $19.595B of carrying debt, before receivables and affiliate margin financing. Preferred equity, forward repurchase obligations and minority interests also sit ahead of or alongside common shareholders. Restricted collateral and nuclear decommissioning trusts cannot simply be netted against debt as though they were excess operating cash.",
    thesisZh:"6 月 30 日现金为 $435M，债务账面值为 $19.595B，尚未包括应收账款与关联方保证金融资。优先股、远期回购义务与少数股东权益也需要考虑。受限保证金和核电退役信托不能被当作自由经营现金，简单用于抵减债务。",
    bullets:["A repurchase is only accretive if undertaken below conservative per-share value without weakening liquidity.","The model fixes diluted shares and does not assume buybacks. It separately deducts preferred distributions from common cash, rather than pretending all FCF belongs to common owners."],
    bulletsZh:["只有在低于保守每股价值、且不削弱流动性时，回购才真正增值。","模型固定摊薄股数，不假设未来回购；优先股分配从普通股现金中单独扣除。"],source:sources.filing,
  },
  {
    en:"AI Demand, Nuclear PPAs and Helix",zh:"AI 需求、核电合同与 Helix",
    thesis:"The Meta contracts cover 2,176 MW of existing output plus 433 MW of uprates, with full contracted capacity expected by 2034. Existing supply and incremental generation are not the same thing. Contract terms can stabilize asset economics, but prices, escalation and incremental profit are not fully disclosed. The base case therefore avoids assigning a separate speculative PPA premium.",
    thesisZh:"Meta 合同包括现有发电 2,176 MW 与增容 433 MW，全部合同容量预计到 2034 年到位。现有供给与新增发电不能混为一谈。合同有助于稳定资产经济性，但价格、调价条款与增量利润并未完整披露，因此基础情景不另行添加猜测性合同溢价。",
    bullets:["AWS and Meta are long-duration commercial counterparties, not evidence that every nuclear megawatt earns a disclosed AI premium.","Helix introduces an up-to-$1B commitment and execution risk. The model funds the whole commitment over two assumed years but assigns no return until evidence emerges."],
    bulletsZh:["AWS 和 Meta 是长期商业客户，并不证明每一核电兆瓦都能获得已披露 AI 溢价。","Helix 带来最高 $1B 投资承诺与执行风险；模型假设两年投入全部承诺，在证据出现前不计入回报。"],source:sources.meta,
  },
  {
    en:"Acquisitions and Growth Projects",zh:"收购与增长项目",
    thesis:"Cogentrix remained pending in the reviewed Q2 documents despite FERC approval. The announced consideration involves cash, assumed debt and five million new common shares. Adding its EBITDA without adding financing and dilution would manufacture accretion. The model excludes transaction uplift and financing together; the next update must revisit both on a confirmed close.",
    thesisZh:"所审阅 Q2 文件中，Cogentrix 在获得 FERC 批准后仍未完成交割。公告对价涉及现金、承接债务及新增 500 万普通股。只加 EBITDA 而不加入融资和摊薄，会制造虚假增厚。模型同时排除交易收益与融资；后续确认交割后必须一起更新。",
    bullets:["2027 EBITDA midpoint opportunity is not formal guidance and excludes Cogentrix and Meta benefits in the cited release.","Gas expansions, nuclear uprates and storage projects must clear return hurdles after interconnection, equipment, construction and fuel costs."],
    bulletsZh:["所引公告中的 2027 年 EBITDA 中点机会区间不是正式指引，且排除 Cogentrix 与 Meta 收益。","燃气扩建、核电增容及储能项目必须在并网、设备、施工与燃料成本之后满足回报门槛。"],source:sources.q2,
  },
  {
    en:"Competition and Management",zh:"竞争与管理层",
    thesis:"Constellation competes for nuclear contracts; NRG competes through retail and dispatchable generation; regulated utilities and new project developers compete for capital and large-load relationships. Vistra's advantage is the combination of existing assets, commercial risk management and retail distribution. Jim Burke's management team should be evaluated on realized cash returns and balance-sheet resilience rather than announced capacity alone.",
    thesisZh:"Constellation 竞争核电合同，NRG 竞争零售与可调度发电，受监管公用事业及新项目开发商则竞争资本与大负荷客户。Vistra 的优势是现有资产、商业风险管理和零售渠道的组合。对 Jim Burke 团队的评价，应基于已实现现金回报与资产负债表韧性，而非仅看公告容量。",
    bullets:["No peer valuation table is fabricated: current peer multiples require matched debt, preferred claims and cash definitions.","Track integration, plant reliability, contract discipline and acquisition financing alongside EBITDA targets."],
    bulletsZh:["不编造同业估值表；比较当前倍数必须统一债务、优先股及现金定义。","跟踪整合、机组可靠性、合同纪律与收购融资，而不只关注 EBITDA 目标。"],source:sources.filing,
  },
  {
    en:"Risks and Thesis Breakers",zh:"风险与逻辑失效条件",
    thesis:"The main risks are lower replacement hedge prices, prolonged plant outages, gas-price and basis exposure, tighter capacity-market regulation, permitting delays, nuclear license renewal costs and higher financing rates. Batteries carry operating and safety risks; coal closures leave cash obligations. AI load growth is not a guarantee of attractive equity returns if competition absorbs the benefit or capital spending runs ahead of contracts.",
    thesisZh:"主要风险包括套保重订价格下滑、长期停机、天然气及基差风险、容量市场监管收紧、许可延迟、核电续证成本与融资利率上升。储能存在运营与安全风险，煤电关闭仍留下现金义务。若竞争消耗收益、或资本支出领先于合同，AI 负荷增长不保证股东回报。",
    bullets:["Bear-case trigger: post-growth common cash remains weak even as adjusted EBITDA increases.","A leverage or collateral shock can force dilution or curtail buybacks precisely when the stock is cheap."],
    bulletsZh:["熊市触发条件：调整后 EBITDA 增长，但增长投资后的普通股现金仍然疲弱。","杠杆或保证金冲击可能在股价低迷时迫使公司摊薄股权或停止回购。"],source:sources.filing,
  },
  {
    en:"Valuation Framework",zh:"估值框架",
    thesis:"Use a common-equity DCF for cash after interest, growth investment and preferred distributions. Discounting this cash at WACC and deducting debt again would mix enterprise and equity methods. An independent EV/adjusted-EBITDA cross-check adds financing, preferred and minority claims to spot common capitalization. Neither measure is a substitute for a review of hedge reset and asset-life assumptions.",
    thesisZh:"对扣除利息、增长投资及优先股分配后的现金采用普通股股权 DCF。若把这种现金按 WACC 贴现，再扣一次债务，就混淆企业与股权估值。独立的 EV/调整后 EBITDA 交叉检验，将融资、优先股及少数股东权益加入即时股权市值。两种方法都不能替代对套保重订和资产寿命的分析。",
    bullets:["Forecast revenue is an analyst illustration, not company revenue guidance; realized revenue contains hedge effects.","Terminal value is sensitive to reinvestment, finite plant lives and costs of equity. The report shows terminal-value weight and discount/growth sensitivities."],
    bulletsZh:["预测收入为分析师情景，并非公司收入指引；已实现收入含套保影响。","终值受再投资、有限机组寿命与股权资本成本影响；报告披露终值权重及折现率、增长率敏感性。"],source:sources.q2,
  },
  {
    en:"Investment Conclusion and Monitoring",zh:"投资结论与跟踪",
    thesis:"Vistra owns valuable power assets and has credible demand tailwinds, but common-shareholder returns depend on price paid and capital allocation. It is a cyclical, leveraged cash-flow investment with nuclear optionality, not a bond-like utility. Use the scenario range to size uncertainty rather than treating one precise target as certainty. This is research, not individualized investment advice.",
    thesisZh:"Vistra 拥有有价值的电力资产及可信需求顺风，但普通股回报取决于买入价格与资本配置。这是一项具有核电可选性的周期性、杠杆现金流投资，不是类似债券的公用事业。应以情景区间衡量不确定性，而不是把单一精确目标视为确定结论。本报告属于研究，不构成个性化投资建议。",
    bullets:["Monitor realized energy/capacity pricing, hedge percentages, growth capex, preferred payments, collateral liquidity and post-growth cash per share.","Revisit on Q3 results, confirmed Cogentrix close, revised guidance or disclosed PPA/Helix economics. Avoid annualizing one seasonal quarter."],
    bulletsZh:["跟踪已实现电能与容量定价、套保比例、增长支出、优先股支付、保证金流动性及每股增长后现金。","在 Q3 财报、Cogentrix 确认交割、指引调整或 PPA/Helix 经济性披露时复核，避免年化单一季节性季度。"],source:sources.q2,
  },
];
