import { VST_SOURCES } from "./operatingMetrics";
export const VST_AUDIT = [
  { area:"SEC inventory / 文件清单", status:"complete", url:"https://data.sec.gov/submissions/CIK0001692819.json", note:"10-K/10-Q and available amendments/registrations through October 4, 2026. Latest quarter June 30, filed August 10.", noteZh:"覆盖截至 2026 年 10 月 4 日的年度、季度与可得修订及注册文件。最新季度 6 月 30 日，8 月 10 日申报。" },
  { area:"Financials / 财务", status:"partial", url:"https://data.sec.gov/api/xbrl/companyfacts/CIK0001692819.json", note:"Annual as-filed accession matching; quarterly comparative facts and YTD cash-flow differences. Partial 2017, early EPS/share gaps and gross profit remain null. OCF less XBRL PPE capex is a proxy: early nuclear-fuel/LTSA classifications may differ. Consolidated income uses ProfitLoss before NCI allocation. ROE uses period-end stockholders' equity including preferred, not average common equity.", noteZh:"年度匹配原始编号，季度采用比较数据及现金流年初至今差额。2017 部分数据、早期 EPS/股数和毛利保留为空。经营现金流减 PP&E 支出为代理，早期核燃料/LTSA 分类可能不同。合并净利润采用少数股东分配前 ProfitLoss。ROE 分母为含优先股的期末权益，非平均普通股权益。" },
  { area:"Operating economics / 运营", status:"complete", url:VST_SOURCES.q2, note:"Release-backed EBITDA, hedge coverage, liquidity and guidance. Ongoing excludes Asset Closure; FCFbG is non-GAAP and before growth. 2027 opportunity is not guidance.", noteZh:"EBITDA、套期保值、流动性与指引来自业绩发布。持续运营不含资产关闭；FCFbG 为非 GAAP 且未扣增长投资。2027 机会非指引。" },
  { area:"Contracts / 合同", status:"partial", url:VST_SOURCES.meta, note:"Capacity/timetable sourced; undisclosed prices/profit not estimated. No unverified closing or synergy assumed. September notes disclosed separately; June capital structure remains the baseline pending a financing/redemption bridge.", noteZh:"容量与时间表有来源，未披露价格与利润不作估计。不假设未核实的交割或协同。9 月债务公告单独披露，融资及赎回完整核对前保留 6 月资本结构基线。" },
  { area:"Market data / 行情", status:"complete", url:"https://query1.finance.yahoo.com/v8/finance/chart/VST", note:"Dated daily closes; current reference October 2. Spot shares for current capitalization, weighted diluted shares for DCF/historical proxies. Dividend adjustments excluded from capitalization prices. Historical EV omitted pending claims reconciliation.", noteZh:"参考 10 月 2 日收盘。当前市值用期末股数，DCF/历史代理用稀释加权股数。市值股价不按股息调整。历史 EV 尚需索取权核对，暂不展示。" },
  { area:"Forecast / 预测", status:"assumptions", url:VST_SOURCES.q2, note:"Analyst common-equity DCF with growth, preferred, closure and Helix deductions. No future buyback uplift. Revenue/growth/cash conversion beyond guidance are estimates.", noteZh:"分析师普通股 DCF 扣除增长、优先股、关闭及 Helix 投入，不计未来回购收益。超出指引的收入、增速及现金转化率均为估计。" },
];
