import { MU_SOURCES } from "./memoryEconomics";
export const MU_REPORT = [
  {
    titleEn: "1. Executive summary",
    titleZh: "1. 执行摘要",
    en: "Micron is a manufacturing-led exposure to the memory intensity of computing. The attraction is not simply more AI chips: higher memory content, qualified high-bandwidth products and committed customer demand can improve the economics of each unit of production. The counterweight is a history of expensive capacity expansion and rapidly changing prices. This report separates business quality from entry valuation. Our independent analysis asks whether future cash generation can justify the October 2 share price after a meaningful normalization, rather than capitalizing the latest quarter indefinitely. All scenario values are conditional estimates, not recommendations or guaranteed targets.",
    zh: "美光提供对计算系统存储需求的制造业敞口。吸引力不只是 AI 芯片更多，而是存储含量提升、高带宽产品认证与客户需求承诺可能改善单位生产经济性。相对的风险是昂贵的产能扩张与价格快速波动。本文把业务质量和买入估值分开，独立分析未来现金创造在明显正常化后能否支持 10 月 2 日股价，而不是把最新季度盈利永续化。情景价值是有条件的估计，不是投资推荐或保证目标价。",
    source: MU_SOURCES.release,
  },
  {
    titleEn: "2. Company history",
    titleZh: "2. 公司历史",
    en: "Micron began in Boise in 1978 and developed into a global memory and storage manufacturer. This history matters because the competitive asset is accumulated process engineering and manufacturing execution, not a recent AI branding change. Institutional knowledge must repeatedly be rebuilt into new generations of products and equipment. Older cycles in the financial database provide a more useful check on capital discipline than a smooth story of uninterrupted progress. Acquisition, accounting and ownership changes mean the historical series should be read with its field-level sources rather than assumed to be economically identical in every year.",
    zh: "美光于 1978 年在博伊西创立，发展为全球存储制造商。其竞争资产是长期积累的工艺工程与制造执行，而不是近期 AI 品牌转型。组织知识必须不断落实到新产品和设备世代。数据库中较早的周期为资本纪律提供了更有用的检验，不能只看持续成长的叙事。收购、会计和所有权变化也意味着历史数据应结合逐字段来源阅读，不能假定每一年的经济结构完全相同。",
    source: "https://www.micron.com/about/company/company-timeline",
  },
  {
    titleEn: "3. Business model and moat",
    titleZh: "3. 商业模式与护城河",
    en: "DRAM serves working-memory workloads; NAND serves persistent storage. Micron combines design, process development, fabrication, assembly and qualification. Our analytical view is that process cost, power performance, reliability and successful customer integration can earn a premium, but that premium has to be renewed at each product generation. Capacity also remains a competitive weapon. Strong demand does not mean every wafer or packaging investment earns the same return. An investment thesis should distinguish differentiated qualified products from scarcity pricing in broadly substitutable memory, then ask how each behaves when available supply increases.",
    zh: "DRAM 服务工作内存，NAND 服务持久存储。美光整合设计、工艺开发、制造、组装和认证。我们的分析认为，工艺成本、能效、可靠性与客户集成可以带来溢价，但每一代产品都需要重新证明。产能仍是竞争工具，需求强不意味着每笔晶圆或封装投资都有相同回报。投资论点应区分经过认证的差异化产品与可替代存储产品的稀缺定价，并检验供给增加后各自的表现。",
    source: MU_SOURCES.annual,
  },
  {
    titleEn: "4. Financial quality and latest results",
    titleZh: "4. 财务质量与最新业绩",
    en: "The September 30 release reports FY2026 revenue of $133.188B and GAAP net income of $84.969B; Q4 revenue is $54.229B. These are unaudited release figures, not a filed FY2026 annual report. The exceptional recent margin is an observation, not a normalized earnings assumption. Cash conversion deserves separate attention because receivable growth can absorb reported profit, while financing deposits can raise liquidity without raising operating cash. The database retains negative historical earnings and cash flows. Net income is not used as enterprise cash flow: the forecast starts with operating profit, applies an assumed operating tax rate, and explicitly funds reinvestment.",
    zh: "9 月 30 日公告披露 2026 财年收入 1,331.88 亿美元、GAAP 净利润 849.69 亿美元，第四季度收入 542.29 亿美元。这些是未经审计公告数字，而非已申报 2026 财年年报。近期异常高利润率是观测值，不是正常化盈利假设。应单独审视现金转化：应收账款增长可能占用利润，融资存款能提高流动性却不增加经营现金。数据库保留历史亏损与负现金流。预测不把净利润当作企业现金流，而从营业利润出发，采用经营税率假设并明确支付再投资。",
    source: MU_SOURCES.release,
  },
  {
    titleEn: "5. Operating evidence",
    titleZh: "5. 经营证据",
    en: "The latest release separates Cloud Memory, Core Data Center, Mobile and Client, and Automotive and Embedded. Comparing their revenue growth and rounded margins is useful; treating those margins as exact allocations of consolidated profit is not. The business-unit revenue total is $6M below consolidated Q4 revenue because of the reported presentation, so the difference stays visible rather than being assigned to a fabricated segment. We do not equate all cloud sales with HBM or infer a stand-alone HBM margin. Inventory and receivables provide additional operating evidence, but year-end ratios are affected by the very large change in scale and should not be mistaken for management's average-balance days metrics.",
    zh: "最新公告分列云存储、核心数据中心、移动与客户端、汽车与嵌入式业务。比较收入增长和舍入利润率有用，但不能把这些利润率当作精确的合并利润分配。四个业务单位第四季度收入合计比合并收入少 600 万美元，保留这一呈现差异，不分配给虚构分部。我们不把全部云收入等同 HBM，也不推算其独立利润率。库存与应收提供额外证据，但年末比率受到规模巨变影响，不能当作管理层平均余额周转天数。",
    source: MU_SOURCES.release,
  },
  {
    titleEn: "6. Memory economics and customer commitments",
    titleZh: "6. 存储经济与客户承诺",
    en: "The Q3 filing describes multi-year take-or-pay strategic agreements, many with fixed prices or pricing bands and a minority with market-dependent pricing. Our inference is that these agreements can reduce some demand and pricing uncertainty, while adding customer-credit, concentration and delivery exposure. A contract is not the same as cash earned: supplier performance and enforceability still matter. Higher manufacturing complexity also creates a trade-off between usable output and premium pricing. We therefore avoid unsupported yield forecasts, contract-wide profit estimates, or a numerical claim that all future demand is secured. Those gaps are research boundaries, not zeros.",
    zh: "第三季度申报披露多年度照付不议战略协议，多数采用固定价格或价格区间，少数仍随市定价。我们的推断是，协议可能降低部分需求和定价不确定性，同时增加客户信用、集中度及交付风险。合同不等于已赚取现金，供应商履约与可执行性仍重要。制造复杂度也在可用产量和溢价间形成取舍。因此不发布无依据的良率预测、全合同利润估计，或全部未来需求已被锁定的数值结论。这些缺口是研究边界，不是零。",
    source: MU_SOURCES.quarter,
  },
  {
    titleEn: "7. Balance sheet and capital allocation",
    titleZh: "7. 资产负债表与资本配置",
    en: "Cash protects a manufacturer when equipment orders and construction cannot be stopped immediately. Our conservative valuation bridge uses September 3 cash and short-term investments, subtracts reported current and long-term debt, and excludes long-term securities. It additionally reserves the noncurrent customer contract liability as a one-time analyst adjustment for future delivery funding. That liability is not legally treated as conventional debt; this convention prevents assuming all deposit-funded liquidity is surplus while forecasting ordinary future cash collections. Readers can see the value impact of removing the reserve. The Q4 weighted diluted share count is a dated valuation proxy, not an exact current outstanding count.",
    zh: "当设备订单与建设无法立即停止时，现金保护制造企业。保守估值桥使用 9 月 3 日现金和短期投资，扣除披露的流动及长期债务，排除长期有价证券。另对非流动客户合同负债作一次分析师保留调整，以反映未来交付资金。该负债并非法律意义上的传统债务，此约定避免在预测正常未来现金收款时又把存款融资现金全部当作闲置资金。读者可查看取消保留的价值影响。第四季度加权稀释股数只是有日期的估值代理，不是当前精确流通股数。",
    source: MU_SOURCES.release,
  },
  {
    titleEn: "8. Growth drivers and investment burden",
    titleZh: "8. 增长动力与投资负担",
    en: "The growth thesis links memory content, product qualification and customer willingness to fund supply to future demand. Our scenario design does not assume that a new plant announcement immediately produces profitable revenue. Construction, equipment installation, process learning and customer qualification can lead reported sales by years. Gross capex stays above depreciation in the terminal period, acknowledging continuing technological reinvestment. Government incentives reduce realized cash investment when received, but the forecast does not assume perpetual receipts. A strong quarter should therefore be examined alongside committed investment and the cash required to carry receivables and inventories through a larger production system.",
    zh: "增长论点把存储含量、产品认证及客户愿意资助供给联系到未来需求。情景设计不假定新厂公告立即带来盈利收入。建设、设备安装、工艺学习与客户认证可能领先销售多年。永续期总资本支出仍高于折旧，承认持续技术再投资。政府补贴收到时会降低实际现金投资，但预测不假设永续收款。因此强劲季度也必须结合投资承诺，以及在更大生产体系中持有应收和库存所需现金审视。",
    source: MU_SOURCES.annual,
  },
  {
    titleEn: "9. Competition and pricing discipline",
    titleZh: "9. 竞争与定价纪律",
    en: "Our competitive framework examines product qualification, delivered performance, manufacturing cost, customer diversification and the timing of supply additions. A supplier can gain share while industry pricing weakens, so relative success and absolute shareholder returns can diverge. Premium products may have longer qualification cycles, but competitors can improve over time. The analytical question is whether customer relationships and execution sustain returns after scarcity eases. This report does not invent peer margins or market-share forecasts. Evidence of faster supply expansion, aggressive price competition or reduced customer investment would weaken the high-margin scenarios even if Micron continues to ship more bits.",
    zh: "竞争框架关注产品认证、交付性能、制造成本、客户多元化及新增供给时点。供应商可能在行业价格下降时取得份额，因此相对成功与绝对股东回报会分化。高端产品可能有更长认证周期，但对手能力会随时间提升。关键是客户关系和执行能否在稀缺缓解后维持回报。本文不编造同行利润率或份额预测。更快供给扩张、激进价格竞争或客户投资下降都会削弱高利润率情景，即使美光位元出货仍增加。",
    source: MU_SOURCES.annual,
  },
  {
    titleEn: "10. Management and incentives",
    titleZh: "10. 管理层与激励",
    en: "The latest issuer release identifies Sanjay Mehrotra as chairman and chief executive. Our management assessment emphasizes the choices an investor can subsequently measure: investment pacing, product delivery, working-capital discipline, contract quality and cash retention through the cycle. Non-GAAP exclusions should not replace the economics of employee compensation; stock-based compensation remains an expense in our forecast. A buyback authorization is not a forecast of repurchases, and dividends distribute value rather than create operating cash. Future assessment should compare promised product and investment milestones with outcomes instead of inferring managerial skill from a favorable pricing environment alone.",
    zh: "最新公司公告列明 Sanjay Mehrotra 为董事长兼首席执行官。管理层评估关注投资者之后能衡量的决策：投资节奏、产品交付、营运资本纪律、合同质量及跨周期现金保留。非 GAAP 剔除不能替代员工报酬经济性，模型保留股权薪酬费用。回购授权不等于回购预测，股息分配价值而不创造经营现金。未来应把承诺的产品和投资里程碑与结果比较，不能仅由有利定价环境推断管理能力。",
    source: MU_SOURCES.release,
  },
  {
    titleEn: "11. Risks and thesis falsification",
    titleZh: "11. 风险与论点证伪",
    en: "Principal tests are a reversal in memory pricing, slower customer infrastructure spending, product qualification delays, excess capacity and poor cash conversion. Export rules, subsidy conditions and geographic manufacturing exposure add risks that are not fully captured by increasing a discount rate. Rising receivables without collections would weaken cash quality even with strong reported earnings. A revenue decline while capex and depreciation remain elevated would challenge the claim of a permanently transformed business. Monitor actual quarterly cash, inventory, customer commitments and investment obligations, and update scenarios when the evidence changes. No mechanical model can supply an accurate probability for all disruptions.",
    zh: "核心检验包括存储价格逆转、客户基础设施支出放缓、产品认证延迟、过剩产能及现金转化不佳。出口规则、补贴条件与制造地域敞口增加了提高折现率无法完全捕捉的风险。应收增加却未收回会削弱现金质量，即使账面盈利强劲。当收入下滑而资本支出及折旧仍高企时，永久转型论点会受到挑战。应跟踪实际季度现金、库存、客户承诺及投资义务，证据变化后调整情景。机械模型无法准确给全部中断赋予概率。",
    source: MU_SOURCES.quarter,
  },
  {
    titleEn: "12. Forecast and valuation",
    titleZh: "12. 预测与估值",
    en: "Ten explicit fiscal years run from 2027 to 2036. Every case includes a contraction rather than uninterrupted extrapolation. Base-case terminal operating margin is 44%, still an optimistic structural assumption compared with many historical years; a separate terminal-margin sensitivity makes this visible. FCFF uses after-tax EBIT plus total D&A less gross cash capex, incremental working capital and new finance-leased asset investment. Finance leases remain in reported debt, deducted once; future financing repayments are not also charged to FCFF. It is not reported FCF or adjusted FCF. Late-2027 cash is discounted from October 4 using an explicit approximate year-end date. WACC, terminal growth and revenue paths are analyst inputs; none are management guidance. Terminal dependence must be considered alongside the apparently precise per-share output.",
    zh: "十个明确预测财年为 2027—2036，每个情景都包含收缩而非持续外推。基准永续营业利润率为 44%，相对很多历史年度仍是乐观结构假设，另以永续利润率敏感性明确展示。企业现金流为税后营业利润加总折旧摊销，减总现金资本支出、增量营运资本及新增融资租赁资产投资。融资租赁留在报告债务并只扣一次，不再把未来融资偿付扣入企业现金流。该值不等于报告 FCF 或调整后 FCF。2027 年末现金从 10 月 4 日起按明确近似财年末日期折现。折现率、永续增长率与收入路径都是分析师输入，不是管理层指引。每股数字看似精确，仍应结合终值依赖判断。",
    source: MU_SOURCES.release,
  },
  {
    titleEn: "13. Investment conclusion and boundaries",
    titleZh: "13. 投资结论与边界",
    en: "Micron offers direct exposure to memory demand with potentially improved contractual visibility, but manufacturing intensity and supply response remain central. The base scenario is below the dated market price, while the bull scenario requires sustained high margins and much greater scale; the bear case demonstrates the cost of normalization. These are stress narratives, not assigned probabilities. Business improvement does not automatically justify any purchase price. This independent report is not personalized investment advice. The unaudited latest year, absent continuous HBM yield series, limited contract-level disclosure and dated balance/share proxies are material limitations. Reconcile the future FY2026 10-K before treating the release snapshot as audited history.",
    zh: "美光提供直接存储需求敞口，合同可见度可能改善，但制造资本强度和供给响应仍关键。基准情景低于有日期市价，乐观情景要求持续高利润率与更大规模，悲观情景展示正常化代价。这些是压力叙事，没有指定概率。业务改善不能自动证明任何买入价格合理。本文为独立研究，非个性化投资建议。最新年度未经审计、连续 HBM 良率缺失、合同层面披露有限，以及余额和股数代理有时点限制，都是重要边界。应在未来 2026 财年 10-K 发布后核对公告快照，再将其视为审计历史。",
    source: MU_SOURCES.quarter,
  },
];
