import { META_LATEST_VALUATION } from "./valuationHistory";
export type MetaScenario = "bear" | "base" | "bull";
export type MetaForecastRow = { year: number; revenue: number; revenueGrowth: number; freeCashFlow: number; freeCashFlowMargin: number };
export type MetaDcfCase = { label: string; discountRate: number; terminalGrowth: number; pvFreeCashFlow: number; pvTerminalValue: number; enterpriseValue: number; equityValue: number; valuePerShare: number; upsideToReferencePrice: number };
const inputs: Record<MetaScenario, { label: string; startRevenue: number; growth: number[]; margins: number[]; discountRate: number; terminalGrowth: number }> = {
  bear: { label: "Bear", startRevenue: 246_000_000_000, growth: [0,13,11,9,8,7,6,5,5,4], margins: [16,17,18,19,20,21,22,22,22,22], discountRate: 10.5, terminalGrowth: 2.5 },
  base: { label: "Base", startRevenue: 250_000_000_000, growth: [0,18,15,13,11,10,9,8,7,6], margins: [18,21,24,27,29,30,31,32,32,32], discountRate: 9.5, terminalGrowth: 3 },
  bull: { label: "Bull", startRevenue: 254_000_000_000, growth: [0,23,19,16,14,12,11,10,9,8], margins: [20,25,29,33,35,36,37,38,38,38], discountRate: 8.5, terminalGrowth: 3.5 },
};
function buildForecast(input: (typeof inputs)[MetaScenario]): MetaForecastRow[] { let revenue=input.startRevenue; return input.growth.map((growth,index)=>{if(index>0)revenue*=1+growth/100;const margin=input.margins[index] ?? 0;return{year:2026+index,revenue:Math.round(revenue),revenueGrowth:growth,freeCashFlow:Math.round(revenue*margin/100),freeCashFlowMargin:margin};}); }
export const META_FORECASTS: Record<MetaScenario,MetaForecastRow[]> = { bear:buildForecast(inputs.bear), base:buildForecast(inputs.base), bull:buildForecast(inputs.bull) };
export const META_DCF_INPUTS = { referencePrice: META_LATEST_VALUATION.adjustedClose ?? 777.59, referencePriceDate: META_LATEST_VALUATION.priceDate, dilutedShares: 2_566_000_000, netCash: 90_260_000_000-83_664_000_000 };
function valueScenario(scenario: MetaScenario): MetaDcfCase { const input=inputs[scenario];const forecast=META_FORECASTS[scenario];const rate=input.discountRate/100;const terminalGrowth=input.terminalGrowth/100;const pvFreeCashFlow=forecast.reduce((sum,row,index)=>sum+row.freeCashFlow/(1+rate)**(index+1),0);const terminalValue=forecast.at(-1)!.freeCashFlow*(1+terminalGrowth)/(rate-terminalGrowth);const pvTerminalValue=terminalValue/(1+rate)**forecast.length;const enterpriseValue=pvFreeCashFlow+pvTerminalValue;const equityValue=enterpriseValue+META_DCF_INPUTS.netCash;const valuePerShare=equityValue/META_DCF_INPUTS.dilutedShares;return{label:input.label,discountRate:input.discountRate,terminalGrowth:input.terminalGrowth,pvFreeCashFlow,pvTerminalValue,enterpriseValue,equityValue,valuePerShare,upsideToReferencePrice:(valuePerShare/META_DCF_INPUTS.referencePrice-1)*100}; }
export const META_DCF_CASES: Record<MetaScenario,MetaDcfCase> = { bear:valueScenario("bear"), base:valueScenario("base"), bull:valueScenario("bull") };
export const META_FORECAST_NOTE = "Hobite FY2026-FY2035 scenarios are assumptions, not Meta guidance. They vary advertising durability, AI-driven engagement and monetization, capital intensity and eventual free-cash-flow margins.";
export const META_VALUATION_NOTE = "The DCF values cash flows after infrastructure investment. It does not capitalize undisclosed AI commitments or treat management capex guidance as a one-year anomaly.";
