import type { ReactNode } from "react";
import { META_ANNUAL_FINANCIALS, META_ANNUAL_FINANCIALS_SOURCE_NOTE } from "./annualFinancials";
import { META_CAPITAL_ECONOMICS, META_CAPITAL_NOTE } from "./capitalEconomics";
import { META_ANNUAL_FILINGS, META_LATEST_ANNUAL_FILING, META_LATEST_QUARTERLY_FILING, META_QUARTERLY_FILINGS } from "./filings";
import { META_DCF_CASES, META_DCF_INPUTS, META_FORECAST_NOTE, META_FORECASTS, META_VALUATION_NOTE } from "./forecastModel";
import { META_Q2_2026, META_Q3_2026_OUTLOOK } from "./latestQuarter";
import { META_LATEST_PLATFORM_METRIC, META_PLATFORM_METRICS, META_PLATFORM_METRICS_NOTE } from "./platformMetrics";
import { META_PUBLICATION_QA_ITEMS } from "./publicationQa";
import { META_QUARTERLY_FINANCIALS, META_QUARTERLY_FINANCIALS_SOURCE_NOTE } from "./quarterlyFinancials";
import { META_REPORT_SECTIONS } from "./reportContent";
import { META_REPORT_SECTIONS_ZH } from "./reportContentZh";
import { META_CHART_GROUPS, META_SOURCE_SYSTEMS } from "./researchPlan";
import { META_SUPPLY_ECONOMICS, META_SUPPLY_NOTE } from "./supplyEconomics";
import { META_SOURCE_AUDIT_ITEMS, META_SOURCE_AUDIT_NOTE } from "./sourceAudit";
import { META_LATEST_VALUATION, META_VALUATION_HISTORY, META_VALUATION_HISTORY_NOTE } from "./valuationHistory";

type Language = "en" | "zh";

const copy = {
  en: {
    lang: "中文", langHref: "/research/meta-complete-fundamental-analysis/zh", updated: "Updated September 24, 2026 · META · USD",
    eyebrow: "Complete Fundamental Research Hub", title: "Meta Platforms", subtitle: "A global advertising platform now funding an extraordinary AI infrastructure build, with the return on that capital as the central investment debate.",
    nav: [["thesis","Thesis"],["latest","Latest"],["operations","Operations"],["segments","Segments"],["capital","Capital"],["valuation","Valuation"],["forecast","Forecast"],["financials","Financials"],["filings","Filings"],["sources","Sources"]],
    sections: { thesis:["Investment memo","Advertising durability versus AI capital intensity"], latest:["Latest quarter","Q2 operating performance and Q3 revenue outlook"], operations:["Advertising drivers","Family DAP, ad impressions and price per ad"], segments:["AI capital intensity","Reported infrastructure investment and disclosure boundaries"], capital:["Capital allocation","Cash generation, R&D, debt and dividends"], valuation:["Scenario valuation","What the current price asks investors to believe"], forecast:["Ten-year model","Explicit revenue and free-cash-flow paths"], financials:["SEC financial database","A decade of income statements and cash flow"], filings:["Primary documents","Meta SEC filing inventory"], sources:["Research controls","Sources, audit trail and publication QA"] },
    metrics: ["Q2 2026 revenue","Family DAP","Cash + securities","Reference price"], reportNote: "Assumptions are Hobite scenarios, not Meta guidance.", disclaimer: "Research and education only, not personalized investment advice. Prices, guidance and forecasts can become stale.",
  },
  zh: {
    lang: "English", langHref: "/research/meta-complete-fundamental-analysis", updated: "更新于 2026 年 9 月 24 日 · META · 美元",
    eyebrow: "完整基本面研究中心", title: "Meta Platforms", subtitle: "全球广告平台正投入大规模 AI 基础设施；增量资本的回报是投资逻辑的核心争论。",
    nav: [["thesis","投资逻辑"],["latest","最新季度"],["operations","运营指标"],["segments","分部"],["capital","资本"],["valuation","估值"],["forecast","预测"],["financials","财务"],["filings","文件"],["sources","来源"]],
    sections: { thesis:["投资备忘录","广告韧性与 AI 资本强度"], latest:["最新季度","Q2 运营表现与 Q3 收入指引"], operations:["广告驱动","Family DAP、广告展示和单条广告价格"], segments:["AI 资本强度","已披露基础设施投资与信息边界"], capital:["资本配置","现金创造、研发、债务和股息"], valuation:["情景估值","当前股价要求投资者相信什么"], forecast:["十年模型","明确的收入与自由现金流路径"], financials:["SEC 财务数据库","十年损益表与现金流历史"], filings:["原始文件","Meta SEC 文件清单"], sources:["研究控制","来源、审计轨迹与发布 QA"] },
    metrics: ["2026 年 Q2 收入","Family DAP","现金与证券","参考股价"], reportNote: "所有预测均为 Hobite 情景假设，并非 Meta 指引。", disclaimer: "本页仅用于研究与教育，不构成个性化投资建议。市场价格、指引与预测可能迅速过时。",
  },
} as const;

const usd = (value: number | null, digits = 1) => value == null ? "-" : `$${(value / 1_000_000_000).toFixed(digits)}B`;
const pct = (value: number | null, digits = 1) => value == null ? "-" : `${value.toFixed(digits)}%`;
const multiple = (value: number | null, digits = 1) => value == null ? "-" : `${value.toFixed(digits)}x`;
const integer = new Intl.NumberFormat("en-US");
const th = "whitespace-nowrap border-b border-zinc-200 bg-zinc-100 px-3 py-2 text-left text-xs font-semibold text-zinc-600";
const td = "whitespace-nowrap border-b border-zinc-100 px-3 py-2 text-sm text-zinc-700";

function Section({ id, eyebrow, title, note, children }: { id: string; eyebrow: string; title: string; note?: string; children: ReactNode }) {
  return <section id={id} className="border-t border-zinc-200 py-10"><div className="mb-6 max-w-4xl"><p className="text-xs font-semibold uppercase text-red-700">{eyebrow}</p><h2 className="mt-2 text-2xl font-semibold text-zinc-950 md:text-3xl">{title}</h2>{note ? <p className="mt-3 text-sm leading-6 text-zinc-600">{note}</p> : null}</div>{children}</section>;
}

function TableFrame({ children }: { children: ReactNode }) { return <div className="overflow-x-auto border border-zinc-200 bg-white">{children}</div>; }

function HeroMetric({ label, value, detail, warm = false }: { label: string; value: string; detail: string; warm?: boolean }) {
  return <div className={`border-l-2 pl-4 ${warm ? "border-amber-400" : "border-red-500"}`}><p className="text-xs font-medium uppercase text-zinc-400">{label}</p><p className="mt-1 text-2xl font-semibold text-white">{value}</p><p className="mt-1 text-xs leading-5 text-zinc-400">{detail}</p></div>;
}

export function MetaResearchView({ language }: { language: Language }) {
  const t = copy[language];
  const reportSections = language === "zh" ? META_REPORT_SECTIONS_ZH : META_REPORT_SECTIONS;
  const annualMax = Math.max(...META_ANNUAL_FINANCIALS.map((row) => row.revenue ?? 0));
  const dcfCases = Object.values(META_DCF_CASES);
  const latest = META_LATEST_PLATFORM_METRIC;
  const labels = language === "zh" ? {
    source: "官方来源", annual: "年度历史", quarterly: "最近季度", history: "历史市场估值", audit: "来源审计", qa: "发布检查",
    period:"期间", revenue:"收入", gross:"毛利润", opIncome:"经营利润", netIncome:"净利润", ocf:"经营现金流", capex:"资本开支", fcf:"自由现金流", margin:"利润率",
    dataCenter:"收入", hyperscale:"Family DAP", aiCloud:"广告展示增长", edge:"单条广告价格增长", dcGrowth:"收入增长",
    inventory:"未披露 GPU 库存", supply:"未披露供应承诺", cloud:"有价证券", leases:"上半年设备购置", customerOne:"展示增长", customerTwo:"单价增长",
    cash:"现金与证券", debt:"债务", rd:"研发", repurchases:"股票回购", price:"股价", marketCap:"市值", ev:"企业价值", ps:"市销率", evSales:"EV/收入", pe:"市盈率", yield:"FCF 收益率",
    year:"年份", bear:"悲观", base:"基准", bull:"乐观", reports:"年度报告", quarterlies:"季度报告", filed:"提交日期", reportDate:"报告日期",
  } : {
    source:"Official source", annual:"Annual history", quarterly:"Recent quarters", history:"Historical market valuation", audit:"Source audit", qa:"Publication checks",
    period:"Period", revenue:"Revenue", gross:"Gross profit", opIncome:"Operating income", netIncome:"Net income", ocf:"Operating cash flow", capex:"Capex", fcf:"Free cash flow", margin:"Margin",
    dataCenter:"Total revenue", hyperscale:"Family DAP", aiCloud:"Ad impressions", edge:"Average price / ad", dcGrowth:"Total revenue growth",
    inventory:"Undisclosed GPU inventory", supply:"Undisclosed supply commitments", cloud:"Marketable securities", leases:"H1 property & equipment purchases", customerOne:"Ad impressions growth", customerTwo:"Price / ad growth",
    cash:"Cash + securities", debt:"Debt", rd:"R&D", repurchases:"Stock repurchases", price:"Price", marketCap:"Market cap", ev:"Enterprise value", ps:"P/S", evSales:"EV/Sales", pe:"P/E", yield:"FCF yield",
    year:"Year", bear:"Bear", base:"Base", bull:"Bull", reports:"Annual reports", quarterlies:"Quarterly reports", filed:"Filed", reportDate:"Report date",
  };

  return <main className="min-h-screen bg-zinc-50 text-zinc-900">
    <header className="border-b border-zinc-800 bg-zinc-950 text-white">
      <div className="mx-auto max-w-7xl px-5 py-10 md:px-8">
        <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-zinc-400"><a href="/research" className="font-medium text-red-400 hover:text-red-300">Hobite Research</a><div className="flex items-center gap-4"><span>{t.updated}</span><a href={t.langHref} className="border border-zinc-700 px-3 py-1 text-white hover:border-zinc-500">{t.lang}</a></div></div>
        <p className="mt-8 text-xs font-semibold uppercase text-red-400">{t.eyebrow}</p><h1 className="mt-3 max-w-5xl text-4xl font-semibold leading-tight md:text-6xl">{t.title}</h1><p className="mt-4 max-w-4xl text-lg leading-8 text-zinc-300">{t.subtitle}</p>
        <div className="mt-9 grid gap-6 sm:grid-cols-2 lg:grid-cols-4"><HeroMetric label={t.metrics[0]} value={usd(META_Q2_2026.revenue)} detail={`${pct(META_Q2_2026.revenueGrowth,0)} YoY · ${pct(META_Q2_2026.operatingMargin)} op. margin`} /><HeroMetric label={t.metrics[1]} value={`${(latest.hyperscaleRevenue / 1_000_000_000).toFixed(2)}B`} detail={`${pct(latest.aiCloudEnterpriseRevenue,0)} impressions · ${pct(latest.edgeComputingRevenue,0)} price / ad`} /><HeroMetric label={t.metrics[2]} value={usd(META_Q2_2026.cashAndMarketableSecurities)} detail={`${usd(META_Q2_2026.cashAndMarketableSecurities-META_Q2_2026.totalDebt)} net cash`} /><HeroMetric label={t.metrics[3]} value={`$${META_DCF_INPUTS.referencePrice.toFixed(2)}`} detail={`${multiple(META_LATEST_VALUATION.priceToSales)} FY2026E P/S`} warm /></div>
      </div>
    </header>
    <nav className="sticky top-0 z-10 overflow-x-auto border-b border-zinc-200 bg-white/95 px-5 backdrop-blur md:px-8"><div className="mx-auto flex max-w-7xl gap-6 py-3 text-xs font-medium text-zinc-600">{t.nav.map(([id,label]) => <a key={id} href={`#${id}`} className="whitespace-nowrap hover:text-red-700">{label}</a>)}</div></nav>
    <div className="mx-auto max-w-7xl px-5 md:px-8">
      <Section id="thesis" eyebrow={t.sections.thesis[0]} title={t.sections.thesis[1]}><div className="grid gap-px border border-zinc-200 bg-zinc-200 md:grid-cols-2">{reportSections.map((section) => <article key={section.title} className="bg-white p-5"><h3 className="text-lg font-semibold text-zinc-950">{section.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-700">{section.thesis}</p><ul className="mt-3 space-y-2 text-sm leading-6 text-zinc-600">{section.bullets.map((bullet) => <li key={bullet} className="border-l border-zinc-300 pl-3">{bullet}</li>)}</ul></article>)}</div></Section>
      <Section id="latest" eyebrow={t.sections.latest[0]} title={t.sections.latest[1]} note={META_Q2_2026.note}><div className="grid gap-px border border-zinc-200 bg-zinc-200 sm:grid-cols-2 lg:grid-cols-4">{[[labels.gross,usd(META_Q2_2026.grossProfit)],[labels.opIncome,usd(META_Q2_2026.operatingIncome)],[labels.netIncome,usd(META_Q2_2026.gaapNetIncome)],[labels.fcf,usd(META_Q2_2026.freeCashFlow)]].map(([label,value]) => <div key={label} className="bg-white p-4"><p className="text-xs text-zinc-500">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div><div className="mt-6 border-l-2 border-amber-500 bg-amber-50 p-5"><p className="text-xs font-semibold uppercase text-amber-800">Q3 2026 outlook</p><p className="mt-2 text-2xl font-semibold">{usd(META_Q3_2026_OUTLOOK.revenue,0)} ± {META_Q3_2026_OUTLOOK.rangePercent}%</p><p className="mt-2 max-w-4xl text-sm leading-6 text-zinc-700">{META_Q3_2026_OUTLOOK.note} </p><a href={META_Q3_2026_OUTLOOK.sourceUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs underline">{labels.source}</a></div></Section>
      <Section id="operations" eyebrow={t.sections.operations[0]} title={t.sections.operations[1]} note={META_PLATFORM_METRICS_NOTE}><TableFrame><table className="w-full min-w-[820px] border-collapse"><thead><tr>{[labels.period,labels.dataCenter,labels.hyperscale,labels.aiCloud,labels.edge,labels.dcGrowth].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{META_PLATFORM_METRICS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.sourceUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{usd(row.dataCenterRevenue)}</td><td className={td}>{(row.hyperscaleRevenue / 1_000_000_000).toFixed(2)}B</td><td className={td}>{pct(row.aiCloudEnterpriseRevenue,0)}</td><td className={td}>{pct(row.edgeComputingRevenue,0)}</td><td className={td}>{pct(row.dataCenterGrowth,0)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="segments" eyebrow={t.sections.segments[0]} title={t.sections.segments[1]} note={META_SUPPLY_NOTE}><TableFrame><table className="w-full min-w-[920px] border-collapse"><thead><tr>{[labels.period,labels.inventory,labels.supply,labels.cloud,labels.leases,labels.customerOne,labels.customerTwo].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{META_SUPPLY_ECONOMICS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.sourceUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{usd(row.inventory)}</td><td className={td}>{usd(row.supplyCommitments)}</td><td className={td}>{usd(row.aiCloudCommitments)}</td><td className={td}>{usd(row.thirdPartyLeaseCommitments)}</td><td className={td}>{row.customerOneRevenueShare ? pct(row.customerOneRevenueShare,0) : "-"}</td><td className={td}>{row.customerTwoRevenueShare ? pct(row.customerTwoRevenueShare,0) : "-"}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="capital" eyebrow={t.sections.capital[0]} title={t.sections.capital[1]} note={META_CAPITAL_NOTE}><TableFrame><table className="w-full min-w-[900px] border-collapse"><thead><tr>{[labels.period,labels.cash,labels.debt,labels.capex,labels.fcf,labels.rd,labels.repurchases].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{META_CAPITAL_ECONOMICS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.sourceUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{usd(row.cashAndInvestments)}</td><td className={td}>{usd(row.totalDebt)}</td><td className={td}>{usd(row.capitalExpenditures)}</td><td className={td}>{usd(row.freeCashFlow)}</td><td className={td}>{usd(row.researchAndDevelopment)}</td><td className={td}>{usd(row.stockRepurchases)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="valuation" eyebrow={t.sections.valuation[0]} title={t.sections.valuation[1]} note={META_VALUATION_NOTE}><div className="grid gap-px border border-zinc-200 bg-zinc-200 md:grid-cols-3">{dcfCases.map((item) => <article key={item.label} className="bg-white p-5"><div className="flex items-baseline justify-between gap-3"><h3 className="text-lg font-semibold">{language === "zh" ? ({Bear:labels.bear,Base:labels.base,Bull:labels.bull} as Record<string,string>)[item.label] : item.label}</h3><span className={`text-sm font-semibold ${item.upsideToReferencePrice >= 0 ? "text-emerald-700" : "text-rose-700"}`}>{pct(item.upsideToReferencePrice)}</span></div><p className="mt-5 text-4xl font-semibold">${item.valuePerShare.toFixed(0)}</p><p className="mt-4 text-sm text-zinc-500">{pct(item.discountRate)} discount · {pct(item.terminalGrowth)} terminal growth</p></article>)}</div><p className="mt-3 text-xs text-zinc-500">{t.reportNote} Reference: ${META_DCF_INPUTS.referencePrice.toFixed(2)} on {META_DCF_INPUTS.referencePriceDate}.</p><h3 className="mt-8 text-lg font-semibold">{labels.history}</h3><p className="mt-2 text-sm text-zinc-600">{META_VALUATION_HISTORY_NOTE}</p><TableFrame><table className="mt-4 w-full min-w-[900px] border-collapse"><thead><tr>{[labels.year,labels.price,labels.marketCap,labels.ev,labels.ps,labels.evSales,labels.pe,labels.yield].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{META_VALUATION_HISTORY.map((row) => <tr key={row.fiscalYear}><td className={td}>{row.fiscalYear}</td><td className={td}>{row.adjustedClose == null ? "-" : `$${row.adjustedClose.toFixed(2)}`}</td><td className={td}>{usd(row.marketCapitalization,0)}</td><td className={td}>{usd(row.enterpriseValue,0)}</td><td className={td}>{multiple(row.priceToSales)}</td><td className={td}>{multiple(row.enterpriseValueToSales)}</td><td className={td}>{multiple(row.priceToEarnings)}</td><td className={td}>{pct(row.freeCashFlowYield)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="forecast" eyebrow={t.sections.forecast[0]} title={t.sections.forecast[1]} note={META_FORECAST_NOTE}><TableFrame><table className="w-full min-w-[850px] border-collapse"><thead><tr><th className={th}>{labels.year}</th>{([labels.bear,labels.base,labels.bull]).map((label) => <th key={label} className={th}>{label}: {labels.revenue} / growth / {labels.fcf}</th>)}</tr></thead><tbody>{META_FORECASTS.base.map((baseRow,index) => <tr key={baseRow.year}><td className={`${td} font-medium`}>{baseRow.year}</td>{(["bear","base","bull"] as const).map((scenario) => { const row = META_FORECASTS[scenario][index]!; return <td key={scenario} className={td}>{usd(row.revenue)} <span className="text-zinc-400">/ {pct(row.revenueGrowth)} / {usd(row.freeCashFlow)}</span></td>; })}</tr>)}</tbody></table></TableFrame></Section>
      <Section id="financials" eyebrow={t.sections.financials[0]} title={t.sections.financials[1]} note={META_ANNUAL_FINANCIALS_SOURCE_NOTE}><h3 className="text-lg font-semibold">{labels.revenue}</h3><div className="mt-4 grid gap-2">{META_ANNUAL_FINANCIALS.map((row) => <div key={row.fiscalYear} className="grid grid-cols-[52px_1fr_76px] items-center gap-3 text-xs"><span>FY{row.fiscalYear}</span><div className="h-3 bg-zinc-200"><div className="h-full bg-red-600" style={{width:`${((row.revenue ?? 0)/annualMax)*100}%`}} /></div><span className="text-right">{usd(row.revenue,0)}</span></div>)}</div><h3 className="mt-8 text-lg font-semibold">{labels.annual}</h3><TableFrame><table className="mt-4 w-full min-w-[1120px] border-collapse"><thead><tr>{[labels.year,labels.revenue,labels.gross,labels.opIncome,labels.netIncome,labels.ocf,labels.capex,labels.fcf,labels.cash,labels.debt,"Gross margin","FCF margin"].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{META_ANNUAL_FINANCIALS.map((row) => <tr key={row.fiscalYear}><td className={`${td} font-medium`}><a href={row.filingUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.fiscalYear}</a></td><td className={td}>{usd(row.revenue)}</td><td className={td}>{usd(row.grossProfit)}</td><td className={td}>{usd(row.operatingIncome)}</td><td className={td}>{usd(row.netIncome)}</td><td className={td}>{usd(row.operatingCashFlow)}</td><td className={td}>{usd(row.capitalExpenditures)}</td><td className={td}>{usd(row.freeCashFlow)}</td><td className={td}>{usd((row.cash ?? 0)+(row.shortTermInvestments ?? 0))}</td><td className={td}>{usd(row.totalDebt)}</td><td className={td}>{pct(row.grossMargin)}</td><td className={td}>{pct(row.freeCashFlowMargin)}</td></tr>)}</tbody></table></TableFrame><h3 className="mt-8 text-lg font-semibold">{labels.quarterly}</h3><p className="mt-2 text-sm text-zinc-600">{META_QUARTERLY_FINANCIALS_SOURCE_NOTE}</p><TableFrame><table className="mt-4 w-full min-w-[980px] border-collapse"><thead><tr>{[labels.period,labels.revenue,labels.gross,labels.opIncome,labels.netIncome,labels.ocf,labels.capex,labels.fcf,"Gross margin","FCF margin"].map((label) => <th key={label} className={th}>{label}</th>)}</tr></thead><tbody>{META_QUARTERLY_FINANCIALS.map((row) => <tr key={row.period}><td className={`${td} font-medium`}><a href={row.filingUrl} target="_blank" rel="noreferrer" className="underline decoration-zinc-300">{row.period}</a></td><td className={td}>{usd(row.revenue)}</td><td className={td}>{usd(row.grossProfit)}</td><td className={td}>{usd(row.operatingIncome)}</td><td className={td}>{usd(row.netIncome)}</td><td className={td}>{usd(row.operatingCashFlow)}</td><td className={td}>{usd(row.capitalExpenditures)}</td><td className={td}>{usd(row.freeCashFlow)}</td><td className={td}>{pct(row.grossMargin)}</td><td className={td}>{pct(row.freeCashFlowMargin)}</td></tr>)}</tbody></table></TableFrame></Section>
      <Section id="filings" eyebrow={t.sections.filings[0]} title={t.sections.filings[1]}><div className="grid gap-5 lg:grid-cols-2">{[{title:labels.reports,rows:META_ANNUAL_FILINGS},{title:labels.quarterlies,rows:META_QUARTERLY_FILINGS}].map((group) => <div key={group.title}><h3 className="mb-3 text-lg font-semibold">{group.title}</h3><TableFrame><table className="w-full border-collapse"><thead><tr><th className={th}>Form</th><th className={th}>{labels.reportDate}</th><th className={th}>{labels.filed}</th></tr></thead><tbody>{group.rows.map((filing) => <tr key={filing.accessionNumber}><td className={td}><a href={filing.url} target="_blank" rel="noreferrer" className="font-medium underline decoration-zinc-300">{filing.form}</a></td><td className={td}>{filing.reportDate || "-"}</td><td className={td}>{filing.filingDate}</td></tr>)}</tbody></table></TableFrame></div>)}</div><p className="mt-3 text-xs text-zinc-500">Latest 10-K: {META_LATEST_ANNUAL_FILING.filingDate}. Latest 10-Q: {META_LATEST_QUARTERLY_FILING.filingDate}.</p></Section>
      <Section id="sources" eyebrow={t.sections.sources[0]} title={t.sections.sources[1]} note={META_SOURCE_AUDIT_NOTE}><div className="grid gap-6 lg:grid-cols-2"><div><h3 className="mb-3 text-lg font-semibold">{labels.source}</h3><div className="divide-y divide-zinc-200 border border-zinc-200 bg-white">{META_SOURCE_SYSTEMS.map((source) => <a key={source.name} href={source.url} target="_blank" rel="noreferrer" className="block p-4 hover:bg-zinc-50"><p className="text-sm font-semibold">{source.name}</p><p className="mt-1 text-xs leading-5 text-zinc-500">{source.use}</p></a>)}</div></div><div><h3 className="mb-3 text-lg font-semibold">{labels.audit}</h3><div className="divide-y divide-zinc-200 border border-zinc-200 bg-white">{META_SOURCE_AUDIT_ITEMS.map((item) => <a key={item.area} href={item.sourceUrl} target="_blank" rel="noreferrer" className="block p-4 hover:bg-zinc-50"><div className="flex justify-between gap-4"><p className="text-sm font-semibold">{item.area}</p><span className="text-xs font-medium uppercase text-emerald-700">{item.status}</span></div><p className="mt-1 text-xs leading-5 text-zinc-500">{item.coverage}. {item.note}</p></a>)}</div></div></div><h3 className="mt-8 text-lg font-semibold">{labels.qa}</h3><div className="mt-4 grid gap-px border border-zinc-200 bg-zinc-200 md:grid-cols-2">{META_PUBLICATION_QA_ITEMS.map((item) => <div key={item.check} className="bg-white p-4"><div className="flex justify-between gap-4"><p className="text-sm font-semibold">{item.check}</p><span className={`text-xs font-semibold uppercase ${item.status === "pass" ? "text-emerald-700" : "text-amber-700"}`}>{item.status}</span></div><p className="mt-2 text-xs leading-5 text-zinc-500">{item.evidence}</p></div>)}</div><div className="mt-8 border-l-2 border-zinc-900 pl-4 text-xs leading-5 text-zinc-500"><p>{META_CHART_GROUPS.reduce((sum,group) => sum+group.targetCount,0)} analytical views across {META_CHART_GROUPS.length} groups.</p><p className="mt-1">{t.disclaimer}</p></div></Section>
    </div>
  </main>;
}
