export type MetaReportSection = { title: string; thesis: string; bullets: string[] };

export const META_REPORT_SECTIONS: MetaReportSection[] = [
  { title:"Executive Summary", thesis:"Meta combines a vast advertising distribution system with an aggressive AI infrastructure build. The key question is whether AI raises engagement and monetization faster than capital intensity compresses cash returns.", bullets:["Q2 2026 revenue grew 28% to $60.8B while Family DAP reached 3.60B.","Ad impressions grew 14% and average price per ad rose 12%.","Reported Q2 free cash flow was $0.8B after $31.1B of capex including finance-lease principal payments."] },
  { title:"Company History", thesis:"Facebook became Meta Platforms as it expanded into a global family of communication, creator, advertising, AI and immersive-computing products.", bullets:["Facebook, Instagram, Messenger and WhatsApp form the core consumer distribution system.","The Meta rebrand made Reality Labs and longer-dated computing platforms explicit capital-allocation choices.","Generative AI connects recommendation quality, advertising measurement, creators, business messaging and future agents."] },
  { title:"Business Model", thesis:"Family of Apps monetizes user attention largely through targeted advertising; Reality Labs develops virtual and augmented reality products at a material operating loss.", bullets:["Advertising benefits from global scale, auction liquidity, measurement and advertiser tooling.","AI can improve ranking, creative, targeting and business messaging, but its direct revenue is not separately disclosed.","Reality Labs is a long-duration option rather than a near-term profit contributor."] },
  { title:"Financial Quality", thesis:"The advertising core retains high gross margins and operating cash generation, while the AI build changes free-cash-flow timing and capital intensity.", bullets:["Q2 operating income was $18.8B, a 31% margin, after legal and severance charges.","Q2 operating cash flow was $31.9B, showing the core engine remains highly cash generative.","The capex step-up makes return on incremental invested capital more important than headline revenue growth."] },
  { title:"Operating Metrics", thesis:"DAP, ad impressions and average price per ad are the clearest reported signals of the advertising system.", bullets:["Family DAP averaged 3.60B in June 2026, up 3% year over year.","Q2 impressions increased 14% and average price per ad increased 12%.","Meta does not publish recurring AI revenue, so causal AI-monetization claims should remain measured."] },
  { title:"AI Infrastructure Economics", thesis:"Meta is converting balance-sheet capacity and operating cash flow into data centers, servers and finance leases on a scale that changes its cash-flow profile.", bullets:["Q2 capex including finance-lease principal payments was $31.1B; H1 was about $50.9B.","FY2026 capex guidance is $130B-$145B, including finance leases.","The base case requires durable returns from ranking, ads, business agents and/or new products; spend alone is not a moat."] },
  { title:"Balance Sheet and Capital Allocation", thesis:"Liquidity is substantial, but debt issuance and infrastructure funding require a fuller view of net cash and fixed commitments.", bullets:["Cash, cash equivalents and marketable securities were $90.3B at Q2 2026.","Long-term debt was $83.7B after new debt issuance.","Meta paid $1.35B in Q2 dividends; buybacks were paused in the reported quarter as capital spending accelerated."] },
  { title:"Growth Drivers", thesis:"AI-assisted recommendations, advertiser tools, business messaging, creators, Threads, wearables and consumer AI provide multiple paths to incremental engagement and monetization.", bullets:["More relevant recommendations can expand engagement and available ad inventory.","AI creative and measurement can broaden the advertiser base and improve auction outcomes.","New products are optionality, but management must show disciplined return thresholds as spend scales."] },
  { title:"Competition", thesis:"Meta competes for user time, creator attention, advertising budgets, messaging use cases, AI talent and compute capacity.", bullets:["TikTok, YouTube and Snapchat compete for short-form attention and advertisers.","Apple and Google influence mobile distribution, privacy and discovery economics.","Large cloud and AI platforms compete for infrastructure inputs and may accept different investment-return standards."] },
  { title:"Management and Governance", thesis:"Founder control supports long-horizon product bets but makes transparent capital-allocation accountability especially important.", bullets:["Mark Zuckerberg remains central to AI investment priorities and long-duration bets.","Dual-class voting limits outside investors' ability to redirect strategy.","Track spending cadence, staffing, legal exposure and evidence of realized AI-driven outcomes."] },
  { title:"Risks", thesis:"Core risks include ad-cycle volatility, regulation, platform-policy change, AI spend that outruns monetization, legal proceedings, competition and Reality Labs execution.", bullets:["Q2 included $2.4B of legal-proceeding charges and $1.18B of severance expenses.","Privacy rules and mobile-platform changes can reduce signal quality or distribution control.","A sustained capex program can compress free cash flow even while revenue remains strong."] },
  { title:"Valuation", thesis:"Valuation must weigh durable advertising cash generation against capital intensity, regulatory uncertainty and the unproven revenue profile of consumer AI and Reality Labs.", bullets:["The bear case assumes slower ad growth and sustained high infrastructure intensity.","The base case assumes AI improves engagement and ad monetization while capex normalizes as a share of revenue.","The bull case requires Meta to monetize AI and new interfaces beyond the historical ad model."] },
  { title:"Investment Conclusion", thesis:"Meta is a high-quality advertising platform entering a capital-intensive phase. The thesis works when AI creates measurable improvements in the core business and earns an attractive return on the infrastructure base.", bullets:["Track DAP, impressions, price per ad, operating margin, capex and finance-lease payments together.","Treat AI claims as a hypothesis until they show up in durable business outcomes and disclosed economics.","The central debate is return on incremental AI infrastructure capital, not whether Meta can spend it."] },
];
