export type Chapter = { title: [string, string]; paragraphs: [string, string][] };

export const MID_REPORT: Chapter[] = [
  { title: ["1. Thesis: buy a monetization pathway, not an AI label", "1. 逻辑：购买变现路径，而非 AI 标签"], paragraphs: [
    ["The mid-cap opportunity sits between established mega-cap platforms and venture-like small companies. A company in this range can have enough customers and engineering scale to survive a product transition while still being small enough for a new workflow to matter. That is the attraction, not a statistical promise that mid-caps outperform. Our top ten is a selected U.S.-listed research shortlist, not the result of screening every security worldwide. It deliberately mixes software, data services, silicon and manufacturing intelligence. Each route captures a different part of the AI spending cycle, so the stocks should not be treated as interchangeable bets on one headline.", "中盘机会位于成熟巨头与创投式小公司之间。该规模公司可能已有足够客户与工程基础渡过产品转型，同时新工作流足以影响整体业务。吸引力在此，而非中盘必跑赢的统计保证。本十股为精选美股研究名单，并非全球所有证券筛选结果；刻意混合软件、数据服务、芯片与制造智能，捕获不同 AI 支出环节，不应当作同一新闻主题的可互换押注。"],
    ["Intapp and UiPath lead because workflow ownership and observable recurring demand offer a clearer route to monetization. PDF Solutions and Box follow for manufacturing data and permission-aware enterprise content. Camtek offers physical scarcity but its starting price demands more caution. GitLab and SentinelOne have relevant products with substantial compensation and competitive risks. Innodata, Ambarella and Ouster provide more concentrated data or physical-AI exposure, with greater uncertainty around customer dependence, product ramps or capital requirements. This ordering is a research judgment about evidence and survivability, not a mathematical ranking of future returns.", "Intapp 与 UiPath 靠前，因工作流控制与可观察的经常性需求提供较清晰变现路径。PDF Solutions 与 Box 分别提供制造数据与带权限内容。Camtek 有物理稀缺性，但起始价格要求谨慎。GitLab 与 SentinelOne 产品相关，却面临薪酬与竞争风险。Innodata、Ambarella 与 Ouster 的数据或物理 AI 敞口更集中，客户依赖、量产与资本需求更不确定。排序是证据与生存能力判断，不是未来回报数学排序。"],
  ] },
  { title: ["2. Where the customer actually saves money", "2. 客户真正在哪里省钱"], paragraphs: [
    ["The best customer proposition ties the product to an expensive measurable problem: recover partner time, reduce failed business transactions, detect high-value chip defects, secure endpoints, or operate machinery more safely. A vendor that reduces cost but cannot retain a portion of the savings may improve customer ROI without improving shareholder returns. Look for contracts, paid usage and renewal behavior rather than pilot counts. Unit economics should include inference costs, deployment labor, support and the cost of meeting governance requirements. A software-like gross margin is valuable only if the operating expense required to win and retain customers also becomes efficient.", "最佳客户价值对应昂贵且可衡量的问题：节省合伙人时间、减少失败交易、检测高价芯片缺陷、保护终端或安全操作设备。供应商若不能保留部分客户节省，可能提升客户 ROI 却不提高股东回报。应看合同、付费用量与续约，而非试点数量。单位经济应含推理、部署人工、支持与治理成本。软件毛利只有与获客留客费用效率改善结合才有价值。"],
    ["The economics differ by layer. Professional workflow and content platforms monetize access and expansion. Manufacturing analytics monetizes yield, connectivity and production decisions. Inspection and edge silicon depend on equipment acceptance or device shipments. Data services monetize delivered evaluation work, which may remain labor intensive. Security depends on trust and distribution as well as product performance. Cross-comparing sales multiples without respecting those differences encourages false bargains; one dollar of advertising media pass-through or hardware sales is not one dollar of high-retention subscription revenue.", "各层经济不同：专业工作流与内容平台靠接入与扩张；制造分析靠良率、连接与生产决策；检测与边缘芯片靠设备验收或出货；数据服务靠交付评估，可能劳动密集；安全依赖信任与分发，不仅是性能。忽视差异比较销售倍数会制造假便宜；广告转付或硬件收入不等于高留存订阅收入。"],
  ] },
  { title: ["3. Five years versus ten years", "3. 五年与十年"], paragraphs: [
    ["Over five years the important test is conversion: existing deployments must become durable cash generation after normal compensation and reinvestment. Over ten years the test becomes defensibility: can the company remain a necessary control layer when models become cheaper and platforms bundle functionality? We fade revenue growth in the second five-year period rather than extrapolate the latest quarter indefinitely. The model uses explicit annual dilution because rapid business growth can coexist with disappointing per-share growth. A high exit multiple is an assumption, not an asset the company already owns.", "五年核心是转化：部署须在正常薪酬与再投入后变成持续现金。十年核心是防御力：模型降价、平台捆绑后，公司是否仍是必要控制层？模型第二个五年下调增速，不无限外推最新单季。显式年度稀释反映业务增长与每股增长可不同。高退出倍数是模型假设，不是公司已拥有资产。"],
    ["We show capital-gain CAGR, not total shareholder return or a forecast of dividends. Exit value depends on modeled owner cash in the following year and a stated equity-cash multiple. The annualized quarter is merely a common starting point, not a trailing-twelve-month figure, fiscal-year forecast or consensus number. This simple screen omits starting balance-sheet claims and several issuer-specific capital structures. It can identify the assumptions required for attractive returns, but it cannot establish that a stock is undervalued without a full issuer valuation.", "展示资本利得 CAGR，而非总股东回报或股息预测。退出价值依赖下一年模型股东现金与规定倍数。单季年化仅是共同起点，不是过去十二个月、财年预测或一致预期。简化筛选遗漏初始资产负债权益与特殊资本结构，可揭示达到收益所需假设，不能替代完整估值证明低估。"],
  ] },
  { title: ["4. Portfolio and research discipline", "4. 组合与研究纪律"], paragraphs: [
    ["These names share more risk than their product descriptions suggest. Enterprise software budgets, hyperscaler spending, financing conditions and investor appetite for AI can turn together. Ten holdings do not automatically create ten independent risk sources. Avoid counting a customer and all of its suppliers as diversified demand. Review concentration by customer, business model, geography and funding dependence. For software, reconcile GAAP margins with adjusted earnings and share issuance; for hardware, reconcile gross profit with inventory and capital requirements. Consider a broad diversified benchmark as the opportunity cost of owning a concentrated thematic basket.", "这些公司共享风险超过产品描述所示：企业软件预算、云厂商投入、融资与 AI 风险偏好可能同步转向。十个持仓不等于十个独立风险源。客户及其全部供应商不是分散需求。应审视客户、模式、地域与融资集中；软件核对 GAAP 与调整利润及发股，硬件核对毛利与库存资本需求。广泛分散基准是主题集中组合的机会成本。"],
    ["A disciplined entry process starts with a full cash/debt/preferred bridge, normalized stock compensation and a conservative terminal case. Revisit the ranking after material earnings releases, acquisitions or financing, and move a company to the appropriate size article if its capitalization crosses a boundary. A change in category is not a buy or sell signal. The most useful outcome of this article is a due-diligence queue with explicit failure conditions, not an instruction to buy all ten at the frozen market prices.", "严谨买入流程从现金、债务、优先股桥接、正常化股权薪酬与保守终值开始。重大财报、并购或融资后重排；市值越界后移至相应规模文章，分类变化不等于交易信号。本文最有用的成果是带失效条件的尽调队列，而非冻结价格下买入全部十股。"],
  ] },
];

export const SMALL_REPORT: Chapter[] = [
  { title: ["1. Thesis: survival before optionality", "1. 逻辑：先求生，再看可选性"], paragraphs: [
    ["Small-cap AI investing is not simply large-cap AI investing with a larger growth rate. Customer dependence, restricted access to capital, weaker trading liquidity and less predictable execution can dominate the outcome. A successful technology may never generate attractive returns for the original common shareholders if it needs repeated expensive financing. Our top ten is a selected U.S.-listed shortlist with an explicit $300M-$2B capitalization window, not an exhaustive ranking of every small AI company. Micro-caps are excluded rather than relabeled to fill the list.", "小盘 AI 投资不是把大盘增速调高。客户依赖、融资限制、交易流动性与执行不确定可主导结果。成功技术若需反复昂贵融资，原始普通股也可能无好回报。本十股为精选美股名单，市值窗口明确为 3 亿至 20 亿美元，并非所有小型 AI 公司穷尽排序。微盘被剔除，不为凑名单改标签。"],
    ["Photronics, Red Violet and Ceva lead for an established commercial base, identifiable data/IP or a less speculative manufacturing role. Viant and Simulations Plus follow for monetized decision workflows, with distinct accounting and mix risks. AOSL and Cerence are cyclical or operational turnarounds. C3.ai and BigBear.ai are higher-risk application and contract cases. POET is an early optical commercialization option, placed last and excluded from the standard return model because smooth extrapolation from a tiny revenue base would be misleading. This is a research-priority ranking, not ten equally suitable investments.", "Photronics、Red Violet 与 Ceva 靠前，因成熟商业基础、可识别数据/IP 或较少投机的制造角色。Viant 与 Simulations Plus 有已变现决策工作流，却有会计与组合风险。AOSL 与 Cerence 属周期或经营转型。C3.ai 与 BigBear.ai 应用及合同风险更高。POET 属早期光学商业化可选性，排最后并退出标准收益模型，因微小收入平滑外推会误导。此为研究优先级，而非十个同等适宜投资。"],
  ] },
  { title: ["2. Direct AI exposure is not always better exposure", "2. 直接 AI 敞口不一定更好"], paragraphs: [
    ["An indirect photomask supplier can be a better investment than a pure-play application vendor if the former earns cash at a reasonable entry value and the latter cannot monetize demand. Conversely, a profitable legacy product can conceal a declining business that adds AI branding without creating incremental value. We classify exposure by the commercial mechanism and avoid inventing a percentage of AI revenue when the issuer has not separately disclosed it. Semiconductor masks and power components are enabling layers; identity graphs, advertising decisions and drug-modeling tools embed AI; C3.ai, Cerence and BigBear.ai have more direct application exposure.", "间接光罩商若在合理买价产生现金，可能优于无法变现的纯 AI 应用商。反之，盈利传统产品也可能掩盖衰退，只加 AI 标签而无增量价值。按商业机制分类，不编造公司未单独披露的 AI 收入占比。光罩与功率器件属支撑层，身份图谱、广告决策与药物建模嵌入 AI；C3.ai、Cerence 与 BigBear.ai 更直接参与应用。"],
    ["For edge IP, license wins must become royalty-bearing shipments. For identity data, permissions and regulatory acceptability must persist. For advertising, contribution after traffic acquisition costs matters more than gross billings. For drug simulation, validate recurring software growth separately from services. For automotive voice systems, distinguish ordinary royalties from fixed contracts and patent settlements. For defense vendors, distinguish funded backlog from an aspirational pipeline. These are practical links between product adoption and cash, not predictions that any particular AI architecture will dominate.", "边缘 IP 许可须转成带版税出货；身份数据须保持授权与监管可用性；广告扣流量成本贡献比总账单重要；药物仿真要分开经常软件与服务；车载语音须区分常规版税、固定合同及专利和解；国防须分清获拨款积压与愿景管线。这些是采用到现金的实际联系，并非某 AI 架构必胜预测。"],
  ] },
  { title: ["3. Financing and dilution are product risks", "3. 融资与稀释也是产品风险"], paragraphs: [
    ["A cash runway is not just cash divided by the latest accounting loss. Use restricted versus unrestricted cash, operating burn, committed capex, debt maturities, working capital and realistic funding access. One favorable cash-flow quarter may reflect collections or reduced spending that cannot recur. Equity issuance, warrants and convertible instruments can make headline market capitalization incomplete. POET illustrates the problem: one quote feed implies roughly 61M shares while another dated source reports 173.04M following financing. We use the latter for classification and disclose the conflict rather than infer a bargain from the stale number.", "现金跑道不只是现金除会计亏损。需区分受限现金、经营消耗、承诺资本开支、债务到期、营运资本与现实融资。一季好现金可能来自不重复回款或削减投入。增发、权证、可转债使标题市值不完整。POET 一报价源暗示约 6100 万股，另一注明日期来源报告融资后 1.7304 亿股；分类采用后者并披露冲突，不从旧数推断便宜。"],
    ["The scenario model assumes annual issuance and capitalizes negative modeled owner cash at a 10% funding cost. This is a stress convention, not a forecast of financing terms or available debt capacity. A real issuer may be unable to fund those losses at any price, or may sell assets and change strategy. Our bear case is not a minimum loss; complete impairment remains possible for any individual equity. Survival analysis and a full capital-structure bridge therefore precede using a favorable model result as an investment argument.", "情景模型假设年度发股，并把负模型股东现金按 10% 融资成本累积。这是压力约定，非融资条款或债务容量预测。实际公司可能无法融资，或需出售资产、改变战略。悲观情景不是最大损失，任何单只股权都可能全部损失。生存分析与完整资本结构桥接应先于把有利模型作为投资论据。"],
  ] },
  { title: ["4. Milestones, not a twenty-year spreadsheet", "4. 看里程碑，不迷信二十年表格"], paragraphs: [
    ["For these companies, a rolling sequence of commercial milestones is more useful than a precise twenty-year valuation. Require paid production adoption, repeat customers, demonstrable gross profit and an improving path to sustainable cash. For early hardware, require qualification and shipment acceptance, not merely memoranda or a potentially large order. For turnarounds, require durable renewal behavior and gross-margin recovery, not just a cost-cutting headline. Growth is valuable only if enough remains after reinvestment and the increase in share count.", "对这些公司，滚动商业里程碑比精确二十年估值有用。要求付费量产采用、重复客户、可证明毛利与持续现金路径；早期硬件看认证验收，而非备忘录或潜在大单；转型看持续续约与毛利恢复，而非削费新闻。增长只有在再投入及发股后仍保留足够价值才有意义。"],
    ["Use a higher return hurdle for greater execution and liquidity risk, but do not confuse a spreadsheet hurdle with compensation guaranteed by the market. The screen uses 20% annual capital-gain hurdle for small-caps, versus 15% for mid-caps. The hurdle entry column is a reverse-engineered price conditional on the modeled exit, not fair value or a recommendation. Evaluate liquidity and limit-order execution, but do not select position sizes from this report alone. A diversified core and a separately risk-budgeted speculative allocation are different decisions.", "较大执行与流动性风险要求更高门槛，但表格门槛不是市场保证补偿。小盘资本利得年门槛 20%，中盘 15%。门槛买价是基于模型退出倒推，不是公允价值或建议。应考虑流动性与限价执行，但不凭本文确定仓位。分散核心与单独风险预算的投机配置是不同决策。"],
  ] },
];
