"use client";

import { useState, type ReactNode } from "react";
import { COMPANIES, MARKET_DATE, RESEARCH_DATE, type Size } from "./data";
import { CASES, CASE_INPUTS, forecast, type Scenario } from "./model";
import { MID_REPORT, SMALL_REPORT } from "./report";

const fmt = (n: number, digits = 1) => n.toLocaleString("en-US", { minimumFractionDigits: digits, maximumFractionDigits: digits });
const pct = (n: number) => `${fmt(n * 100)}%`;
function Table({ label, headers, rows }: { label: string; headers: string[]; rows: ReactNode[][] }) {
  return <div role="region" aria-label={label} tabIndex={0} className="max-w-full overflow-x-auto focus:outline-2 focus:outline-emerald-700"><table className="w-full whitespace-nowrap text-left text-sm"><caption className="sr-only">{label}</caption><thead><tr>{headers.map((h,i)=><th key={i} scope="col" className="border-b border-zinc-400 px-3 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((cell,j)=><td key={j} className="border-b border-zinc-200 px-3 py-3 align-top tabular-nums">{cell}</td>)}</tr>)}</tbody></table></div>;
}

export default function ResearchView({ size, lang }: { size: Size; lang: "en" | "zh" }) {
  const zh = lang === "zh", index = zh ? 1 : 0;
  const t = (en: string, cn: string) => zh ? cn : en;
  const companies = COMPANIES.filter(c=>c.size === size);
  const chapters = size === "mid" ? MID_REPORT : SMALL_REPORT;
  const slug = `ai-${size}-cap-investment-outlook`;
  const [ticker, setTicker] = useState(companies[0].ticker);
  const [scenario, setScenario] = useState<Scenario>("base");
  const [horizon, setHorizon] = useState<5|10>(10);
  const [price, setPrice] = useState(String(companies[0].price));
  const company = companies.find(c=>c.ticker===ticker)!;
  const validPrice = Number.isFinite(Number(price)) && Number(price)>0;
  const result = forecast(company,scenario,horizon,validPrice?Number(price):company.price);
  const title = size === "mid" ? t("Top 10 Mid-Cap AI Stocks", "AI 中盘股：十大研究候选") : t("Top 10 Small-Cap AI Stocks", "AI 小盘股：十大研究候选");
  const field = "mt-1 w-full min-w-0 rounded border border-zinc-300 bg-white px-3 py-2 text-zinc-900";
  const labels = { bear: t("Bear", "悲观"), base: t("Base", "基准"), bull: t("Bull", "乐观") };
  const sectionTitle = "mb-4 text-2xl font-semibold";
  return <main data-company="ai-size" lang={lang} className="mx-auto w-full min-w-0 max-w-7xl bg-white px-4 py-10 text-zinc-900 sm:px-8">
    <nav aria-label={t("Research navigation", "研究导航")} className="mb-7 flex flex-wrap gap-4 text-sm underline"><a href="/research">{t("Research library", "研究库")}</a><a href={`/research/${slug}`}>English</a><a href={`/research/${slug}/zh`}>中文</a><a href="/research/ai-value-chain-investment-outlook">{t("AI value chain", "AI 价值链")}</a></nav>
    <header className="border-b border-zinc-200 pb-8">
      <p className="mb-3 text-sm font-medium text-emerald-800">{t("Hobite Research | AI investment shortlist", "Hobite 研究 | AI 投资候选名单")}</p>
      <h1 style={{color:"#18181b"}} className="text-4xl font-semibold sm:text-5xl">{title}</h1>
      <p className="mt-4 text-xl text-zinc-600">{t("Five- and ten-year opportunities, evidence and failure conditions", "五年与十年机会、证据与失效条件")}</p>
      <p className="mt-5 text-sm leading-7 text-zinc-600">{t(`Research cutoff ${RESEARCH_DATE}; market snapshot ${MARKET_DATE}. U.S.-listed selected universe; ${size === "mid" ? "$2B to below $10B" : "$300M to below $2B"} equity market cap. Ranking is subjective research priority, not a whole-market optimum, an undervaluation claim or personalized investment advice.`, `研究截点 ${RESEARCH_DATE}，市场快照 ${MARKET_DATE}。精选美股范围；普通股市值${size === "mid" ? "20 亿至不足 100 亿" : "3 亿至不足 20 亿"}美元。排序为主观研究优先级，不是全市场最优、低估保证或个性化投资建议。`)}</p>
    </header>
    <nav aria-label={t("Contents", "目录")} className="flex flex-wrap gap-5 border-b border-zinc-200 py-5 text-sm underline">{[["report",t("Investment thesis", "投资逻辑")],["ranking",t("Top 10", "十股排序")],["profiles",t("Company profiles", "公司分析")],["model",t("5 / 10 year scenarios", "五年 / 十年情景")],["audit",t("Sources and limits", "来源与局限")]].map(([id,label])=><a key={id} href={`#${id}`}>{label}</a>)}</nav>
    <section id="report" className="py-8"><h2 className={sectionTitle}>{t("Research report", "研究报告")}</h2>{chapters.map((chapter,i)=><article key={i} className="border-t border-zinc-200 py-6"><h3 className="mb-4 text-xl font-semibold">{chapter.title[index]}</h3><div className="max-w-5xl space-y-4 text-base leading-8 text-zinc-700">{chapter.paragraphs.map((p,j)=><p key={j}>{p[index]}</p>)}</div></article>)}</section>
    <section id="ranking" className="border-t border-zinc-300 py-8">
      <h2 className={sectionTitle}>{t("Ranked shortlist and financial evidence", "候选排序与财务证据")}</h2>
      <p className="mb-4 text-sm leading-7 text-zinc-600">{t("Editorial order emphasizes commercial evidence, defensibility, capital discipline and valuation risk. No numerical ranking score or scenario probability is claimed. Direct AI revenue shares are not inferred. Quarter revenue below is reported; revenue x 4 is a model baseline only, not TTM. Market caps use the dated quote vendor, except POET's disclosed alternate share-count calculation.", "编辑排序强调商业证据、防御力、资本纪律与估值风险，不宣称数值评分或情景概率，不推算 AI 收入占比。下表单季收入为报告事实；收入乘四仅为模型起点，不是过去十二个月。市值使用注明日期报价源，POET 除外，采用披露的替代股数计算。")}</p>
      <Table label={t("Ranked AI stocks", "AI 股票排序")} headers={["#",t("Company", "公司"),t("AI layer", "AI 环节"),t("Exposure", "敞口"),t("Price USD", "股价 美元"),t("Equity cap $M", "普通股市值 百万美元"),t("Quarter end", "单季期末"),t("Quarter sales $M", "单季收入 百万美元"),t("Cap / annualized sales", "市值 / 年化收入")]} rows={companies.map(c=>[c.rank,<a key={c.ticker} href={`#${c.ticker}`} className="font-semibold underline">{c.ticker}</a>,c.layer[index],c.exposure,`$${fmt(c.price,2)}`,fmt(c.capM),c.periodEnd,fmt(c.quarterRevenueM,3),`${fmt(c.capM/(c.quarterRevenueM*4))}x`])} />
      <figure className="mt-7 max-w-3xl"><figcaption className="mb-4 font-semibold">{t("Publication-date equity capitalization ($B)", "出版日普通股市值（十亿美元）")}</figcaption>{companies.map(c=><div key={c.ticker} className="mb-2 grid grid-cols-[60px_minmax(0,1fr)_65px] items-center gap-3 text-sm"><span>{c.ticker}</span><div className="h-3 bg-zinc-100"><div className="h-3 bg-emerald-700" style={{width:`${c.capM/(size==="mid"?10000:2000)*100}%`}} /></div><span className="text-right tabular-nums">{fmt(c.capM/1000,2)}</span></div>)}</figure>
    </section>
    <section id="profiles" className="border-t border-zinc-300 py-8"><h2 className={sectionTitle}>{t("Ten company investment cases", "十家公司投资逻辑")}</h2>{companies.map(c=><article key={c.ticker} id={c.ticker} className="border-t border-zinc-200 py-7"><h3 className="text-xl font-semibold">{c.rank}. {c.name} ({c.ticker})</h3><p className="mt-2 text-sm text-emerald-800">{c.layer[index]}</p><p className="mt-4 max-w-5xl text-base leading-8 text-zinc-700">{c.thesis[index]}</p><dl className="mt-4 max-w-5xl space-y-4 text-sm leading-7">{[[t("Reported evidence", "报告证据"),c.facts[index]],[t("Commercial milestone", "商业里程碑"),c.catalyst[index]],[t("Monitor", "监测"),c.monitor[index]],[t("Thesis failure", "逻辑失效"),c.failure[index]]].map(([k,v])=><div key={k}><dt className="font-semibold">{k}</dt><dd className="text-zinc-600">{v}</dd></div>)}</dl><p className="mt-4 text-sm"><a href={c.source} target="_blank" rel="noreferrer" className="underline">{t("Primary earnings evidence", "原始财报证据")}</a></p>{c.ticker==="AOSL"&&<p className="mt-2 text-sm"><a href="https://www.aosmd.com/application/cloud/server" target="_blank" rel="noreferrer" className="underline">{t("Power-product evidence", "电源产品证据")}</a></p>}</article>)}</section>
    <section id="model" className="border-t border-zinc-300 py-8">
      <h2 className={sectionTitle}>{t("Five- and ten-year return scenarios", "五年与十年回报情景")}</h2>
      <p className="mb-4 text-sm font-semibold">{t(`None of the modeled base cases clears the selected ${size === "mid" ? "15%" : "20%"} annual return hurdle at snapshot prices on either horizon. This is a due-diligence shortlist, not a list of ten proven bargains.`, `在快照价格下，已建模的基准情景均未在任一期限达到所选${size === "mid" ? "15%" : "20%"}年回报门槛。这是尽调名单，不是十个已证明便宜的股票。`)}</p>
      <p className="mb-4 text-sm leading-7 text-zinc-600">{t("Every forecast is a research assumption, not guidance or consensus. Capital-gain CAGR excludes dividends. Ranking does not follow modeled CAGR. A zero terminal value means model impairment, not a prediction that the issuer must fail. POET is milestone-only; no smooth return forecast is offered.", "全部预测为研究假设，非指引或一致预期。资本利得 CAGR 不含股息，排名不按模型 CAGR。终值为零表示模型减值，不预测公司必然失败。POET 仅看里程碑，不发布平滑收益预测。")}</p>
      <Table label={t("Return scenarios by company", "公司回报情景")} headers={[t("Stock", "股票"),t("Bear 5Y / 10Y CAGR", "悲观五年 / 十年 CAGR"),t("Base 5Y / 10Y CAGR", "基准五年 / 十年 CAGR"),t("Bull 5Y / 10Y CAGR", "乐观五年 / 十年 CAGR"),t("Base 10Y hurdle entry USD", "基准十年门槛买价 美元")]} rows={companies.map(c=>[c.ticker,...CASES.map(s=>{const f=forecast(c,s,5),ten=forecast(c,s,10);return f&&ten?`${pct(f.cagr)} / ${pct(ten.cagr)}`:t("Not modeled", "不建模");}),forecast(c,"base",10)?`$${fmt(forecast(c,"base",10)!.hurdlePrice,2)}`:"N/A"])} />
      <div className="mt-6 grid gap-4 border-y border-zinc-200 py-5 sm:grid-cols-2 lg:grid-cols-4">
        <label className="text-sm">{t("Company", "公司")}<select className={field} value={ticker} onChange={e=>{setTicker(e.target.value);setPrice(String(companies.find(c=>c.ticker===e.target.value)!.price));}}>{companies.map(c=><option key={c.ticker} value={c.ticker}>{c.ticker}</option>)}</select></label>
        <label className="text-sm">{t("Scenario", "情景")}<select className={field} value={scenario} onChange={e=>setScenario(e.target.value as Scenario)}>{CASES.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label>
        <label className="text-sm">{t("Horizon", "期限")}<select className={field} value={horizon} onChange={e=>setHorizon(Number(e.target.value) as 5|10)}><option value={5}>{t("5 years", "五年")}</option><option value={10}>{t("10 years", "十年")}</option></select></label>
        <label className="text-sm">{t("Entry price USD", "买入价 美元")}<input className={field} type="number" min="0.01" step="0.01" value={price} aria-invalid={!validPrice} onChange={e=>setPrice(e.target.value)} /></label>
      </div>
      {!validPrice&&<p role="alert" className="mt-3 text-sm text-rose-700">{t("Enter a positive price. Until then, calculations use the publication price.", "请输入正数价格；此前按出版日价格计算。")}</p>}
      {result?<><dl aria-live="polite" className="grid grid-cols-2 gap-5 py-6 lg:grid-cols-4">{[[t("Capital-gain CAGR", "资本利得 CAGR"),pct(result.cagr)],[t("Modeled exit price", "模型退出股价"),`$${fmt(result.exitPrice,2)}`],[t("Hurdle entry", "门槛买价"),`$${fmt(result.hurdlePrice,2)}`],[t("Exit funding deficit $M", "退出融资缺口 百万美元"),fmt(result.funding)]].map(([k,v])=><div key={k}><dt className="text-xs leading-5 text-zinc-500">{k}</dt><dd className="mt-2 text-xl font-semibold">{v}</dd></div>)}</dl><Table label={t("Annual research forecasts USD millions", "年度研究预测 百万美元")} headers={[t("Relative year", "相对年"),t("Growth", "增长"),t("Revenue $M", "收入 百万美元"),t("Owner cash margin", "股东现金率"),t("Owner cash $M", "股东现金 百万美元"),t("Quote-equivalent shares M", "报价等效股数 百万"),t("Funding deficit $M", "融资缺口 百万美元")]} rows={result.rows.map(r=>[r.year,pct(r.growth),fmt(r.revenue),pct(r.margin),fmt(r.ownerCash),fmt(r.shares),fmt(r.funding)])} /></>:<p className="py-6 text-sm leading-7">{t("POET's current scale does not support a comparable cash-margin forecast. Require volume shipment, acceptance, repeated revenue and a verified fully diluted capital structure before valuing a sustained commercial ramp.", "POET 当前规模不支持可比现金率预测。应先验证量产出货、验收、重复收入及完全稀释资本结构，再估值持续商业化。")}</p>}
      <h3 className="mb-4 mt-8 text-xl font-semibold">{t("Assumptions, not reported margins", "假设，不是报告利润率")}</h3>
      <Table label={t("Base model inputs", "基准模型输入")} headers={[t("Stock", "股票"),t("Starting revenue x4 $M", "起点收入乘四 百万美元"),t("Growth Y1-5 / Y6-10", "增长 1-5 / 6-10 年"),t("Owner cash margin Y1 → Y5", "股东现金率 第一年 → 第五年"),t("Annual dilution", "年度稀释"),t("Exit cash multiple", "退出现金倍数")]} rows={companies.map(c=>[c.ticker,c.modelAvailable?fmt(c.quarterRevenueM*4):"N/A",c.modelAvailable?c.growth.map(pct).join(" / "):"N/A",c.modelAvailable?c.cashMargin.map(pct).join(" → "):"N/A",c.modelAvailable?pct(c.dilution):"N/A",c.modelAvailable?`${c.multiple}x`:"N/A"])} />
      <Table label={t("Scenario adjustments", "情景调整")} headers={[t("Case", "情景"),t("Growth shift", "增长变化"),t("Cash-margin shift", "现金率变化"),t("Dilution shift", "稀释变化"),t("Exit multiple scale", "退出倍数系数")]} rows={CASES.map(s=>[labels[s],pct(CASE_INPUTS[s].growth),pct(CASE_INPUTS[s].margin),pct(CASE_INPUTS[s].dilution),`${fmt(CASE_INPUTS[s].multiple,2)}x`])} />
      <p className="mt-4 max-w-5xl text-sm leading-7 text-zinc-600">{t("Model equations: revenue baseline = quarter sales x 4; growth is compounded annually. Owner cash = revenue x assumed after-tax, after-interest, after-reinvestment cash margin, including normal compensation with no SBC addback. Margin ramps linearly from Y1 to Y5 and stays constant thereafter. Shares = quote-equivalent initial shares x compounded annual dilution (minimum zero issuance). Dilution is a separate conservative capital-structure stress, not a precise SBC reconciliation. Deficit funding = prior funding x 1.10 + negative owner cash. Positive cash is retained but not separately valued or distributed. Exit equity = max(0, next-year positive owner cash x multiple - funding); exit price = equity / end-horizon shares. CAGR = (exit price / entry price)^(1/years) - 1. Hurdle entry discounts that exit price at 15% for mid-cap or 20% for small-cap. These are reverse-engineered thresholds, not DCF fair values.", "公式：收入起点 = 单季乘四，年度复合增长。股东现金 = 收入 × 假设税后、利息后、再投入后现金率，含正常薪酬、不加回股权薪酬。现金率第一至第五年线性变化，之后固定。股数 = 初始报价等效股数 × 复合年度稀释（发股率最低零）。稀释另作保守资本结构压力，不是精确股权薪酬核对。缺口融资 = 上年融资 × 1.10 + 负股东现金。正现金留存但不另估值或分配。退出股权 = max(0, 下一年正现金 × 倍数 - 融资)，退出价除期末股数。CAGR = (退出价 / 买价)^(1/年数) - 1。门槛买价按中盘 15%、小盘 20% 折现退出价，是倒推阈值，非 DCF 公允价值。")}</p>
    </section>
    <section id="audit" className="border-t border-zinc-300 py-8"><h2 className={sectionTitle}>{t("Sources, eligibility and limitations", "来源、资格与局限")}</h2>
      <p className="mb-4 text-sm leading-7">{t("Sources were reviewed through October 5, 2026. Issuer releases substantiate the quarterly facts, not the forecast assumptions or editorial rankings. Prices and capitalization are frozen October 2 quote snapshots, not live quotes. The selected universe is not an index and the size cutoffs are house conventions. No issuer-wide AI revenue percentage, consensus target or guaranteed highest-ROI list is asserted.", "来源审阅至 2026 年 10 月 5 日。公司公告支持季度事实，不支持模型假设或编辑排序。价格市值冻结于 10 月 2 日，并非实时。精选范围不是指数，市值界限是本文约定。不宣称全公司 AI 收入占比、一致目标价或保证最高 ROI 名单。")}</p>
      <p className="mb-4 text-sm leading-7 text-zinc-600">{t("Important valuation omissions: no beginning cash, debt, preferred shares, tax receivable agreement or minority-interest bridge; no full GAAP forecast or historical financial database; quarterly seasonality is not normalized. BOX preferred claims, DSP Up-C/TRA economics, CRNC debt, and PLAB minority/cash-location issues require separate issuer work. POET uses 173.04M vendor-reported shares x $7.79 = $1,347.9816M, overriding a stale quote capitalization of about $475.9M. That count is not a fully diluted audit. Its financing and warrants require primary-register reconciliation. Model output must not be treated as a validated undervaluation conclusion.", "重要估值遗漏：未桥接初始现金、债务、优先股、税收应收协议或少数权益；非完整 GAAP 预测或财务历史库；未正常化季度季节性。BOX 优先股、DSP Up-C/税收协议、CRNC 债务及 PLAB 少数权益与现金所在地需另行研究。POET 用供应商股数 1.7304 亿 × 7.79 美元 = 13.479816 亿美元，覆盖旧报价约 4.759 亿美元市值。该股数不是完全稀释审计，融资权证须核对原始登记。模型不得当作已验证低估结论。")}</p>
      <p className="mb-4 text-sm leading-7 text-zinc-600">{t("Eligibility exclusions at the reviewed snapshot: IOT, CLS, FORM and AEIS exceed $10B; VERI, OSS, SSTK and REKR fall below $300M. INOD, AMBA and OUST are mid-caps rather than small-caps. These exclusions are about classification, not investment quality. A cap change after publication requires reclassification.", "审阅快照下分类排除：IOT、CLS、FORM、AEIS 超过 100 亿美元；VERI、OSS、SSTK、REKR 低于 3 亿美元。INOD、AMBA、OUST 为中盘非小盘。排除基于分类，不是投资质量；出版后市值变化须重新分类。")}</p>
      <ol className="space-y-4">{companies.map(c=><li key={c.ticker} className="border-t border-zinc-200 pt-4 text-sm leading-7"><a href={c.source} target="_blank" rel="noreferrer" className="font-semibold underline">{c.ticker} — {t("Primary quarterly evidence", "原始季度证据")}</a><p>{t("Reported period end", "报告期末")}: {c.periodEnd}. <a href={`https://finance.yahoo.com/quote/${c.ticker}/history/`} target="_blank" rel="noreferrer" className="underline">{t("Dated quote reference", "日期报价参考")}</a></p></li>)}</ol>
      {size==="small"&&<p className="mt-5 text-sm"><a href="https://stockanalysis.com/stocks/poet/" target="_blank" rel="noreferrer" className="underline">{t("POET alternate market-cap/share-count reference", "POET 替代市值与股数来源")}</a></p>}
      <p className="mt-6 text-sm leading-7 text-zinc-500">{t("Review checklist: validate reported periods; reconcile share classes and dilution; test a recession and lower exit multiple; confirm funding access; track paid renewals or shipment acceptance; compare with a diversified benchmark. The bull case has no assigned probability. The bear case does not cap losses. General educational research, not personalized investment advice.", "审阅清单：验证期间，核对股类与稀释，压力测试衰退与低退出倍数，确认融资，跟踪付费续约或验收，对比分散基准。乐观情景无指定概率，悲观情景不限制最大损失。仅供一般教育研究，非个性化投资建议。")}</p>
    </section>
  </main>;
}
